### ISSUE TITLE
Flag Node with WorkingSectionNode without searching the parent type each time

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1003]
In CobolNodeBuilder.EnterDataDescriptionEntry:
Instead of searching the parent type (WorkingStorage, LocalStoreage, ...) each time a EnterDataDescriptionEntry is create, use methods like EnterWorkingStorageSection/ExitWorkingStorageSection to remember the parent type.

**Comment by collarbe** [comment]
See commit https://github.com/TypeCobolTeam/TypeCobol/commit/ade3a011f872f1e9dd616ad098870521429c2d1d
