### ISSUE TITLE
Incremented pointer must be limited to 22 chars and not inside copy

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1011]
**FOLLOWING #780**

2 rules to add:
If a pointer is incremented with a set up/down by instruction, then its generated name will be:
its name + a hash of 8 characters.

We must then limit its name to 22 chars because our target compiler (IBM V4 for now) limit variable name to 30 chars.

As codegen cannot change COPY, pointer inside copy cannot be incremented.

**Comment by Brochato** [comment]
The 22 chars limit is respected in the redefines declaration generation (inside a type or not).
But its not in it usage, in the SET Statement generation.
