### ISSUE TITLE
Create Type from existing COPY

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1019]
As we have a lot of COPY in our legacy code, it would be nice to define a type from a COPY.
We have COPY which contains a level 01 data definition and those which start after level 01 and can contains several top data definition.

First we need to define a syntax.
A syntax that also works with our procedure (there is no level in our procedure parameters).

**Comment by smedilol** [comment]
One user wants to use this syntax to declare a type with a copy:
```cobol
       identification division.
       program-id. MyPGM.
       environment division.
       configuration section.
       source-computer. ibm-370
      *                 with debugging mode
                        .
       special-names. decimal-point is comma.
       data division.
       working-storage section.
      
      
       01 Type1 typedef strict.
          COPY MyCopyA REPLACING ==:Foo:== BY ==Foo==.
      
       01 Type2 typedef strict.
          COPY MyCopyB.
      
      
      
       end program MyPGM.
```

However the generated code duplicate the COPY instruction and only one of the instruction is commented:
```cobol
      *01 Type1 typedef strict.
      *   COPY MyCopyA REPLACING ==:Foo:== BY ==Foo==.
          COPY MyCopyA REPLACING ==:Foo:== BY ==Foo==.
      
      *01 Type2 typedef strict.
      *   COPY MyCopyB.
          COPY MyCopyB.
```

The codegen must not duplicate the instruction COPY and comment it.

**Comment by mayanje** [comment]
So my attempt will be to take in acount what is described in the sample, that is to say no duplicate the COPY line.
