### ISSUE TITLE
Use OrdinalIgnoreCase instead of InvariantCultureIgnoreCase

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1021]
When comparing String, OrdinalIgnoreCase is supposed to be faster than InvariantCultureIgnoreCase.

As the Cobol source code is not Culture dependant, we can switch to OrdinalIgnoreCase in SymbolTable and compare performance.

**Comment by cobarzanc** [comment]
Indeed, the OrdinalIgnoreCase StringComparer is much faster than InvariantCultureIgnoreCase. A performance comparaison is available here (https://blogs.msdn.microsoft.com/noahc/2007/06/29/string-equals-performance-comparison/). Using OrdinalIgnoreCase brings arroud 5x improvement in speed when compared to InvariantCultureIgnoreCase (in .Net 3.5)
