### ISSUE TITLE
Completion should add a "." after completing a type name

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1029]
When you ask completion after:
`01 var1 type `

Completion should propose type like:
- Bool
- Date
- String
But when selected, a `.` must be added after the type name.
This will allow the user to just hit `Enter` and declare its next data.

Note that when you complete a Type name inside a procedure, completion should not add "."
Because in procedure, only the last parameter has a "."

**Comment by smedilol** [comment]
See commit f44cba58907804830674a351bbf7d1d1c0e133ea

**Comment by collarbe** [comment]
@sarterbe found a case where putting the dot automaticaly is not efficient. 

01 myVar TYPE BOOL.

And the user wants to replace the BOOL type by anoter type using completion, there will be two dots. 

We need to check if a dot is already given in the code.
