### ISSUE TITLE
Completion should add a input, in-out and output when completing procedure parameters

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1030]
When you ask completion after a call. You get the list of all accessible procedures.
After selecting your procedure, if the procedure require parameter, then corresponding `input`, `in-out` or `output` keyword must be added.

Same logic when you select a parameter from the completion list. If the next word is `in-out` or `output` then add it automatically.

**Comment by Tenember** [comment]
The keywords after the parameters trigger only when the signature of the procedure is known or when all the procedures have the same number of parameters left to input.
