### ISSUE TITLE
SymbolTable.GetCustomTypesSubordinatesNamed is very slow

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1033]
I ran a new incremental test.
This time, I've included 12 types with about 15 children each.
I also excluded the CUPS preparation time.

Method SymbolTable.GetCustomTypesSubordinatesNamed took 60% of the time.
It's mainly caused by method Node.GetChildren<T>(string name, bool deep) where T : Node

Find a way to optimize this.

**Comment by smedilol** [comment]
As discussed last week, you can see how SymbolTable works for type/variable and search how to optimize this.

**Comment by cobarzanc** [comment]
@smedilol Can you check if the changes improuve the speed for your tests ?
