### ISSUE TITLE
Document our incremental pipeline

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1041]
We have a small internal doc about the incremental pipeline.
We need to publish it on our wiki.

**Comment by collarbe** [comment]
Is this doc stored iside source files of TypeCobol ?

**Comment by smedilol** [comment]
See menu "[Main phases](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolMainPhases)" on our wiki.
You can create a new page for incremental and reference it from the menu.
