### ISSUE TITLE
Duplicated dependency loading 

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#1056]
Working on a file named : ASLZ1ABS. 
And having dependecies like : ASLZ0SEC, ASLZ0ABS, ASLZZGES

Make TypeCobol parser crash saying ASLZ0ABS is defined multiple times

**Comment by collarbe** [comment]
The issue was due to a non named file containing a program ID equals to ASLZ0ABS. So there were 2 dependecy with "ASLZ0ABS" as a program name.

**Comment by smedilol** [comment]
We have the same problem again.

**Comment by smedilol** [comment]
Ok same reason here:
We had a file named `.tcbl` in our dependency folder.
This filed contained a duplicate program name, hence the bug.
