### ISSUE TITLE
Public/Private visibility refactoring

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#1081]
# Visibility
- Cobol 85 / 2002 use keywods (`no keyword` and `global`) to define visibility of variables at compile time.
  - Note that `external` doesn't affect visibility at compile time
- TypeCobol has introduced `private` and `public`

`private` and `public` doesn't have the same logic as `no keyword` or `global`

__(Breaking) changes:__
- [ ] A type declared with no keyword is no longer private.
  - No keyword means it's only visible in the program or function that declare it.
- [ ] You cannot combine global and (private or public) on type declaration
- [ ] Type declared in procedure can only be declared without keyword and will only be visible in the current procedure
- [ ] A private type or procedure is no longer visible in stacked program
- [ ] Private is the same as global-storage. Private is for type and function. Global-storage is for variable.
- [x] Type cannot be declared in global-storage
- [ ] Variable declared as Global are accessible from procedure, it shouldn't be the case #938

See the new visibility rules here:
[20180919-VisibilityRefactoring-v2.xlsx](https://github.com/TypeCobolTeam/TypeCobol/files/2966852/20180919-VisibilityRefactoring-v2.xlsx)

Or directly in this issue:

|           |             |                                 |         |                            |                |                                                          |                       |                                                                               |                       | 
|-----------|-------------|---------------------------------|---------|----------------------------|----------------|----------------------------------------------------------|-----------------------|-------------------------------------------------------------------------------|-----------------------| 
| What      | Declared in | Where                           | program | procedure                  | nested program | procedure in nested                                      | stacked program       | procedure in stacked                                                          | Outside module        | 
| Variable  | program     | working or local without global | Y       |                            |                |                                                          |                       |                                                                               |                       | 
| Variable  | program     | global                          | Y       |                            | Y              |                                                          |                       |                                                                               |                       | 
| Variable  | program     | global-storage                  | Y       | Y                          | Y              | Y (but procedure will be forbidden in nested in TC v1.5) |                       |                                                                               |                       | 
|           |             |                                 |         |                            |                |                                                          |                       |                                                                               |                       | 
| Type      | program     |                                 | Y       |                            |                |                                                          |                       |                                                                               |                       | 
| Type      | program     | global                          | Y       |                            | Y              |                                                          |                       |                                                                               |                       | 
| Type      | program     | private                         | Y       | Y                          | Y              | Y (but procedure will be forbidden in nested in TC v1.5) |                       |                                                                               |                       | 
| Type      | program     | private global (forbidden)      |         |                            |                |                                                          |                       |                                                                               |                       | 
| Type      | program     | public                          | Y       | Y                          | Y              | Y (but procedure will be forbidden in nested in TC v1.5) | Y with program prefix | Y with program prefix (but procedure will be forbidden in stacked in TC v1.5) | Y with program prefix | 
| Type      | program     | public global (forbidden)       |         |                            |                |                                                          |                       |                                                                               |                       | 
| Type      | program     | global-storage (forbidden)      |         |                            |                |                                                          |                       |                                                                               |                       | 
|           |             |                                 |         |                            |                |                                                          |                       |                                                                               |                       | 
| Type      | procedure   |                                 | N       | Y (only current procedure) |                |                                                          |                       |                                                                               |                       | 
| Type      | procedure   | private (forbidden)             |         |                            |                |                                                          |                       |                                                                               |                       | 
| Type      | procedure   | global (forbidden)              |         |                            |                |                                                          |                       |                                                                               |                       | 
| Type      | procedure   | public (forbidden)              |         |                            |                |                                                          |                       |                                                                               |                       | 
| Procedure | Program     |                                 | Y       |                            |                |                                                          |                       |                                                                               |                       | 
| Procedure | Program     | private                         | Y       | Y                          | Y              | Y (but procedure will be forbidden in nested in TC v1.5) |                       |                                                                               |                       | 
| Procedure | Program     | public                          | Y       | Y                          | Y              | Y (but procedure will be forbidden in nested in TC v1.5) | Y with program prefix | Y with program prefix (but procedure will be forbidden in stacked in TC v1.5) | Y with program prefix | 

_Only new   keyword : private, public make a type visible to a procedure. These keywords   are NOT available to data_

# Technical hints
New scope in SymbolTable are:

        /// <summary>
        /// Cobol has compile time binding for variables, sometimes called static scope.
        /// Within that, Cobol supports several layers of scope: Global and Program scope.
        ///
        /// TypeCobol has Intrinsic scope used for standard library types and variables.
        /// TypeCobol has Function scope used for types and variables declared inside a function.
        /// </summary>
        public enum Scope
        {
            /// <summary>
            /// Intrinsic scope is a specific to TypeCobol.
            /// </summary>
            Intrinsic,

            /// <summary>
            /// Namespace scope is a specific to TypeCobol. It registers all the different parsed programs. 
            /// </summary>
            Namespace,

            /// <summary>
            /// GlobalStorage scope is TypeCobol specific. It will store all the DataEntry data are decalred inside a GLOBAL-STORAGE SECTION
            /// These variables will be accessible by all the nested programs. All the procedures will also have access to these variables. 
            /// Issue #805
            /// SymbolTable Enclosing Scopes allows to respect the rules : 
            ///     - GLOBALSS_RANGE 
            ///     - GLOBALSS_NOT_FOR_STACKED 
            /// </summary>
            PrivateGlobalStorage,
            Global,
            Local
        }

**Comment by smedilol** [comment]
Note : commits c353d11 and d800fbe has been done on Namespace branch because first we intended to do all these changes at the same time of namespace implementation.
Now namespace implementation is postpone to end of 2019 or for 2020.

**Comment by smedilol** [comment]
I made a mistake in the visibility. I've uploaded a new file.
I've also added details about visibility of procedure.

**Comment by fm-117** [comment]
CobolDefault to be renamed to Local.

**Comment by fm-117** [comment]
The attached file describes current model and proposed model for this issue.
[symboltable_instances_05-08-19.pptx](https://github.com/TypeCobolTeam/TypeCobol/files/3467848/symboltable_instances_05-08-19.pptx)
- Each box represents an instance of SymbolTable (number of such instances is written next to it)
- Scopes in the proposed model are :
  - __Intrinsic__ : contains external types and procedures loaded from intrinsic files
  - __Namespace__ : contains all known programs at compile time (includes current main, nesteds and stackeds and also external dependencies)
  - __Program__ : contains private and public types and procedures and also variables declared in global-storage section
  - __Global__ : contains variables flagged with GLOBAL keyword
  - __Local__ : contains types, procedures and variables declared without any modifier
  - __Function__ : contains types and variables declared within a procedure

**Notes** :
- _Program_ is different in the new model, it corresponds to items that are visible through the entire span of a program
- in this model public and private types/procedures from Nested are bound to Program Scope from Main which means they are visible from Main itself and all Nested
- This kind of declarations may be forbidden in future releases

**Comment by smedilol** [comment]
Ok for me.

**Comment by fm-117** [comment]
Closed with PR #1468.

**Comment by fm-117** [comment]
Summary of visibility rules.
TypeCobol uses 4 visibilities :
- Local
- Global
- Private
- Public

**Local visibility :**
It is the default visibility in Cobol, it is declared using `no keyword`. In TypeCobol it applies to types, variables and procedures. _It means that the type, variable or procedure is only visible in the program or procedure that declares it_ (but not in its nested programs and procedures).

**Global visibility :**
It is declared with the `GLOBAL` keyword and it applies to types and variables, a procedure can't be marked as global. _It means that the variable or type is visible in the program that declares it and its nested programs_ (but not in its procedures).

**Private visibility :**
Private visibility is specific to TypeCobol, it is declared using the `PRIVATE` keyword. It applies to types and procedures. _It means that the type or procedure is visible in the entire span of the program that declares it_ (including its nested programs and procedures). `PRIVATE` keyword cannot be used inside procedures and cannot be combined with the `GLOBAL` keyword. To achieve the same effect on a variable, it must be declared in GLOBAL-STORAGE SECTION.

**Public visibility :**
Public visibility is similar to private visibility except that it also extends the visibility to outside of the program. It applies to types and procedures and cannot be used on variables. A public type or procedure is visible in the entire span of a program that declares it and can also be used from another program as long as it is prefixed with the declaring program name. Just like the `PRIVATE` keyword, `PUBLIC` keyword cannot be used inside procedures and cannot be combined with `GLOBAL` keyword.
