### ISSUE TITLE
Completion should be able to suggest children compatible variable

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#1082]
In the following case : 

```COBOL
01 ArrayDesc.
  05 var1 PIC 9.
  05 var2 PIC 9.

MOVE 1 TO ...
```

The completion does not suggest variable like `ArrayDesc::var1` or `ArrayDesc::var2`. It could be great, but it has to be discuss, this solution may suggest all the numeric varaible available.. it would be to much.

**Comment by smedilol** [comment]
duplicate of #907
