### ISSUE TITLE
Shared visibility

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#1097]
### Description 
`shared`: Visible on a specified root namespace and its children

Can be used on :

- Type (declared in a program, nested, stacked or in a procedure)
- A type declared shared in a procedure of a nested program will be visible in the main program and programs declared in the root namespace
- Procedure

 _To be completed_

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
