### ISSUE TITLE
TALLY is changed to ALL in error message

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1120]
**Describe the bug**
Symbol `TALLY` is changed in `ALL` in error message

**To Reproduce**
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZS0OSM.
      
       procedure division.
      
           if foo(tally)
                continue
           end-if
           goback.
       END PROGRAM DVZS0OSM.
```
As `foo` is not declared you get an error.
But you get:
`Syntax error : Symbol foo(ALL) is not referenced`
instead of 
`Syntax error : Symbol foo(TALLY) is not referenced`

If `foo` is declared as a level 88, then there is no error.
The generated code is also ok.

**Comment by fm-117** [comment]
@smedilol I've tested the sample on the current develop in RdZ and the error message is correct (displaying `Semantic error: Symbol foo(tally) is not referenced`) so can we close this issue ?

**Comment by smedilol** [comment]
@fm-117 The solution from PR #1124 is not perfect because token `ALL` is still used.

**Comment by fm-117** [comment]
Ok so we could do something like in #1841: change the `SyntaxProperty<bool> ALL` into a `SyntaxProperty<enum>` to capture the presence of either `ALL` keyword or `TALLY` keyword.
