### ISSUE TITLE
Formalized comment doesn't works in incremental

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1130]
**Describe the bug**
When you type a formalized comment `*<<<     my comment *>>>' you get an error.
You need to re-synchronize the document to get rid of this error.

**Comment by smedilol** [comment]
See if #1234 and #1229 fix this

**Comment by smedilol** [comment]
@sarterbe can you check if the last version still procedure error with formalized comment ?

**Comment by maxime645** [comment]
The issue is still occuring. 
When adding a new @keyword, the first line of TypeCobol code after it shows a syntax error. It goes away when a manual save is made.
There is no error thrown when adding a simple description without the keyword @description.

**Comment by mayanje** [comment]
This issue is reopened because in fact the flag FormalizedCommentLineEnd is not necessary
