### ISSUE TITLE
Unterminated literals doesn't generate an error

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1160]
**Describe the bug**
A unterminated literals doesn't generate an error.

**To Reproduce**
The terminal `"` is not present in the display statement:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       PROCEDURE DIVISION .
           display "Hello
           goback
           .
       END PROGRAM DVZF0OSM.
```

**Expected behavior**
First check is this is allowed by Cobol standard.
If this is not allowed, then generate an error because the terminal `"` is not present.
If it's allowed, then generate a warning because it's clearly not usual to see this syntax.

**Comment by fm-117** [comment]
IBM compiler returns an error: `An alphanumeric literal was not properly continued.  The end of the literal was assumed on the last source line.` but positioned on the next line.
Current implementation of our parser returns: `Syntax error : Literal is not correctly delimited.` on the line containing the literal.
Should we close this issue ?

**Comment by smedilol** [comment]
Yes it's working.
Can you check if we have unit test for this issue?

**Comment by fm-117** [comment]
@smedilol We do.
See https://github.com/TypeCobolTeam/TypeCobol/blob/develop/TypeCobol.Test/Parser/Programs/Cobol85/CharOutsideEditableRange.rdz.cbl and https://github.com/TypeCobolTeam/TypeCobol/blob/bc6e49a2daee2867f25ea3d2f11850a72812a589/TypeCobol.Test/Parser/Scanner/TestTokenTypes.cs#L87

Closing this issue.
