### ISSUE TITLE
Documentation: Formalized Comments, Multiline Comments and Documentation generation

### ISSUE THREAD

**Issue by Brochato** [TypeCobolTeam/TypeCobol#1176]
# Commentaires Formalisées et Documentation

## Principe de base

Les commentaires formalisés ont pour but de permettre au développeur de renseigner des métas donnés concernant les Nodes suivants :
-	Fonctions/Procédures
-	Types
-	Programmes
On récupère ces informations pour générer une documentation en y ajoutant des informations des Nodes eux même comme le nom, le Namespace ou encore la visibilité.

## Scanner

Les TokenTypes et leur TokenFamilly sont présents dans TypeCobol/Compiler/Scanner/TokenType.cs.

Tout d’abord les balises ouvrantes et fermantes (des commentaires formalisés et multilignes) ne sont pas prises comme des commentaires standards pour qu’ils passent dans le scanner. 

![image](https://user-images.githubusercontent.com/38039171/47792338-18d16900-dd1c-11e8-89eb-8ced2e28a339.png)

Les balises ouvrantes sont traitées dans le switch principale :

![image](https://user-images.githubusercontent.com/38039171/47792368-2a1a7580-dd1c-11e8-9877-a754a519f76c.png)
![image](https://user-images.githubusercontent.com/38039171/47792375-3272b080-dd1c-11e8-9892-83a379cf2501.png)
![image](https://user-images.githubusercontent.com/38039171/47792378-356da100-dd1c-11e8-842a-7f10f695fbb3.png)

Le premier caractère visible par le scanner est le ‘<’ car le ‘\*’ se trouve en colonne 7 et le scanner regarde a partir de la colonne 8. On teste quand même la présence du ‘\*’ à la position n-1.

On détecte aussi les balises ouvrantes hors colonne 7 pour mettre un warning et quand même créer les Tokens pour ne pas gêner le parsing.

![image](https://user-images.githubusercontent.com/38039171/47792417-461e1700-dd1c-11e8-8a7d-4c1d86661487.png)
![image](https://user-images.githubusercontent.com/38039171/47792421-49190780-dd1c-11e8-9294-8f0773cde845.png)
![image](https://user-images.githubusercontent.com/38039171/47792425-4b7b6180-dd1c-11e8-8412-95b7605bb0b7.png)

Quand on ajoute un Token de balise ouvrante ou fermante, on modifie le ScanState (MultilineScanState.cs) pour indiquer que l’on se trouve dans le contexte d’un commentaire formalisée.

![image](https://user-images.githubusercontent.com/38039171/47792440-56ce8d00-dd1c-11e8-872e-79e6e6c868cd.png)
![image](https://user-images.githubusercontent.com/38039171/47792443-58985080-dd1c-11e8-94c4-d6f51c49d12c.png)
![image](https://user-images.githubusercontent.com/38039171/47792449-5afaaa80-dd1c-11e8-8c2a-84425aad67bf.png)

Pour ne pas générer des Token propres à TypeCobol qui n’ont pas de sens dans le contexte des commentaires formalisées ou des commentaires multilignes, le reste du scan se fait dans un switch séparé du switch principal.  

![image](https://user-images.githubusercontent.com/38039171/47792466-66e66c80-dd1c-11e8-9aec-f4534fe7e201.png)
![image](https://user-images.githubusercontent.com/38039171/47792470-6948c680-dd1c-11e8-8215-e910562e1ff3.png)
![image](https://user-images.githubusercontent.com/38039171/47792483-6f3ea780-dd1c-11e8-969f-2f098587cdb8.png)

Ainsi,  comme le scanner ne passe que dans le switch dédié aux commentaires formalisés si une balise ouvrante est trouvée, la détection de la balise fermante ne se fait que dans ce switch.

Les mots clés sont reconnus si le dernier token significatif est un ‘@’ via ScanCharacterString(startIndex) qui évalue le mot démarrant à startIndex. Si nous sommes dans le contexte d’un commentaire formalisé, on évalue le mot pour savoir à quel mot clé il correspond.

![image](https://user-images.githubusercontent.com/38039171/47792506-7796e280-dd1c-11e8-82bf-47f174cb01ef.png)
![image](https://user-images.githubusercontent.com/38039171/47792509-79f93c80-dd1c-11e8-8cb1-1af2c8ecdc0e.png)
TokenType.UserDefinedWord est utilisé pour une clé de Params. 
 

Pour autoriser les mots clés dans le nommage des paramètres, on vérifie que si on trouve un mot clé, que nous sommes juste après un ‘-‘ et que le précédent mot clé trouvé est le mot clé ‘@Parameters’. Si c’est le cas, on corrige le Type de Token en TokenType.UserDefinedWord.
 
![image](https://user-images.githubusercontent.com/38039171/47792534-82ea0e00-dd1c-11e8-8189-b2f9b290b528.png)
 
Enfin, si ce n’est ni un mot clé, ni une clé de ‘@Parameters’, c’est une valeur. Les valeurs ne pouvant pas précéder d’autres Token sur une ligne, on regroupe tout le reste de la ligne dans un même Token TokenType.FormComsValue grâce à ScanUntilDelimiter(startIndex, tokenType, delimiter)
 
![image](https://user-images.githubusercontent.com/38039171/47792677-d2303e80-dd1c-11e8-8595-7c94991b45f1.png)

Cette méthode scanne le reste de la ligne et renvoie un Token du type spécifié allant jusqu’à la fin de la ligne ou jusqu’au délimiteur spécifié.
Le délimiteur ici est "*>>>", malgré le fait que ce soit pour l’instant impossible de le rencontrer, comme la balise fermante ne peux se trouver qu’en colonne 7. Cela permettra dans le futur d’avoir une syntaxe comme celle-ci :
>*<<< Ici mon commentaire formalisé sur une seule ligne *>>>

## Grammaire

La grammaire des commentaires formalisée se décompose comme suit :
 
![image](https://user-images.githubusercontent.com/38039171/47792757-f429c100-dd1c-11e8-9d45-b9ea46b66c8d.png)

Elle est composé de : une balise ouvrante, n lignes et une balise fermante.
Il existe trois types de lignes :
* Les lignes de niveau « extérieur » qui commencent par ‘’@’’ sont composé d’un mot clé + ‘’ : ’’ (optionnel, le ‘’ : ‘’ n’a qu’un but de clarté du code)  et une valeur (optionnel)
* Les lignes de niveau « intérieur » servant à lister des valeurs se composent de ‘’-‘’ + une valeur dans le cas d’un listing simple (pour Todo et Needs) ou de ‘’-‘’ + clé (UserDefinedWord) + ‘’ : ’’ (optionnel, toujours un but de clarté) et une valeur. Un listItem de type clé-valeur ne s’applique que à ‘@Params’.
* Les lignes simplement composé d’une valeur qui sera rattaché à l’instruction précédente.
Cette grammaire s’intègre au début de celle d’une Fonction, d’une définition de type et d’une Procedure Division ainsi les tokens du commentaire formalisé sont inclue dans le CodeElements suivant et il n’y a donc pas de CodeElements dédiés aux commentaires formalisés
 

![image](https://user-images.githubusercontent.com/38039171/47792769-fb50cf00-dd1c-11e8-9847-b31d0c5f2fd4.png)
![image](https://user-images.githubusercontent.com/38039171/47792779-01df4680-dd1d-11e8-899d-15cdf2abd4f8.png)
![image](https://user-images.githubusercontent.com/38039171/47792785-04da3700-dd1d-11e8-9af1-621cf8e160ac.png)

![image](https://user-images.githubusercontent.com/38039171/47792836-2affd700-dd1d-11e8-8a6c-070ccdd7521e.png)

### Commentaires formalisées

On implémente l’interface IFormalizedCommentable aux CodeElements applicables. Cette interface force ces CodeElements à avoir une propriété FormalizedCommentDocumentation de type FormalizedCommentDocumentation qui contiendra les données du commentaire formalisé.

![image](https://user-images.githubusercontent.com/38039171/47792995-892cba00-dd1d-11e8-9f43-fde773d0e0c7.png)
![image](https://user-images.githubusercontent.com/38039171/47793001-8af67d80-dd1d-11e8-9ebf-60079c84c8e8.png)
![image](https://user-images.githubusercontent.com/38039171/47793007-8df16e00-dd1d-11e8-9bd3-dcc892c38741.png)
![image](https://user-images.githubusercontent.com/38039171/47793011-8fbb3180-dd1d-11e8-8b0c-901d0aa4cd93.png)

![image](https://user-images.githubusercontent.com/38039171/47793040-9ea1e400-dd1d-11e8-8afb-a11fe1c671f3.png)

La propriété privée _lastParameterRegistered enregistre la dernière clé ajouté à la propriété Parameters  pour y rattacher les valeurs seules sur leur ligne (le cas d’une continuation de ligne). En effet, comme c’est un Dictionnaire, la propriété n’est pas ordonnée et n’a donc pas de « dernier » élément comme les listes Needs et ToDo
Les autres Propriétés sont les données renseignables dans un commentaire formalisé.

Il y a deux méthodes Add qui servent à ajouter une valeur à la propriété associée à un mot clé.
```C#
void Add(Fields parameter, IToken symbol, bool isContinuation)
```
Pour les valeurs simples (tout sauf @Params). isContinuation sert, dans le cas des listes, à spécifier si c’est la continuité d’une valeur ou une nouvelle valeur, donc de savoir s’il faut créer un nouvelle élément ou concaténer la valeur au dernier élément.
```C#
void Add(Fields parameter, string key, string value)
```
Pour les couples clé-valeur (@Params)

Le constructeur s’occupe de décortiquer le contexte retourné par Antlr et ajouter les bonnes valeurs aux bonnes propriétés.

Ces Propriétés sont créées au CodeElementBuilders directement après le parsing d’Antlr.

### Commentaires multilignes

Il faut injecter les tokens des commentaires multilignes dans les CodeElements correspondant à leurs lignes pour pouvoir les repérer et les commenter dans la phase de génération de Code.
Ceci est effectué dans CodeElementsParserStep :

![image](https://user-images.githubusercontent.com/38039171/47793073-b7aa9500-dd1d-11e8-868f-5dbc7b19c414.png)

### Fonctions

Pour les fonctions, on vérifie si il y a des paramètres dans ‘@Params’ qui ne correspondent pas à des paramètres présents dans la signature de la Fonction, pour y placer un Warning.
 
![image](https://user-images.githubusercontent.com/38039171/47793082-be390c80-dd1d-11e8-9956-1ccb8d232007.png)

De la même manière, on vérifie si des paramètres présents dans la signature de la Fonction ne le sont pas dans la section ‘@Params’ des commentaires formalisés pour y placer un Warning.
 
![image](https://user-images.githubusercontent.com/38039171/47793264-2e479280-dd1e-11e8-9a3c-ad402eeee63a.png)

On vérifie enfin s’il y a un mot clé qui est déclaré deux fois pour y placer un Warning. Cette action est factorisée dans une méthode statique car elle est utilisée pour chaque structure acceptant un commentaire formalisé. 

![image](https://user-images.githubusercontent.com/38039171/47793276-369fcd80-dd1e-11e8-95a7-3a4f0d96995b.png)
![image](https://user-images.githubusercontent.com/38039171/47793278-39022780-dd1e-11e8-9d66-3f12440179e5.png)
 
### Type Définition

Pour les types on vérifie si il y le champ ‘@Params’ déclaré pour y placer un Warning.
 
![image](https://user-images.githubusercontent.com/38039171/47793285-3f909f00-dd1e-11e8-8ed4-70c344972bed.png)

Enfin on vérifie  s’il y a un mot clé qui est déclaré deux fois pour y placer un Warning.
 
![image](https://user-images.githubusercontent.com/38039171/47793304-461f1680-dd1e-11e8-9bb7-a83e2b17b1fd.png)
 
### Programmes
Pour les fonctions, on vérifie si il y a des paramètres dans‘@Params’ qui ne correspondent pas à des paramètres présents dans la section using de la Procedure Division pour y placer un Warning.
 
![image](https://user-images.githubusercontent.com/38039171/47793316-4ae3ca80-dd1e-11e8-857f-df8418b1e6d1.png)

De la même manière, on vérifie si des paramètres présents dans la section using de la Procedure Division ne le sont pas dans la section ‘@Params’ des commentaires formalisées pour y placer un Warning.
 
![image](https://user-images.githubusercontent.com/38039171/47793327-4fa87e80-dd1e-11e8-9521-eb377c624d36.png)

On vérifie enfin s’il y a un mot clé qui est déclaré deux fois pour y placer un Warning.
 
![image](https://user-images.githubusercontent.com/38039171/47793337-559e5f80-dd1e-11e8-89ef-c53971d9507f.png)

### Procédure Division

On vérifie si la Procédure Division à laquelle est rattachée le commentaire formalisé est bien la Procédure Division d’un Programme et pas d’une déclaration de fonction.
 
![image](https://user-images.githubusercontent.com/38039171/47793343-5afbaa00-dd1e-11e8-981d-667bc0b77199.png)
 

## Génération de la documentation

La Génération de la documentation se fait en mettant l’argument du CLI OutputFormat à Documentation (-f 4 OU -f Documentation). Le générateur s’occupant de la documentation utilise un Visiteur dédié qui crée un DTO pour chaque TypeDefinition, FunctionDeclaration et Program et les stocke dans une liste de documentation.
 
![image](https://user-images.githubusercontent.com/38039171/47793393-71096a80-dd1e-11e8-992e-629566dc0421.png)

Les DTOs :
 
![image](https://user-images.githubusercontent.com/38039171/47793403-75358800-dd1e-11e8-8e42-e308d9251045.png)

A noter que les DTOs possèdent tous un constructeur par défaut vide qui est nécessaire à la sérialisation.

### Documentation

![image](https://user-images.githubusercontent.com/38039171/47793744-42d85a80-dd1f-11e8-991b-52f912da496a.png)

Documentation est la classe de base qui implémente les propriétés et la logique commune aux trois types de commentaires formalisés. Elle contient tous les champs des commentaires formalisés sauf ‘@Params’ qui ne sont utilisés que pour les fonctions et les procédures. Elle contient aussi des informations qui ne se trouvent pas dans les commentaires formalisés comme le nom, la visibilité et le namespace. 
Elle initialise ses propriétés avec son constructeur :
A noter que Deprecated ne s’initialise pas comme les autres propriétés car il peut représenter un booléen à true si il contient un string vide, il ne faut donc pas utiliser IsNullOrEmpty().

Documentation possède aussi la méthode CreateAppropriateDocumentation() qui permet de créer un documentation sans savoir si le node est de type Program, FunctionDeclaration ou TypeDefinition. C’est la méthode qui est toujours utilisée pour créer une documentation.
 
![image](https://user-images.githubusercontent.com/38039171/47793755-479d0e80-dd1f-11e8-9d95-777000da7a0b.png)

C’est aussi Documentation qui implémente les méthodes de sérialisation. Pour l’instant en XML ou JSON, mais si un autre format est nécessaire, il suffit d'implémenter la nouvelle méthode à Documentation.
 
![image](https://user-images.githubusercontent.com/38039171/47793763-4bc92c00-dd1f-11e8-91a6-71f4ea5139db.png)

### DocumentationDataType

![image](https://user-images.githubusercontent.com/38039171/47793915-a06ca700-dd1f-11e8-89db-daecff2590d0.png)

DocumentationDataType définie les données communes aux variables présentes dans la documentation comme le type lui-même, ses éventuelles enfants, les paramètres de fonctions et les paramètres de programmes.

Elle est composée de deux constructeurs :
`DocumentationDataType(DataDefinition dataDef)`
Qui prend en paramètre un DataDefinition, un node qui définit une donnée mais n’est pas serialisable directement. Ce constructeur en extrait la majeure partie de ses données directement et récupère la valeur par défaut de la variable avec son codeElement.

![image](https://user-images.githubusercontent.com/38039171/47793951-b4180d80-dd1f-11e8-9428-279c3d75d483.png)

Le second constructeur :
```
DocumentationDataType(DataUsage? usage = null, long maxOccurence = 1,
string defaultValue = null, string typeName = null, string picture = null)
```
N’est jamais utilisé pour l’instant mais peut être utile si on doit créer un dataType sans avoir de DataDefinition.
 
![image](https://user-images.githubusercontent.com/38039171/47793967-bd08df00-dd1f-11e8-8adf-366276e0459d.png)

 
### DocumentationTypeChildren

![image](https://user-images.githubusercontent.com/38039171/47793976-c42fed00-dd1f-11e8-8800-e63996f36dea.png)

DocumentationTypeChildren regroupe les données des enfants du type si ce dernier est un groupe. En plus du DocumentationDataType, il comporte des propriétés que l’on ne peut retrouver que chez les enfants d’un Type tel que les conditions des niveaux 88, IsBlankWhenZero, Justified etc.
IsSubGroup indique que cet enfant a lui-même des enfants.

Il est composé d’un constructeur prenant en paramètre un DataDefinition qui permet d’instancier toute les propriétés de l’objet.

![image](https://user-images.githubusercontent.com/38039171/47793984-c85c0a80-dd1f-11e8-8617-250adb9f0944.png)

### DocumentationForType

![image](https://user-images.githubusercontent.com/38039171/47794002-d447cc80-dd1f-11e8-98ff-3afa3a3dafe7.png)

Représente la documentation propre aux définitions de types. En plus des propriétés héritées de Documentation, elle contient les propriétés définissant son type de donnée DocDataType de type DocumentationDataType, IsBlankWhenZero et Justified qui sont des options utilisables pour un Type et ses enfants mais pas pour des paramètres de fonction/programmes, donc ne figurent pas dans DocumentationDataType. Elle comprend aussi la liste d’enfants du type pour y enregistrer leur DocumentationTypeChildren. À l’instar des Nodes, la liste de childrens ne possède que la DocumentationTypeChildren des enfants directs du type, les sous enfants se trouvent dans la liste de childrens de leurs parents directs. 

Le constructeur de DocumentationForType prend le node documentable TypeDefinition pour en tirer, avec son codeElement, un maximum d’informations.

![image](https://user-images.githubusercontent.com/38039171/47794011-db6eda80-dd1f-11e8-9bae-51fd456b0323.png)

 ### DocumentationParameter 

![image](https://user-images.githubusercontent.com/38039171/47794021-e295e880-dd1f-11e8-8223-736a546d5f10.png)

DocumentationParameter regroupe les données des paramètres des fonctions et des programmes. En plus du DocumentationDataType, il comporte des propriétés que l’on ne peut retrouver que chez les paramètres tel que les informations renseignées dans les commentaires formalisés (@Params), le passing type (input, output, inout) et son nom.

Il est composé de deux constructeurs : 
```C#
public DocumentationParameter(ParameterDescription parameter, string info)
```
Le premier constructeur prend en paramètre un ParameterDescription contenant les informations liées au dataType et un string qui contient la description du commentaire formalisé si elle existe. Le passing type est contenu dans le ParameterDescription. Ce constructeur est utilisé par les Fonctions.

![image](https://user-images.githubusercontent.com/38039171/47794159-2f79bf00-dd20-11e8-9432-f84a1265f671.png)
 

```C#
public DocumentationParameter(DataDefinition dataDef, string info, bool determinePassing = true)
```
Le second constructeur prend en paramètre une DataDefinition contenant les informations liées au dataType, un string qui contient la description du commentaire formalisé si elle existe et un booléen qui indique si on doit déterminer le PassingTypes avec la description du commentaire formalisé ou non. Ce constructeur est utilisé par les Programmes car DataDefinition ne supporte pas le PassingTypes. Il faut donc le déterminer si possible.
 
![image](https://user-images.githubusercontent.com/38039171/47794166-343e7300-dd20-11e8-9e6f-c18e229c1899.png)

La reconnaissance du PassingTypes se fait par la méthode suivante 
```C#
Tuple<PassingTypes, string> DetermineType(string info)
```
Elle prend en paramètre la description du commentaire formalisé et en extrait le premier mot. Si ce dernier est ‘INPUT’, ‘OUTPUT’, ‘INOUT’ (case insensitive) alors on enregistre le passing type adéquat et on tronque l’info jusqu’au premier caractère alphabétique et on renvoie un Tuple<PassingTypes, string> du passing type trouvé et de la description tronquée. Ainsi, une description du type :
‘Input – Description de mon paramètre’
Donne le Tuple {PassingTypes.Input, ‘Description de mon paramètre’} 
Et pas le Tuple {PassingTypes.Input, ‘ - Description de mon paramètre’}

![image](https://user-images.githubusercontent.com/38039171/47794297-7e275900-dd20-11e8-9f52-4fdf2f90fd8d.png)

### DocumentationForFunction

![image](https://user-images.githubusercontent.com/38039171/47794441-c0e93100-dd20-11e8-8e47-6bd9d7fe168e.png)

En plus des propriétés héritées de Documentation, DocumentationForFunction n’a qu’une liste de DocumentationParameter.

Elle possède un seul constructeur qui construit la liste des paramètres :
 
![image](https://user-images.githubusercontent.com/38039171/47794451-c6467b80-dd20-11e8-86d1-e0a6c6eb2c4e.png)

### DocumentationForProgram

![image](https://user-images.githubusercontent.com/38039171/47794657-29d0a900-dd21-11e8-8cb8-467a8473bc8c.png)

Comme DocumentationForFunction,  DocumentationForProgram n’ajoute qu’une liste de DocumentationParameter aux propriétés héritées de Documentation.

Elle possède un seul constructeur qui construit la liste des paramètres à partir des paramètres spécifiés dans la clause USING de la Procédure Division. À la différence de DocumentationForFunction, le passing type est déterminé à partir du commentaire formalisé et non pas dans la définition du paramètre.
 
![image](https://user-images.githubusercontent.com/38039171/47794673-2fc68a00-dd21-11e8-80ed-181c34a7e5c4.png)
 
### DocumentationGenerator & DocumentationBuilder

![image](https://user-images.githubusercontent.com/38039171/47794696-394ff200-dd21-11e8-8f41-909f87e4fd35.png)
![image](https://user-images.githubusercontent.com/38039171/47794704-3fde6980-dd21-11e8-988e-564fb0826815.png)

Le passage du paramètre CLI OutputFormat à 4 (Documentation) permet d’utiliser le générateur dédié à la documentation DocumentationGenerator au lieu du générateur par défaut. 
Il utilise un visiteur, DocumentationBuilder, qui contient une liste de DTOs. Il parcoure les Nodes en créant le DTO approprié selon le node trouvé (Program – Function – TypeDefinition), si ces derniers sont Publics.
Enfin, DocumentationGenerator récupère cette liste et, pour chacun d’eux, les sérialise et les concatène dans this.Destination. 

La fonction Generate de DocumentationGenerator :
 
![image](https://user-images.githubusercontent.com/38039171/47794711-47057780-dd21-11e8-8dcc-2f4fe3f20be7.png)
 
Le Visiteur DocumentationBuilder :
 
![image](https://user-images.githubusercontent.com/38039171/47794720-4cfb5880-dd21-11e8-8e95-dba451f2e619.png)
 

### Commentaires formalisés

La génération du code est assez simple en théorie puisque nous n’avons qu’à commenter les lignes du commentaire formalisé. En pratique, il n’est pas possible de procéder comme pour les autre Nodes que nous devons commenter, car les commentaires formalisées ne constituent pas de Nodes propres. Ils font parties de codeElements existants et nous ne pouvons que commenter l’intégralité d’un Node.
Les Nodes de Function et de TypeDefinition sont déjà commentées dans le CodeGen. Il ne reste donc que les Nodes de Procedure Division directement enfants des Programs.

Ce Node se génère de deux manières, s’il contient une fonction déclaré en public ou non:
 
Avec une fonction public, C’est la propriété IEnumerable<TypeCobol.Compiler.Text.ITextLine> Lines du Node ProcedureDivision qui génère le code via son getter.
On parcoure les ConsumedTokens du Node : s’ils sont compris dans un commentaire formalisé, on commente la TokensLine (les autres ConsumedTokens de la TokensLine sont ignorés).
 
![image](https://user-images.githubusercontent.com/38039171/47794731-54bafd00-dd21-11e8-8837-f8be80348b18.png)
![image](https://user-images.githubusercontent.com/38039171/47794734-571d5700-dd21-11e8-98ca-af931dbeb45e.png)
![image](https://user-images.githubusercontent.com/38039171/47794742-5a184780-dd21-11e8-93d6-941835544641.png)
 
Sans fonction public. C’est la méthode CommentSpecificParts dans LinearNodeSourceCodeMapper qui commente ces lignes.
 
![image](https://user-images.githubusercontent.com/38039171/47794748-5dabce80-dd21-11e8-8294-315dcefa444e.png)

Cette méthode est appelée pour chaque Node et s’occupe de commenter les commentaires formalisés des ProcedureDivision appartenant au Program et les Commentaires Multilignes pouvant apparaitre n’importe où.
Dans les deux cas, la méthode
```C#
void CommentBetweenTokens(Node node, TokenType startTokenType, TokenType stopTokenType)
```
est appelée. Cette méthode commente toutes les lignes se trouvant entre les deux tokens passés en paramètre en injectant un ‘*’ dans leur buffer.
 
![image](https://user-images.githubusercontent.com/38039171/47794798-79af7000-dd21-11e8-96ee-78ab8ba9437b.png)
 
Un problème se pose cependant, Razor utilise le caractère ‘@’ comme mot clé. Cela pose donc problème pour les champs des commentaires formalisés. Il faut donc les échapper dans RazorEngine :
 
![image](https://user-images.githubusercontent.com/38039171/47794812-7ddb8d80-dd21-11e8-969c-e9debf5b72bd.png)
 
Enfin il ne reste que le cas de la génération des signatures à commenter dans SignaturesGenerator. 
Pour se faire, à la création de chaque ligne à inscrire dans le fichier de sortie, si elle est dans un commentaire formalisé (entre les deux balises), on ajoute la ligne commentée. Sinon, on ajoute la ligne sans y toucher.

![image](https://user-images.githubusercontent.com/38039171/47794829-85029b80-dd21-11e8-8614-a9e4fd18717d.png)
 
### Commentaires Multilignes

Pour les commentaires multilignes, on distingue deux cas de figures :
* Les commentaires multilignes appartenant à un Node (avec le commentaire entre deux lignes d’un même node par exemple)
* Les commentaires multilignes libre donc sans Nodes (comme les commentaires classiques)

Les premiers sont commentés dans LinearNodeSourceCodeMapper avec la méthode CommentSpecificParts. Comme pour les commentaires formalisés, on parcoure chaque Nodes et on commente tout ce qui se trouve entre les balises.
 
![image](https://user-images.githubusercontent.com/38039171/47794836-8a5fe600-dd21-11e8-8ca3-c3cec0a56840.png)
![image](https://user-images.githubusercontent.com/38039171/47794847-8df36d00-dd21-11e8-8970-406e0268f064.png)
 
Le second cas est géré dans DefaultGenerator. Pour chaque ligne n’appartenant à aucun Node, si elles sont entre les balises d’un commentaire multilignes, on les commente.

![image](https://user-images.githubusercontent.com/38039171/47794876-9d72b600-dd21-11e8-935e-0ef074bb721e.png)

### Nouveau mot clé	

Pour ajouter un nouveau mot clé au commentaire formalisé, il faut suivre les étapes suivantes :
* L’ajouter au Tokens et à la TokenFamily.
* Dans TokenUtils, modifier la méthode 
TokenType GetFormalComTokenTypeFromTokenString(string tokenString)
pour que le scanner reconnaisse le nouveau mot clé.
* Inclure le nouveau dans CobolWords.g4 et dans la grammaire dans la liste des formalizedCommentParam.
* Ajouter sa propriété à FormalizedCommentDocumentation, choisir le type selon les valeurs qu’on peut y mettre :
  * string pour une valeur simple et un flag
  * List<string> pour une série de valeurs
  * Dictionary<string, string> pour une série de couples clé – valeurs
* Extraire sa valeur dans le constructeur de FormalizedCommentDocumentation et l’ajouter à la propriété créée précédemment
* Ajouter sa propriété à Documentation, DocumentationForType, DocumentationForFunction ou DocumentationForProgram selon ce à quoi s’applique le mot clé et y assigner la valeur extraite et transformée si besoin du commentaire formalisé.

***

### Nouveau Node commentable

Pour ajouter un nouveau Node pouvant contenir un commentaire formalisé, il faut suivre les étapes suivantes :
* Créer le Node désiré implémentant l’interface IDocumentable.
* Créer un nouveau CodeElement implémentant IFormalizedCommentable ou si c’est un CodeElement existant qui sera utilisé, lui faire implémenter IFormalizedCommentable.
* Modifier ou créer la grammaire de ce CodeElement en y ajoutant formalisedComment à l’emplacement souhaité.
* Dans CodeElementBuilder, modifier la méthode liée à ce Node pour y mettre l’instanciation de FormalizedCommentDocumentation si le contexte Antlr contiens formalizedComment(), donc si Antlr a repéré un commentaire formalisé pour ce Node. Il faut passer au constructeur de FormalizedCommentDocumentation les formalizedCommentLine du contexte Antlr.
* Vérifier si besoin dans CrossCheck que les champs du commentaire formalisé sont correctement remplis.
* Il faut ensuite créer son DTO dans Documentation.cs héritant de la classe Documentation. Si la documentation du Node doit avoir des propriétés autre que celles communes dans documentation, alors il faut les ajouter à ce DTO et les instancier dans son constructeur.
* Enfin, pour que la documentation se fasse correctement, dans DocumentationGenerator, au visiteur DocumentationBuilder, il faut ajouter une méthode Visit prenant en paramètre ce Node, y construire son DTO et l’ajouter à la liste de DTOs du visiteur.

***

En cas de modification des commentaires formalisés il est bon de créer des tests unitaires ou de mettre à jour les tests unitaires dédiés.
* **Test du processus complet :**
  * >CLI/test/ressources/documentation/CLIArguments.txt
  * >CLI/test/ressources/documentation/input/DocGen.tcbl
  * >CLI/test/ressources/documentation/output_expected/DocGen.json
  * >CLI/test/ressources/documentation/output_expected/error.txt

* **Test du CodeGen :**
  * >Codegen/test/resources/input/TypeCobol/FormalizedComments.tcbl
  * >Codegen/test/resources/input/TypeCobol/MultilinesComments.tcbl
  * >Codegen/test/resources/output/TypeCobol/FormalizedComments.tcbl
  * >Codegen/test/resources/output/TypeCobol/MultilinesComments.tcbl

* **Test de sérialisation et CodeElement :**
  * >TypeCobol.Test/Parser/Documentation/DocumentationCombined.rdz.json
  * >TypeCobol.Test/Parser/Documentation/DocumentationCombined.rdz.tcbl
  * >TypeCobol.Test/Parser/Documentation/DocumentationCombined.rdzDoc.txt
  * >TypeCobol.Test/Parser/Documentation/DocumentationFunctions.rdz.json
  * >TypeCobol.Test/Parser/Documentation/DocumentationFunctions.rdz.tcbl
  * >TypeCobol.Test/Parser/Documentation/DocumentationFunctions.rdzDoc.txt
  * >TypeCobol.Test/Parser/Documentation/DocumentationPrograms.rdz.json
  * >TypeCobol.Test/Parser/Documentation/DocumentationPrograms.rdz.tcbl
  * >TypeCobol.Test/Parser/Documentation/DocumentationPrograms.rdzDoc.txt
  * >TypeCobol.Test/Parser/Documentation/DocumentationTypeDefs.rdz.json
  * >TypeCobol.Test/Parser/Documentation/DocumentationTypeDefs.rdz.tcbl
  * >TypeCobol.Test/Parser/Documentation/DocumentationTypeDefs.rdzDoc.txt

**Comment by smedilol** [comment]
Doc referenced in the wiki under `How to extend the grammar and semantic check (full example)`
