### ISSUE TITLE
set myBool1 myBool2 to false cause an exception

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1187]
**Describe the bug**
Setting 2 bool in the same instruction to false is not supported. And it cause an exception during code generation.

**To Reproduce**
TypeCobol code that cause the bug :
```cobol
set myBool1 myBool2 to false
```

**Expected behavior**
- No error or warning should be raised 
- Code generation must NOT throw an exception

The correct TypeCobol code to use is:
```cobol
set myBool1 to false
set myBool2 to false
```

Edit:
Allow to use `set myBool1 myBool2 to false`

**Comment by maxime645** [comment]
The error can't be implemented as is, because of the possibility in cobol to set many type 88 to true. 
See NistTest program NC248A line 555 :
```
055500     SET     TEST-9-1-1-TRUE                                      NC2484.2
055600             TEST-9-2-1-TRUE                                      NC2484.2
055700             TEST-9-3-1-TRUE TO TRUE.                             NC2484.2
```

**Comment by smedilol** [comment]
My mistake, so we can allow to use : 
`set myBool1 myBool2 to false`
