### ISSUE TITLE
DataRenames node are generated as children of previous node

### ISSUE THREAD

**Issue by maxime645** [TypeCobolTeam/TypeCobol#1192]
See following code:

```
       IDENTIFICATION DIVISION.
       PROGRAM-ID. PGM1.
      
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  TEST-GROUP1.
           05  TEST-SGROUP1.
               10  TEST-ELT1           PIC X(04).
               10  TEST-ELT2           PIC X(350).
           05  TEST-SGROUP2.
               10  TEST-ELT3           PIC X(200).
               10  TEST-ELT4           PIC X(1000).
           05  TEST-SGROUP5.
               10  TEST-ELT5           PIC X(100).
        66  TEST-SGROUP2R RENAMES TEST-ELT2
                          THRU    TEST-ELT4.
      
       END PROGRAM PGM1.
```

The RENAMES clause will here be interpreted by the parser as a child of TEST-ELT5, though he shouldn't be.

In this case, the expected behaviour is that TEST-SGROUP2R is a child of the working storage section, containing a reference to TEST-ELT2, TEST-ELT3, TEST-ELT4.

**Comment by smedilol** [comment]
Can you specify what is expected?
So if there are new issues about RENAMES we can compare expected behavior.

**Comment by fm-117** [comment]
Duplicate with #1724, the RENAMES should not be a child fo the WORKING STORAGE section but a child of its nearest level-01 (here TEST-GROUP1).
