### ISSUE TITLE
Handle SYNC LEFT and RIGHT

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1200]
**Describe the bug**
SYNC LEFT and SYNC RIGHT are allowed by our grammar but our CodeElement doesn't have the information.

**To Reproduce**
Cobol code that cause the bug : (if any)
```cobol
01 var1 pic X SYNC LEFT.
01 var2 pic X SYNC RIGHT.

TODO, I need a better test case
```

**Expected behavior**
CodeElementBuilder must use info about SYNC LEFT and RIGHT and put it in DataDescriptionEntry

**Comment by fm-117** [comment]
According to Cobol specs:
> When specified, the LEFT and the RIGHT phrases are syntax checked but have no effect on the execution of the program.
So we only need to capture LEFT or RIGHT keyword with a syntax property right ?
