### ISSUE TITLE
AppVeyor : Keep nuget cache between builds

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1203]
Change AppVeyor config so the NuGet cache is kept between builds.

See AppVeyor doc: 
https://www.appveyor.com/docs/nuget/

> Use build cache for NuGet packages
> To avoid downloading packages from nuget.org on every build you can use build cache.
> 
> If packages folder is in the root of your repo add this to appveyor.yml:
> 
> cache:
>   - packages -> **\packages.config
> That means “preserve packages folder contents between builds unless any of packages.config changes”.

**Comment by NicolasStr** [comment]
PR sent. See #1382.
Looks like we need to test it on a develop branch. Merged by @osmedile now, we are waiting for AppVeyor to build asap.
