### ISSUE TITLE
Diagnostics created during CrossCheck must be attached to Node

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1208]
**Describe the bug**
Bug discovered with #1207
Diagnostics created during CrossCheck step mut be attached to Node instead of CodeElement.
At least, see CrossChecker

**Comment by smedilol** [comment]
After review with Maxime, there is still an addError that use a CodeElement instead of a Node

**Comment by maxime645** [comment]
Nevermind, we reviewed on the wrong branch
