### ISSUE TITLE
Delete skeleton typebool.xml ?

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1232]
Can we remove skeleton typebool.xml ?
I think it's not use except for unit test. But our unit test could use the reference skeleton.

Also typebool.xml is not be the skeleton transpiler

**Comment by mayanje** [comment]
Yes it can be removed, shall I ?

**Comment by smedilol** [comment]
Yes you can!

**Comment by mayanje** [comment]
There is another one that can be removed: Types.xml, can we remove it also ?
