### ISSUE TITLE
Codegen: call to private procedure should only use 8 chars

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1233]
**Is your feature request related to a problem? Please describe.**
FOLLOWING #666 we have used program id of 30 chars for program declaration and call.
```cobol
      *declare procedure StartCheckpoint public
      *    input  PgmName          pic X(08)
      *    output RC               type ReturnCode.
      *_________________________________________________________________
       IDENTIFICATION DIVISION.
       PROGRAM-ID. e01f2d5e-StartCheckpoint.
```
The call to this program is 
```cobol
       call 'e01f2d5e-StartCheckpoint'
```

The problem is that IBM compiler will truncate the program id to 8 chars.
There is a warning for each truncate.

As we keep the original TypeCobol call as a comment just above the generated, we can easily know which procedure is called. 
So we can truncate the call to 8 chars to:
```cobol
       call 'e01f2d5e'
```

**Comment by trudeaun** [comment]
If you would like to use a longer-than-8-char `PROGRAM-ID`, enclose it in single quotes/apostrophes (`'`) and use `PGMNAME(LONGMIXED)`. More information about `PGMNAME` on [Knowledge Center](https://www.ibm.com/support/knowledgecenter/en/SS6SG3_5.1.1/com.ibm.cobol511.ent.doc/PGandLR/ui/up1061.html).

**Comment by smedilol** [comment]
Hi,

Thanks for this information. We'll try that.

**Comment by smedilol** [comment]
Idea from @fm-117 is there a way to ignore some warning with a special clause ?

**Comment by fm-117** [comment]
Compiler option FLAG allows to suppress diagnostics that are above a given severity. It is not usable here as it will remove valuable messages. Besides it is IBM-specific (Microfocus compiler uses WARNING option instead).

**Comment by trudeaun** [comment]
What specific warning message are you trying to suppress? Some messages numbered 0000-3999 and any messages numbered 8000-8999 may be suppressed by using a `MSGEXIT` user exit. A few pages on [Knowledge Center](https://www.ibm.com/support/knowledgecenter/en/SS6SG3_6.2.0/com.ibm.cobol62.ent.doc/PGandLR/tasks/tpext11.html) explain how to do it. While on Knowledge Center, you can navigate by clicking the Table of Contents to expand it, and clicking the push pin to keep it from collapsing. You can also use the previous/next buttons at the top right.

**Comment by fm-117** [comment]
Thanks for the input @trudeaun !
Currently we are trying to suppress messages about truncated program names (i.e. Name"PGMNAMETOOLONG"was processed as"PGMNAMET"). Although MSGEXIT solution would work for this purpose, it would be costly to integrate into our enterprise platform.
We'll make changes on the generation so as to use only 8-chars-long program names.
