### ISSUE TITLE
Bug for incremental mode and multi line changes.

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1234]
When several lines are impacted by incremental scanning and maybe by a multilscanstate, some lines are not entirely rescanned or invalidated for incremental code element reparsing

**Comment by smedilol** [comment]
Can you update the documentation about incremental:
https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolIncrementalPipeline

**Comment by mayanje** [comment]
I had a look to this documentation and I made minor changes, otherwise nothing has changed concerning the meaning of functions and the workflow. No functions has been added or removed.

**Comment by smedilol** [comment]
The goal is to indicate the rules of incremental. Like:
- Reset code Elements
- When to stop the scanning of lines

**Comment by mayanje** [comment]
This is another issue your are asking to describe here the underlying Incremental Algorithms used for both Incremental Scanning and Incremental Code Element parsing.

**Comment by mayanje** [comment]
Ok I have updated [https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolIncrementalPipeline](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolIncrementalPipeline
and referenced [#1277](https://github.com/TypeCobolTeam/TypeCobol/issues/1277)

**Comment by smedilol** [comment]
Ok, thanks.
