### ISSUE TITLE
Identify and Implement Syntactic and Semantic Observers Design Patterns. (A02.T01)

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1263]
***Purpose***

The purpose here is to implement Syntactical node creation listeners, and Parser build action dispatchers, so that Syntax directed strategies can be used, applied and elaborated.

# ProgramClassBuilderNodeListener class #

This class is a NodeListener instance over a IProgramClassBuilder interface imlplementation, witch is able to listen to Systactical nodes creation and parsing action performing.

![class_type_cobol_1_1_compiler_1_1_cup_parser_1_1_node_builder_1_1_program_class_builder_node_listener__inherit__graph](https://user-images.githubusercontent.com/19149269/52789125-5061e800-3063-11e9-8812-c03d51fce58c.png)

# ProgramClassBuilderNodeDispatcher class #

This class is a NodeDispatcher instance over a IProgramClassBuilder interface imlplementation, witch is able to dispatch Syntactical nodes created and parsing actions performed, to registered NodeListener instances and ProgramClassBuilderNodeListener instances.

![class_type_cobol_1_1_compiler_1_1_cup_parser_1_1_node_builder_1_1_program_class_builder_node_dispatcher__inherit__graph](https://user-images.githubusercontent.com/19149269/52789126-51931500-3063-11e9-82ce-9ba7e802b857.png)

# Other classes descriptions #

| **Class** | **Description** |
| :------- | :---------- |
| NodeListener | An interface that describes the contract of any objet able to listen to Syntactical node creation. |
| IProgramClassBuilder | An interface that describes the contract of any objet able to handle parsing actions for program class builing. |
| NodeDispatcher | It is the base class of any object which can dispatch node creation actions to registered NodeListener instances. |

**Comment by smedilol** [comment]
Commit for this issue has been included in branch v1.4.1.
So I change the milestone to v1.4.1. This is a minor change so there is no problem.
