### ISSUE TITLE
Elaborate the semantic domain. (A02.T02)

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1264]
# Purpose #

Purpose here is to elaborate a complete Global Symbol Table of a program with all related dependencies.
The strategy is a syntax directed strategy, that is to say: using what have been done in #1263, parsing building nodes actions are used to perform Symbol Table creation actions. See #1262 for a Global Symbol Table overview.

The following class diagram shows the _ProgramSymbolTableBuilder_ and how it implements _NodeListener_ and _IProgramClassBuilder_ interfaces thru the abstract base class _SymbolTableBuilder_.

![class_type_cobol_1_1_compiler_1_1_domain_1_1_program_symbol_table_builder__inherit__graph](https://user-images.githubusercontent.com/19149269/54217398-d7cc3b00-44eb-11e9-8f0c-5cdddc62ab5e.png)

**Comment by rooksdo** [comment]
Fixed by #1824.
