### ISSUE TITLE
List all TypeCobol control instructions (A04.T01)

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1266]
Instructions causing a change in the control flow graph can be grouped into categories.
**Altered GOTO is not supported by TypeCobol parser, thus the ALTER statement is not handled.**

| **Category** | **Description** |
| :------- | :---------- |
| Decision | IF <br> EVALUATE |
| Procedure-branching | ALTER (**_Not handled_**)<br> EXIT <br> GO TO <br> NEXT SENTENCE <br> PERFORM |
| Ending | STOP RUN <br> EXIT PROGRAM <br> EXIT METHOD <br> GOBACK |

Conditional statements imply a value evaluated to true of a condition to be determined and that the next action of the program is dependent on the true value. These instructions can be categorized

| **Category** | **Description** |
| :------- | :---------- |
| Arithmetic | ADD ... ON SIZE ERROR <br> ADD ... NOT ON SIZE ERROR <br> COMPUTE ... ON SIZE ERROR <br> COMPUTE ... NOT ON SIZE ERROR <br> DIVIDE ... ON SIZE ERROR <br> DIVIDE ... NOT ON SIZE ERROR <br> MULTIPLY ... ON SIZE ERROR <br> MULTIPLY ... NOT ON SIZE ERROR <br> SUBTRACT ... ON SIZE ERROR <br> SUBTRACT ... NOT ON SIZE ERROR |
| Data movement | STRING ... ON OVERFLOW <br> STRING ... NOT ON OVERFLOW <br> UNSTRING ... ON OVERFLOW <br> UNSTRING ... NOT ON OVERFLOW <br> XML GENERATE ... ON EXCEPTION <br> XML GENERATE ... NOT ON EXCEPTION <br> XML PARSE ... ON EXCEPTION <br> XML PARSE ... NOT ON EXCEPTION |
| Input-output | DELETE ... INVALID KEY <br> DELETE ... NOT INVALID KEY <br> READ ... AT END <br> READ ... NOT AT END <br> READ ... INVALID KEY <br> READ ... NOT INVALID KEY <br> REWRITE ... INVALID KEY <br> REWRITE ... NOT INVALID KEY <br> START ... INVALID KEY <br> START ... NOT INVALID KEY <br> WRITE ... AT END-OF-PAGE <br> WRITE ... NOT AT END-OF-PAGE <br> WRITE ... INVALID KEY <br> WRITE ... NOT INVALID KEY |
| Ordering |  RETURN ... AT END <br> RETURN ... NOT AT END |
| Program or method linkage | CALL ... ON OVERFLOW <br> CALL ... ON EXCEPTION <br> CALL ... NOT ON EXCEPTION <br> INVOKE ... ON EXCEPTION <br> INVOKE ... NOT ON EXCEPTION |

**Comment by rooksdo** [comment]
Fixed by #1824.
