### ISSUE TITLE
Generate the .dot file of a CFG graph. (A05.T01)

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1268]
To visualize a Control Flow Graph we can generate it using the Graphviz dot format.
https://www.graphviz.org/doc/info/lang.html
https://www.graphviz.org/

One can visualize a dot file using a online viewer like:
http://www.webgraphviz.com/
https://dreampuf.github.io/GraphvizOnline/

The class diagram below represents two classes used for generating a CFG using the GraphViz dot format.
![CFGDotFileCD](https://user-images.githubusercontent.com/19149269/60276912-d557ea80-98fc-11e9-869c-3d76b29ae213.png)

| **Class** | **Description** |
| :------- | :---------- |
| CfgDotFileGenerator | This class represents the base class for generating a CFG graph using the dot format. |
| CfgDotFileForNodeGenerator | This class represents the sepcialization of the class CfgDotFileGenerator for generating a CFG dot graph based on TypeCobol Node instructions. |

**Comment by rooksdo** [comment]
Fixed by #1824.
