### ISSUE TITLE
Test CFG dot graphs and visualization. (A05.T02)

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1269]
We have some tests on CFG file generation using the dot format of GrAphViz.
All input source files are located in the subdirectory _TypeCobol\TypeCobol.Analysis.Test\BasicCfgInstrs_
All corresponding generated dot files are in the subdirectory _TypeCobol.Analysis.Test\DotOutput_

The test project is: TypeCobol.Analysis.Test
You can use the online tool: http://www.webgraphviz.com/
to visualize resulting dot files.

**Comment by rooksdo** [comment]
Fixed by #1824.
