### ISSUE TITLE
Increase the CFG graph with data structures and fields for DFA. (A06.T01).

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1270]
Data Flow Algorithms uses the BitSet data structure to represent a set of variables.
Then on each basic block we can gather the following informations:

![DFADataStructure](https://user-images.githubusercontent.com/19149269/61214373-0cedd180-a708-11e9-94d2-b62dd214b5bd.png)

| **Data** | **Description** |
| :------- | :---------- |
| Gen | Generated definitions bit set. This is a set of data which is created to identify which data definitions are made within a basic block |
| Kill | Killed definitions bit set: The Kill set represents those variables defined outside the basic block which also have definitions inside the block.|
| In | Definitions live on entry to basic block.|
| Out | Definitions live on basic block exit|

**Comment by rooksdo** [comment]
Fixed by #1824.
