### ISSUE TITLE
Identify TypeCobol instructions targeted by DFA. (A07.T01)

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1271]
Instructions targeted by DFA are typicaly thoses that can contribute to the USE list and the DEF list. Thus instructions that have read storage area or write storage area.

With TypeCobol Parser/Generator, we can easily, traverse a syntax node and visit its code element to accept StorageArea instances used in read or write from.

So no matter to have here the complete list of all TypeCobol instruction that uses Storage Areas.

**Comment by rooksdo** [comment]
Fixed by #1824.
