### ISSUE TITLE
Apply the DFA algorithms. (A07.T02)

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1272]
# Basic DFA Algorithms #

- Mark all definition points of variables in a PROCEDURE DIVISION
- Mark all use points of variables in a PROCEDURE DIVISION
- Build a GEN set for each basic block
- Build a KILL set for each basic block
- Build IN and OUT sets for each basic block
- Build USE-DEF chain for each basic block

**Comment by rooksdo** [comment]
Fixed by #1824.
