### ISSUE TITLE
Support new special register JSON_CODE

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1306]
**CHILD OF #616**
**Is your feature request related to a problem? Please describe.**
For Cobol v6, support new special register.
See page 19 of Cobol v6.1 language reference
01 JSON-CODE PICTURE S9(9) USAGE BINARY VALUE 0.

TODO : finish this issue.

TypeCobol code that you'd like to write.
```cobol

```

**Describe the solution you'd like**

Expected generated code:
```cobol

```

**Comment by fm-117** [comment]
IBM introduced another special register JSON-STATUS with COBOL v6.2. It will be supported as well.
