### ISSUE TITLE
Autocompletion on WHEN keyword

### ISSUE THREAD

**Issue by maxime645** [TypeCobolTeam/TypeCobol#1311]
**Describe the bug**
The autocompletion on a variable in a WHEN returns the list of variable in the program instead of the variables in the structure of the written variable.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZXMNT0.
      *REMARKS. COPY=(
      * ).
       DATA DIVISION.
       working-storage section.
      
       01 type1 TYPEDEF STRICT.
           05 VAR1      PIC X.
           05 VAR2      PIC X(5).
           05 VAR3      PIC S9(5) COMP.
           05 VAR4      PIC 9.
      
       01 t TYPE type1.
      
       PROCEDURE DIVISION.
           
           EVALUATE TRUE
           WHEN t:: = 1
                GOBACK
           WHEN OTHER
                GOBACK
      
           END-EVALUATE.
      
      
       END PROGRAM DVZXMNT0.
```
At line 19, autocomplete variable t to get VAR4. 

**Expected behavior**
The autocompletion should return the structure of variables from type1 (VAR1, VAR2, VAR3, VAR4).

**Comment by rooksdo** [comment]
This issue will be dealt with #1593
