### ISSUE TITLE
Make codegen work with Typedef inside COPY

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1323]
With issue #1019 it is now possible to declare a TYPEDEF whose body is inside a COPY.
However TypeCobol does not support TYPEDEF entirely declared inside a Copy.
But Codegen shall works as if it is possible. But a semantic error must be generated.

**Comment by maxime645** [comment]
The entirety of a TypeDef shouldn’t be in a copy. 
The declaration line (01 myType TypeDef) should in any case be in the TypeCobol Source. Only the bodies of weak and strong TypeDefs can be stored in a copy.
Using a TypeDef strict should be forbidden.

**Comment by smedilol** [comment]
TypeCobol is abandonned, this issue is not needed anymore.
