### ISSUE TITLE
Completion should propose children variables when a variable has no name or is a filler

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1332]
**CHILD OF #907**
Completion should propose children variables when a variable has no name or is a filler.

Example:
```cobol
       01 Person typedef strict.
         03 .
           05 LastName  pic X(30).
           05 FirstName pic X(30).
       03 filler.
         05 BirthDate type Date.

      01 Person1 type Person.
```

If you type :
```cobol
       move Person1:: 
```
The completion should propose:
- LastName
- FirstName
- BirthDate 

If you type:
```cobol
       move  
```
The completion will only propose `Person1`

**Comment by rooksdo** [comment]
@smedilol 
seems to be working fine on lastest release v1.4.2
