### ISSUE TITLE
Using variable in dependency file

### ISSUE THREAD

**Issue by maxime645** [TypeCobolTeam/TypeCobol#1335]
**Describe the bug**
A variable A that expanses another variable B in a dependency file. 
If the variable B is private or absent from the file, generation will succeed, but with the type declaration sentence from TypeCobol source (e.g. 01 … TYPE …), without further notice.
Leaving TypeCobol code in generated COBOL source without an error should never happen.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZBCO0.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1      PIC 9.
       01 NSpan     TYPE DVZTEST2::NamedSpan.
       PROCEDURE DIVISION.
           GOBACK.
       END PROGRAM DVZZBCO0.
```
In a dependency file:
```cobol
      *TypeCobol_Version:v1.2.5.20
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZTEST2.
       DATA DIVISION.
       WORKING-STORAGE SECTION.       
       01 NamedSpan typedef strict public.
           05 name      pic X(10).
           05 group1.
               10 span      type Span.
        
       PROCEDURE DIVISION.
            GOBACK.
       end program DVZTEST2.
```

**Expected behavior**
The generation should end with an error saying that it couldn’t generate NSpan properly
*Update*
After consideration, a structure or type should not be able to declare a variable with a lowest visibility than itself.

**Comment by smedilol** [comment]
Won't fix as TypeCobol language feature is no longer supported.
