### ISSUE TITLE
TypeCobol Lsp server add the version to the SeverCapabilities of the InitializeResult

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1342]
TypeCobol RDz client needs to display the current TypeCobol parser/generator version.
We can use the 'experimental' property of the ServerCapabilities as result of the Initialize request to return further information to the client thru the InitializeResult.
As described at: https://microsoft.github.io/language-server-protocol/specification

**Comment by smedilol** [comment]
Duplicate of #662
