### ISSUE TITLE
Typedef strict declarations forbidden in copies

### ISSUE THREAD

**Issue by maxime645** [TypeCobolTeam/TypeCobol#1343]
Child of #1323 

Declare a Typedef strict in a COPY shouldn't be allowed. Only its body can be stored in it.
Typedef weak and strong are allowed in a COPY.

The problem with typedef strict is that we use it with a visibility qualifier (private/public).
When you use the COPY, you bypass the visibility qualifier.

**Comment by fm-117** [comment]
Typedef weak and strong are allowed unless qualified with visibility.
An error should be raised when
- using a typedef strict in copy
- using a typedef weak or strong with visibility qualifier in copy
Plain weak/strong typedef are allowed.
