### ISSUE TITLE
TypeCobol.LanguageServer raise index out of range exceptions

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1350]
I can detect two situations that raise an index out of range exception from the TypeCobol.languageServer. This result of the display of a popup in TypeCobol RDz client.

- Create an empty last line in a document and press backspace to suppress the line an go to the previous line.

- Select a range of lines to the end of document and suppress the selection.

Attached images are the stack traces displayed.
![IndexOutOfRange0](https://user-images.githubusercontent.com/19149269/55938221-31cf3600-5c3b-11e9-9b41-8d129926ed7c.png)
![IndexOutOfRange1](https://user-images.githubusercontent.com/19149269/55938226-3693ea00-5c3b-11e9-8426-d10d7448393a.png)

**Comment by mayanje** [comment]
Sometime with Ctrl+Shift+End, it can happend.

**Comment by mayanje** [comment]
An easy way to reproduce is like say maxime645 always after a save.
Ctrl+Shift+End
Suppr
Ctrl+S   -- SAVE
Ctrl+Z   -- UNDO

Crash index out of range

**Comment by maxime645** [comment]
Another occurence of this bug:
On the first line of a source, place the cursor on the first column, then do 2 line breaks -> same error
