### ISSUE TITLE
CLI can ignore parameters `s` / `skeletons`.

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1355]
**Is your feature request related to a problem? Please describe.**
CLI can ignore parameter `s` / `skeletons`.
It's annoying to remove/add this parameter when you switch to the production version to develop branch.
It will also be annoying for our users during the qualification.

Moreover code generation works well without the skeleton parameter.

So CLI can ignore this parameter.

**Comment by maxime645** [comment]
After the following test :
Generate in V1.2.6 with skeletons
Generate in develop with skeletons
Generate in develop without skeletons
The solution is already doing fine if we are trying to generate with the option -s in the latest version of TypeCobol.

Besides, @mayanje handled this in issue #1155

**Comment by maxime645** [comment]
On another hand, CLI tests are still using the option -s. These tests should be updated so they don't use the skeleton file anymore
