### ISSUE TITLE
Create Type from existing COPY inside Declare Procedure

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1365]
As per #1019, this shall also works if the Typedef is declared inside a DECLARE PROCEDURE.
Actually #1019 does not handle this case.

**Comment by smedilol** [comment]
With version > 1.3.0, it will not be possible to declare a typedef private or public inside procedure.
So the bug in this issue is not urgent.

**Comment by smedilol** [comment]
TypeCobol is abandonned, this issue is not needed anymore.
