### ISSUE TITLE
Stacked program using main program 

### ISSUE THREAD

**Issue by maxime645** [TypeCobolTeam/TypeCobol#1369]
**Describe the bug**
Considering a stacked program using any main program Types or Functions.
When the source file is opened when a Language Server is running, a "Program with identifier XXX is defined multiple times" will be displayed.

This bug has no impact on the generation. It only occure when the file is opened.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION division.
       PROGRAM-ID. TCOZBMX1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 var1      PIC X.
       01 typedVar TYPEDEF STRICT PUBLIC PIC X(5).
      
       PROCEDURE DIVISION.
       INIT-LIBRARY.
           CONTINUE.
      
       declare procedure ToTest public
           input v PIC X(5)
           .
      
      
       procedure division.
           GOBACK.
       end-declare.
      
       END PROGRAM TCOZBMX1.
      
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZSTK1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 fakeTypedVar PIC X(5).
       LINKAGE SECTION.
       01 var TYPE TCOZBMX1::typedVar.
      
       PROCEDURE DIVISION.
           CALL TCOZBMX1::ToTest INPUT fakeTypedVar.
           GOBACK.
       END PROGRAM DVZZSTK1.
```
Save this program, close and re-open it. An error should instantly be displayed.
The incriminated lines are "01 var TYPE TCOZBMX1::typedVar." and "CALL TCOZBMX1::ToTest INPUT fakeTypedVar.". If you comment one, the error is still present.

**Expected behavior**
This error shouldn't appear since the code is not wrong.

**Comment by smedilol** [comment]
It seems commit de636453 has modified TypeCobolServer.cs :
If I had back:
```
|| contentChange.rangeLength == -1
```
it works again.

@mayanje can you check ?

**Comment by mayanje** [comment]
So this is a bug inside TypeCobol RDz client, test rangeLength == -1 is true when a whole document content has changed, but TypeCobol used to set this value in other situation with an empty range. So the fix in TypeCobol RDz was to set range == null if the change is for the entire document, and to never explicitly set rangeLength to -1.

See: https://microsoft.github.io/language-server-protocol/specification#textDocument_didChange

**Comment by smedilol** [comment]
Ok, it works fine with the client update.
