### ISSUE TITLE
TypeCobol Diagnostic objects must have a reference to the targe file.

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1372]
TypeCobol.LanguageServer uses TypeCobol.Compiler.Diagnostics.Diagnostic object to create LSP Diagnostic objets to be published to the client.

But when TypeCobol.Compiler.Diagnostics.Diagnostic objects refer to positions inside a COPY file,
these positions are not translated to positions inside the source document, the consequence is that the client receives bad locations.

So TypeCobol.Compiler.Diagnostics.Diagnostic objets must have a reference to the target file,
so that TypeCobol.LanguageServer  can determines to which document diagnostics refer to.

**Comment by rooksdo** [comment]
Issue will be fixed with #1592

**Comment by LANOYDO** [comment]
> Issue will be fixed with #1592
Actually it'done by #1592
