### ISSUE TITLE
ProgramClass grammar

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#138]
Make sure the grammar defined in `CobolProgramClass.g4` is appropriate to a COBOL production programs test set.

**Comment by smedilol** [comment]
After testing with our extended production sample, there are still errors with some weird replace.
Otherwise the grammar seems fine.
I propose to close this issue, because it's sufficient for our first beta.
With the milestone we'll aim to check the grammar on all our production files.

**Comment by wiztigers** [comment]
Agreed. This issue was too vague regarding our current state anyway.
