### ISSUE TITLE
Completion on instruction DEPENDING ON

### ISSUE THREAD

**Issue by maxime645** [TypeCobolTeam/TypeCobol#1385]
**Describe the bug**
Completion on instruction DEPENDING ON results in an exception "value cannot be null"

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZTEST1.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-370
      
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 dependOnVarWork PIC 9(2).
      
       01  TEST1-ELT5 PIC X(120)
                 OCCURS 1 TO 10  TIMES
                 DEPENDING ON .
      
      
       PROCEDURE DIVISION.
           CONTINUE.
      
       END PROGRAM DVZTEST1.
```
Place cursor at line 13, after the DEPENDING ON. Press Ctrl + Space to complete. The following window should appear :
![image](https://user-images.githubusercontent.com/42465940/59096520-4f5b0c00-891b-11e9-9309-1bd04f2e321c.png)

**Expected behavior**
The completion should run without exception and display the variables that are compatible.

**Comment by fm-117** [comment]
Merged on master and reported on develop.
