### ISSUE TITLE
Detect if program name doesn't match file name

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1389]
**Is your feature request related to a problem? Please describe.**
In our company, the program name must match the file name.
We should have a custom EI warning to enforce this.

TypeCobol code that you'd like to write.
File name `XXXF0YYY`:
```cobol
       IDENTIFICATION DIVISION .
      *No warning here
       PROGRAM-ID. XXXF0YYY.
      
       END PROGRAM XXXF0YYY.
```

File name `XXXF0YYY`:
```cobol
       IDENTIFICATION DIVISION .
      *Warning here because it doesn't match file name.
       PROGRAM-ID. AAAF0YYY.
      
       END PROGRAM AAAF0YYY.
```

**Comment by smedilol** [comment]
Following #1530, we can now decide that it's always a warning (for EI and non EI rules).

**Comment by LANOYDO** [comment]
> Following #1530, we can now decide that it's always a warning (for EI and non EI rules).
Done
https://github.com/TypeCobolTeam/TypeCobol/tree/fe09fb97ac0c0875e95c644d751fbf2de0ab6f1f

**Comment by smedilol** [comment]
To implement this issue, we must first do an evolution on our RDZ client.
Our client use intermediate file with a generated name.
This generated name never match the program name.

Our RDZ client must first keep the original file name.

**Comment by delevoye** [comment]
Closing the issue as this is not a warning of the IBM compiler and has already been done in a custom quality analyzer.
