### ISSUE TITLE
Implement Global-storage visibility in new SymbolTable

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1391]
**FOLLOWING #805 and #1260**
Implement Global-storage visibility in new SymbolTable.
work in branch 1260_DataflowDomain

See #805 to list rules to implement.

**Comment by fm-117** [comment]
- global-storage scope should be always searched when resolving variables.

**Comment by rooksdo** [comment]
New Symbol Table no longer planned.
