### ISSUE TITLE
Elaborate Section and Paragraph in the new SymbolTable.

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1394]
According to #1262, #1263 and #1264 there are new Symbols: SectionSymbol and ParagraphSymbol respectivilely for  sections and paragraphs, the purpose of this issue is to store in the new SymbolTable these symbols.

**Comment by fm-117** [comment]
Here is my proposal :

1. Change the way `SectionSymbol` and `ParagraphSymbol` are defined. I suggest using a composite pattern with `LabelSymbol` as base class
    a. `LabelSymbol` inherits from `Symbol`, it is an abstraction for both `SectionSymbol` and `ParagraphSymbol`
    b. `ParagraphSymbol` inherits from `LabelSymbol`
    c. `SectionSymbol` inherits from `LabelSymbol` and has a collection of `ParagraphSymbol`
2. in `ProgramSymbol`, replace the `Sections` and `Paragraphs` lists with a list of `LabelSymbol` and adapt code accordingly
3. in `ProgramSymbolTableBuilder`, override `StartParagraph` to register each paragraph symbols
4. in `ProgramSymbolTableBuilder`, override `StartSection` and `EndSection` to handle each section
    a. a `CurrentSection` property will have to be added so as to add the new paragraph in the correct owning section, this property will be updated in both `StartSection` and `EndSection` methods

This approach keeps the relation between a section and its paragraphs but allows at the same time to search for section or paragraph indifferently.

**Comment by rooksdo** [comment]
New Symbol Table is not scheduled anymore.
