### ISSUE TITLE
See AppVeyor can rebuild+tests before a merge

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1413]
**Is your feature request related to a problem? Please describe.**
AppVeyor builds are run when a PR is created.
if the develop branch is updated, the merge can produce unwanted results.

See if AppVeyor can rebuild+tests before a merge

**Comment by maxime645** [comment]
It seems not to be possible to rerun tests automatically before a merge action because it's not AppVeyor that is actually doing the merge, therefore is not in control of the merge process.

**Comment by smedilol** [comment]
I've seen this link.
I've enabled the config. We can test that on current PRs.
