### ISSUE TITLE
Detect SPACE literal in procedure calls

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#1422]
**Describe the bug**
SPACE is incorrectly recognized as a variable when passed as an input in a procedure call.

**To Reproduce**
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZMFT1.
       DATA DIVISION.
       GLOBAL-STORAGE SECTION.
       WORKING-STORAGE SECTION.
      
       PROCEDURE DIVISION.
           DECLARE PROCEDURE DoNothing INPUT t PIC X(1).
           END-DECLARE.
           
      *OK
           CALL DoNothing INPUT BY CONTENT ' '
      *KO
           CALL DoNothing INPUT BY CONTENT SPACE    
           .
      
       END PROGRAM DVZZMFT1.
```

**Expected behavior**
SPACE (and other special literal values) should be recognized correctly and used in the CALL.

Expected generated Cobol code : 
```cobol
           CALL 'dc5faba1DoNothing' USING
                    by CONTENT   SPACE
           end-call
```

**Comment by fm-117** [comment]
Seems to be solved now, works on develop as intended.

**Comment by smedilol** [comment]
Seems solved and won't fix anyway as TypeCobol language feature is no longer supported.
