### ISSUE TITLE
AppVeyor : stop the whole build if the build in EI_Debug fails

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1431]
AppVeyor : stop the whole build if the build in EI_Debug fails.
New build order:
- EI_Debug
- Debug
- EI_Release
- Release

**Comment by maxime645** [comment]
The test is successful. See AppVeyor build https://ci.appveyor.com/project/TypeCobolTeam/typecobol/builds/26636883
