### ISSUE TITLE
Modify char '_' by '-' in the commented rule names in code

### ISSUE THREAD

**Issue by maxime645** [TypeCobolTeam/TypeCobol#1432]
We currently use the char '_' as separator in our rule names. If we want to document them, it with the markdown symbol '_' which bolds the text.
To remove the ambiguity, we replace all char '_' by char '-'.

This issue is directly related to issue https://github.com/TypeCobolTeam/TypeCobol-WebSite/issues/54. All commit that modify a rule name due to the creation of a page on the website shall be registered here.

**Comment by smedilol** [comment]
No longer needed as TypeCobol is abandonned.
