### ISSUE TITLE
Call parameter completion

### ISSUE THREAD

**Issue by maxime645** [TypeCobolTeam/TypeCobol#1441]
**Describe the bug**
Any token read after a qualified name as a call parameter will be recognized as a qualified name token, which results in an exception if the completion is triggered.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
      *TypeCobol_Version:0.1(alpha)
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZTEST3.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 STR.
           05 STR-DATA1       PIC X.
           05 STR-DATA2       PIC X.
      
       01 ROOT-DATA1          PIC X.
       01 ROOT-DATA2          PIC X.
      
       PROCEDURE DIVISION.
       INIT-LIBRARY.
           CALL ToTest INPUT STR::STR-DATA1
                             S
           .
      
       DECLARE PROCEDURE ToTest PUBLIC
               INPUT     DATA1  PIC X
                         DATA2  PIC X.
       PROCEDURE DIVISION.
       END-DECLARE.
       end program DVZTEST3.
```
Ask the completion result for the second parameter of CALL ToTest.
If the completion is triggered on the second parameter with nothing written, there is no problem.
If the first parameter of CALL ToTest is changed to a normal dataDefinition (e.g. ROOT-DATA1), there is no problem.

**Expected behavior**
The second parameter should be recognized as a parameter token

**Comment by rooksdo** [comment]
This bug is now fixed.
