### ISSUE TITLE
NullReference in codegen with some indexes

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#1445]
**Describe the bug**
A NullReferenceException may be raised when generating from complex TC source involving indexes. The bug has been found in CNAF-based file 'CGMV01-BigTypes-1Procedure.tcbl'.
The exception is raised in `DefaultGenerator.LinearGeneration<A>` method at line 524 because node has no position.

**To Reproduce**
Run codegen on CGMV01-BigTypes-1Procedure.tcbl located in TypeCobol.Test\ThirdParty\CNAF_TypeCobol.

**Expected behavior**
Generation should complete without error.

**Note**
First analysis has shown that the node is added in the ErasesNodes list and that changing the Comment action with `ErasedNodes = erasedNodes.Where(n => !(n is IndexDefinition)).ToList();` eliminates the exception.
A smaller COBOL source has to be written to reproduce the bug more easily first !

**Comment by mayanje** [comment]
I simply used the fix, because I failed to find a smaller test.
