### ISSUE TITLE
New diagnostic : The second paragraph/section of a "PERFORM THRU" statement must be defined after the first paragraph/section

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1448]
**Is your feature request related to a problem? Please describe.**
New diagnostic : The second paragraph/section of a "PERFORM THRU" statement must be defined after the first paragraph/section

TypeCobol code that you'd like to write.
```cobol
        perform A thru B
```
A must be defined before B.
Generate an error if it's not the case.

Technical:
Introduce the concept of GlobalIndex from semantic domain to solve this issue.

**Comment by fm-117** [comment]
In fact, this is already implemented in CFG/DFA, see that line https://github.com/TypeCobolTeam/TypeCobol/blob/8afd04bd1597fae1791abe193b789fab3ee02bde/TypeCobol.Analysis/Cfg/ControlFlowGraphBuilder.cs#L1413.

**Comment by rooksdo** [comment]
This is become a Quality Rule.
