### ISSUE TITLE
New diagnostic : "STOP RUN" or "GOBACK" should be the last statement o

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1449]
**Is your feature request related to a problem? Please describe.**
New diagnostic : "STOP RUN" or "GOBACK" should be the last statement o

If a `stop run` or `goback` statement is encountered, then it must be the last statement of the paragraph/section.
Generate an error if it's not the case.

Cobol example:
```cobol
        INIT.
       *Ok
            goback
            .
        INIT2.
       *Ko
            goback
            display "Hello"
            .
```

**Comment by smedilol** [comment]
See comment on #1493

**Comment by fm-117** [comment]
This overlaps with unreachable code detection (see #2016 and #2023). When an instruction follows a `STOP RUN` or a `GOBACK`, a warning is created to signal that it won't be reached.
Moreover, we also have a specific check in our private code-quality analyzer.
