### ISSUE TITLE
Cobol 6.2 : Support when set to false / set to false (without DFA)

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1459]
# Support set to false
## Cobol
Support `when set to false` on level 88 variable and `set niv88 to false` statement.
See IBM Enterprise Cobol 6.2 for zOS language reference for specifications.

Correct Cobol example:
SetToFalseOk.rdz.cbl
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. SetToFalseOk.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-370
      *                WITH DEBUGGING MODE
                      .
       SPECIAL-NAMES.
           DECIMAL-POINT IS COMMA
           .
       DATA DIVISION.
       WORKING-STORAGE SECTION.

       01 Var1 pic X.
           88 Val1 value 'A' false 'B'.
           88 Val2 value 'B' false 'A'.
           88 Val3 value 'B' 'C' false IS 'A'.
           88 Val4 value 'C' when set to false is 'A'.
           88 Val5 value 'D' set false 'A'.
           88 Val6 value 'E' to false 'A'.
           88 Val7 value 'F' when false 'A'.
           88 Val8 value 'G' when to false 'A'.


       procedure division.
           set Val1 to true
           perform displayVar1AndVals

           set val2 to true
           perform displayVar1AndVals


           set Val1 to false
           perform displayVar1AndVals

           set Val2 to false
           perform displayVar1AndVals

           goback.
       displayVar1AndVals.
           evaluate true
              when Val1
                display "Val1 true, Var1=" Var1
              when Val2
                display "Val2 true, Var1=" Var1
           end-evaluate

           if(not Val1)
                display "Not Val1"
           else if (not Val2)
                display "Not Val2"
           end-if
           .
       END PROGRAM SetToFalseOk.
```

SetToFalseKO.rdz.cbl
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. SetToFalseKO.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-370
      *                WITH DEBUGGING MODE
                      .
       SPECIAL-NAMES.
           DECIMAL-POINT IS COMMA
           .
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      
       01 VarA pic X.
           88 ValA-1 value 'A'.
           88 ValA-2 value 'B' false 'A'.
      *Ko No value
      *IBM compiler: "FALSE"was invalid in a level-88 item.
      *The level-88 item was discarded.
           88 ValA-3 false 'A'.
      *Same literal for value and false
      *No error from IBM compiler. Handle this with a quality tool.
           88 ValA-4 value 'A' false 'A'.
      
      *Some invalid syntax
        01 VarB pic X.
             88 ValB-3 value 'A' false.
             88 ValB-3 value 'A' is 'B'.
             88 ValB-3 value 'A' when set.
      
       procedure division.
      *Ko: no false clause defined for Val1
      *IBM compiler: A condition-name was specified in a"SET TO
      *FALSE" statement, but no"WHEN FALSE" value was defined for"VAR1".
      *The" SET"statement was discarded.
           set ValA-1 to false
      
      *As a level 88 must always have a value clause we don't
      *need to reproduce this error.
      *IBM compiler: An error was found in the definition of
      *condition-name "VALA-3".
      *The reference to this condition-name was discarded.
           set ValA-3 to true
      
           set ValA-4 to true
           set ValA-4 to false

      
           goback
           .
       END PROGRAM SetToFalseKO.
```

## TypeCobol
To simplify the codegen we must forbid a set to false that mix variable of type `bool` and level 88 with `false` clause.
Codegen can use `set to false` syntax. This will be done in #2534.
Otherwise except no change in codegen.

# Technical
## Cobol
- [ ] Check hardcoded test with level 88, DataCondition(Entry).
- [ ] move grammar of `setStatementForConditions` from `TypeCobolCodeElements.g4` to `CobolCodeElements.g4`
- [ ] Grammar for level 88 declaration
- [ ] Check where to store the false value in CodeElement
  - adding a `public Value FalseConditionValue { get; set; }` property in `DataConditionEntry`
- [ ] Remove limitation of set to false for Cobol in `TypeCobol.Compiler.Diagnostics.UnsupportedLanguageLevelFeaturesChecker.Check(SetStatementForConditions statement, CodeElementsParser.SetStatementForConditionsContext context)`
- [ ] There should be no change in `conditionalExpression` grammar
- [ ] When `set to false` is used, check that data has `false` clause
  - in CrossChecker on `Visit(SetStatement)`, add a part for checks related to `SetStatementForConditions` code element
- [ ] Bonus : replace hard coded test on Node with level 88 with test on `CodeElementType.DataConditionEntry`

## TypeCobol
- [ ] In `TypeCobolChecker` create a new check to forbid a `set to false` that mix variable of type `bool` and level 88 with `false` clause.
- [ ] Codegen : apply transformation of `set to false` only if receivers are of `type bool`. This can be bone by:
    - Set a flag in `TypeCobolChecker` when the previous check on `set to false` instruction is done
    - Adapt/create an `Attributes` (see Attributes class) to know if `receivers` are of type `Bool`. Only check the first receiver as all receiver must be of type Bool if the first is of type Bool.
    In `skeleton.xml` we could for example, write:
    `<condition node="TypeCobol.Compiler.Nodes.Set" isSetToFalse="yes" />`
    instead of:
    `<condition node="TypeCobol.Compiler.Nodes.Set" sender.type="BOOL" sender="FALSE"/>`

## DFA
NO DFA. It will be done in #2511.

## Quality rules
Note that we do not check compatibility between literals used in `VALUE` clause and the type of the parent definition. If we add this check, we'll have to check type compatibility for `FalseConditionValue` too.

# How to test automatically
Standard program test with Mix comparator.

**Comment by fm-117** [comment]
Syntax `SET lvl88 TO FALSE` is currently supported by the parser (no error) but it then produces an invalid code at generation time

**Original TC code**
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZMFT0.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 var1 PIC X.
          88 item1 VALUE "A".
          88 item2 VALUE "B".
          88 item3 VALUE "C".
       PROCEDURE DIVISION.
           SET item1 TO FALSE.
           GOBACK
           .
       END PROGRAM DVZZMFT0.
```

**Generated Cobol code**
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZMFT0.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 var1 PIC X.
          88 item1 VALUE "A".
          88 item2 VALUE "B".
          88 item3 VALUE "C".
       PROCEDURE DIVISION.
      *    SET item1 TO FALSE.
           SET item1-false TO TRUE
                             .
           GOBACK
           .
       END PROGRAM DVZZMFT0.
```

Generated data item `item1-false` is not defined.
