### ISSUE TITLE
Implement new visibility rules in SemanticDomain

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#1472]
Following #1081, #1260 and #1391, we must implement all new visibility rules in SemanticDomain. Some are already in place but it needs to be completed.
New rules recap :
- Local : visible only for declaring program. Applies to variable/type/procedure
- Global : visible for declaring program and nested. Applies to variables and types
- Private : visible for declaring program, nested and procedures. Applies to types and procedures but also for variables if they are in GlobalStorage
- Public : same as private + visible from outside. Applies to types and procedures only.

- [ ] Apply rules during ResolveType mechanism
- [ ] Update masks (TypeVisibilityMask / VariableVisibilityMask)
- [ ] Handle Local flag
- [ ] Implement full Resolve Function mechanism

**Comment by smedilol** [comment]
This part of new SemanticDomain is cancelled.
