### ISSUE TITLE
Completion duplicated items

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1475]
Some completion items can be duplicated, as shown in the screenshot below:

![DuplicateCompletionItems](https://user-images.githubusercontent.com/19149269/65256983-c13d1700-db00-11e9-80ba-f4b9ba5ece22.png)

See also https://github.com/TypeCobolTeam/TypeCobol/issues/775

**Comment by smedilol** [comment]
Link with #1577
