### ISSUE TITLE
Completion between :: and :: raises an exception

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1484]
When the completion is invoked between two sequences of :: and ::, that is to say the cursor locate like that :: | ::
This raises an exception
![CobonColonColonColonompletion](https://user-images.githubusercontent.com/19149269/65701663-fce85b80-e081-11e9-894b-55776e07dc25.png)

**Comment by fm-117** [comment]
May be related to #1428.
