### ISSUE TITLE
Add an option to specify the path of the log file TypeCobol.CLI.log

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1513]
TypeCobol Parser/Generator creates log file called TypeCobol.CLI.log.
This file is created in the working directory from which the TypeCobol Parser/Generator is called.
The purpose of this issue is to add an option that allows to specify the path of this output log file.

**Comment by rooksdo** [comment]
[Issue 1513.docx](https://github.com/TypeCobolTeam/TypeCobol/files/3915761/Issue.1513.docx)
