### ISSUE TITLE
COPY in TYPEDEF can lead to unwanted level reordering

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#1519]
**Describe the bug**
Following #1434 some problems may appear when using COPY in TYPEDEF because of level renumbering (and also in general because items in COPY have fixed levels but may be used at any level depending on the typed variable using the type).

**To Reproduce**
Consider these 3 files.

CopyExample.cpy
```cobol
05 item2 PIC X.
05 item3 PIC X.
```

Dependency.tcbl
```cobol
01 CustomType TYPEDEF STRICT PUBLIC.
   05 item1 PIC X.
   COPY CopyExample.
   05 item4 PIC X.
```

Dependency.tcbl
```cobol
01 var TYPE CustomType.
```

Originally item1, item2, item3 and item4 are at the same level (05). But after code generation item1 and item4 will be renumbered as level 02 and thus creating a different data structure.

First CustomType is expanded by TypeCobol compiler this way :
```cobol
01 var.
   02 item1 PIC X.
   COPY CopyExample.
   02 item4 PIC X.
```

When the COPY is expanded during COBOL compilation :
```cobol
01 var.
   02 item1 PIC X.
      05 item2 PIC X.
      05 item3 PIC X.
   02 item4 PIC X.
```

Thoses cases are difficult to predict and can't be all solved because TypeCobol does not expand nor renumber copies.
Usage of COPY inside TYPEDEF and usage of those resulting types should be restricted. To be discussed in this issue.

**Comment by fm-117** [comment]
PR #1478 already contains example of those kind of renumbering conflicts.

**Comment by smedilol** [comment]
Won't fix as TypeCobol language is no longer supported.
