### ISSUE TITLE
Completion : move typedVar to xxx

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1541]
## Describe the bug
Completion : 
When the sending variable is typed, the completion must propose at least alphanumeric variable and compatible variable.

## To Reproduce
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X.
       01 Var2 pic X.
       01 Date1 type Date.
       PROCEDURE DIVISION.
           move Var1  to 
           move Date1 to 
           .
       END PROGRAM MyPGM.
```
Completion after `move Var1 to` propose Var2
Completion after `move Date1 to` is empty. `Var1` and `Var2` must be proposed.

## Expected behavior
Completion after `move Date1 to` must propose `Var1` and `Var2`.

## Rules
Use property PrimitiveDataType of a TypeDefinition to get compatible variable.
This is not totally accurate, but we'll review all the type system in a next version of TypeCobol.

**Comment by fm-117** [comment]
I think we missed a part of the specifications that could help us in determining which types are compatible with another.
In COBOL 6.1 specs, page 166, the language reference defines data "classes" and data "categories". Classes are sets of more precise categories. In the parser `TypeCobol.Compiler.CodeElements.DataType` looks like it is representing a data category and CompatibleDataTypes is more like a data class regrouping similar categories. This data class concept could be fully implement in the parser so as to have a better type representation and a simpler way to compare DataTypes.
