### ISSUE TITLE
Add support of .copy extension for COPY files.

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1554]
**Description:**
For looking for COPY files the parser only uses **_.cpy_** extension, it must also support **_.copy_** extension.

CLI should accept a copyExtension to specify copy extension.
By default use current hard-coded value.

**Technical**
Look at C# API to search for a file with multiple possible extension.
Or search the file without extension checking. Then when file(s) are read, check if extension is ok.

**Comment by rooksdo** [comment]
Closed with  #1609.
