### ISSUE TITLE
Document not recognized by TypeCobol.LanguageServer 

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1565]
**Describe the bug**
Close RDZ.
Open RDZ.
The user gets the following message:
![image](https://user-images.githubusercontent.com/13764482/69874099-6ec76600-12ba-11ea-86ce-4daa4ccfddac.png)

Restart TypeCobol.LanguageServer doesn't help.
RDZ must be restarted.

Idea: maybe 2 instances of TypeCobol.LanguageServer are running.

**Comment by rooksdo** [comment]
Ok for merge as soon as possible. Tests runs are all ok.
Specific tests concerning concurrency will need to be run.

**Comment by fm-117** [comment]
May not be fully resolved but improving the concurrency checks in workspace should help (see PR #1569).
