### ISSUE TITLE
Random bug with TypeCobol.LanguageServer during generation

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1566]
**Describe the bug**
Random bug during code generation.
![image](https://user-images.githubusercontent.com/13764482/69874345-06c54f80-12bb-11ea-9127-0e16636a0f02.png)

**To Reproduce**
No information from the user. It's random.

**Comment by rooksdo** [comment]
Ok for merge as soon as possible. Tests runs are all ok.
Specific tests concerning concurrency will need to be run.

**Comment by fm-117** [comment]
May not be fully resolved but improving the concurrency checks in workspace should help (see PR #1569).
