### ISSUE TITLE
Display Hash information in TypeCobol editor

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1570]
Hash information about a TypeCobol procedure needs to be accessible from the editor.

Display information in a display window below item for every mouseHover(?) action over a procedure signature. Copy action from the display window should be activated.

Retrieve the information from the hash by calling the appropriate service.

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
