### ISSUE TITLE
Line mapping error for a list element

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1574]
**Describe the bug**
There is a line mapping problem.

From the user perspective:
Error from the IBM compiler on a generated line is mapped to the wrong TypeCobol source line.

This occurs on a list item without specifying any index.

**To Reproduce**
TODO : example of code.

**Expected behavior**
Error should appear at the exact source line generating the error in TypeCobol editor.

**Comment by smedilol** [comment]
Won't fix as TypeCobol language is not supported anymore.
