### ISSUE TITLE
Error messages triggered from click on Remote Error List item

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1575]
**Describe the bug**
3 error messages appear successively after clicking on an error in the remote error list.

![image](https://user-images.githubusercontent.com/57907033/70259024-a4be8b80-178d-11ea-8bc9-191fdd97ddb6.png)
![image](https://user-images.githubusercontent.com/57907033/70259029-a6884f00-178d-11ea-963c-f0deed485e23.png)
![image](https://user-images.githubusercontent.com/57907033/70259033-a8eaa900-178d-11ea-99af-5d8d288cb6ae.png)

**To Reproduce**
3 error messages appear successively after clicking on an error in the remote error list.

**Expected behavior**
No error message should appear after clicking  on a remote error list.

**Comment by rooksdo** [comment]
![image](https://user-images.githubusercontent.com/57907033/70259024-a4be8b80-178d-11ea-8bc9-191fdd97ddb6.png)
![image](https://user-images.githubusercontent.com/57907033/70259029-a6884f00-178d-11ea-963c-f0deed485e23.png)
![image](https://user-images.githubusercontent.com/57907033/70259033-a8eaa900-178d-11ea-99af-5d8d288cb6ae.png)

**Comment by smedilol** [comment]
This error is related to our private plugin. I close it.

**Comment by rooksdo** [comment]
Ok, issue  #61878 created on TFS.
