### ISSUE TITLE
Completion (CTLR+SPACE) shows same suggestion twice

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1577]
### Describe the bug
Completion (CTLR+SPACE) shows same suggestion twice. See also #775.

![DuplicateCompletionItems](https://user-images.githubusercontent.com/19149269/65256983-c13d1700-db00-11e9-80ba-f4b9ba5ece22.png)

### To Reproduce
Doesn't always happen.

Known case : CTRL+SPACE outside editable range.

TODO => Maybe find a case scenario that triggers this behavior systematically.

### Expected behavior
Any given suggestion appears but once in dialog box.

### Workaround
Send email with server dump if duplicate values are returned

**Comment by smedilol** [comment]
It didn't happen since a long time.
