### ISSUE TITLE
CTRL+Z triggered unexpected error message

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1578]
**Describe the bug**
CTRL+Z triggered unexpected error message

![image](https://user-images.githubusercontent.com/57907033/70260127-eea87100-178f-11ea-9475-884677e06ea0.png)

**To Reproduce**
Happened only once (see call trace for origin)

**Expected behavior**
Default CTRL+Z behavior (a.k.a undo last action)

**Comment by fm-117** [comment]
Strange, according to the stacktrace it shoud have been fixed in commit d0a52e3415c086c5cb3c48ee02b417bb2d373ec9. We need a procedure to reproduce.

**Comment by rooksdo** [comment]
Commit d0a52e3415c086c5cb3c48ee02b417bb2d373ec9 was made one day after this issue was created, so this error probably occured before. There's no known scenario to reproduce the bug, I'm closing this issue as I consider the bug to be resolved.
