### ISSUE TITLE
Keyword names allowed for naming variables

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1580]
**Description**
Allow for keyword names in variable names.

TypeCobol code that you'd like to write.
```cobol
  01 Date TYPE Date.
```

**Possible solution**
Implement same rule as in C#, using @ character for enabling

Expected generated code:
```cobol
 01 @Date TYPE Date.
```

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
