### ISSUE TITLE
CLI doesn't allow for generation with multiple input files

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1584]
**CLI doesn't allow for generation with multiple input files**

CLI supports standard generation followed by source file generation with extended copys but not on multiple input files since CLI accepts only one folder path for extended copys output file.

**Solution**
Case scenarios need to be analysed for this feature. In the meantime throw an exception.

Is this feature needed? How to support mutliple files?
 - Append both results in one single file
 - Make two calls combining -o & -i format options
 - Accept multiple files as input?

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
