### ISSUE TITLE
#1539 sub-issue for Equals/GetHashCode implementation

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1586]
This issue is a subset of issue #1539 to be integrated in v1.4. Targeted classes to be modified for implemention of Equals/GetHashCode are shown below (with specified method to redefine):

Type | Equals | GetHashCode
-- | -- | --
TypeCobol.Compiler.CodeElements.CodeElement | O | X
TypeCobol.Compiler.CodeElements.Expressions.AbstractQualifiedName | O | O
TypeCobol.Compiler.CodeElements.SymbolInformation | O | O
TypeCobol.Compiler.Diagnostics.Diagnostic | O | X
TypeCobol.Compiler.Scanner.MultilineScanState | O | O
TypeCobol.Compiler.Scanner.Token | O | O
TypeCobol.LanguageServer.VsCodeProtocol.SignatureInformation | O | X
TypeCobol.Compiler.CodeElements.SymbolReference | X | X
TypeCobol.Compiler.Preprocessor.ImportedToken | X | X

And the following table adds information about further checks to consider for implemention

Type | Action
-- | --
TypeCobol.Compiler.CodeElements.CodeElement | Add GetHashCode and Iequatable, check present comparision algorithm
TypeCobol.Compiler.CodeElements.Expressions.AbstractQualifiedName | Seems manageable
TypeCobol.Compiler.CodeElements.SymbolInformation | Add IEquatable ?
TypeCobol.Compiler.Diagnostics.Diagnostic | Add GetHashCode and Iequatable, check present comparision algorithm
TypeCobol.Compiler.Scanner.MultilineScanState | Add IEquatable ?
TypeCobol.Compiler.Scanner.Token | Add IEquatable ?
TypeCobol.LanguageServer.VsCodeProtocol.SignatureInformation | Add GetHashCode and Iequatable, check present comparision algorithm
TypeCobol.Compiler.CodeElements.SymbolReference | Check whether redefining equality is necessary?
TypeCobol.Compiler.Preprocessor.ImportedToken | CopyDirective needs to be checked in order to distinguish between native   and imported token

**Comment by smedilol** [comment]
TypeDefinition was ok in PR #1555, why remove it from this issue ?

**Comment by rooksdo** [comment]
TypeDefinition appears to be in the Node class hierarchy and its Equals/GetHashCode methods may need to be reevaluated once Node's Equals/GetHashCode methods are optimized (for class conformity). OK, a first optimization will be integrated in this issue.
