### ISSUE TITLE
Optimized File loading

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#159]
**Reported by @smedilol in 8bec808888b6cf98a74bf66b4e0a15f64b048cd7**

When loading file, if file name already as an extension try to read it as is and then with project extensions. Otherwise try to read file with project extensions and then without extension.

GrammarTest now use `*.cpy` extension before `*.cbl`
As a result GrammarTest now is about 10% faster on my machine.

**Comment by wiztigers** [comment]
I had to fix one code line in f3d5833a1127c62a085ae64eb1ebb75b0456953a, because ParserTest was broken on my machine.
@smedilol, could you please check that I did not break the intent behind your 8bec808888b6cf98a74bf66b4e0a15f64b048cd7 upgrade ?

**Comment by smedilol** [comment]
Ok for this fix. Sorry I forgot to commit some files.
I'll do a further commit about that.
