### ISSUE TITLE
Hover on procedure name fires error message

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1590]
### Description
Pressing F3 key on procedure name fires an error message, as in the example below:
```cobol
       declare procedure GetPersonById private{cursor here}
               input  PersonId type Date.
       Procedure division.
      
           goback
           .
       end-declare.
```

Stacktrace:
![image](https://user-images.githubusercontent.com/13764482/70780924-f1095d00-1d85-11ea-94ea-519d89da7545.png)

You can also try to use "hover" on an undeclared variable:
```cobol
            move a to xxxxxxxxxxxxx
```

### Solution
Shield against null value (see onHover method in TypeCobolServer.cs)

**Comment by smedilol** [comment]
@LANOYDO I've updated the issue with the stacktrace

**Comment by smedilol** [comment]
@LANOYDO the move statement doesn't seems to reproduce the bug.
But I can reproduce it with a set:
```cobol
            set xxxxxxxxxxxx to true
```
