### ISSUE TITLE
CodeElementsParserStep line index update problem

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#160]
Somewhere between Dec,22 and today, something has divided our `GrammarTest` speed by 4:
**before:**

```
Files tested=498/498, files in error=2, ignored=0
Total number of errors: 6
total time: 05m02s243ms
```

**now:**

```
Files tested=498/498, files in error=1, ignored=0
Total number of errors: 5
total time: 22m12s255ms
```

Gotta investigate.

**[EDIT]** Performance issue is solved by avoiding a time-consuming instruction. This instruction will however be needed for future features. See from [this post](https://github.com/TypeCobolTeam/TypeCobol/issues/160#issuecomment-179762463) on for details.

**Comment by wiztigers** [comment]
The guilty commit seems to be ca976f9114f5be6e56a7f99b65d87b7caf53bced : `GrammarTest` speed takes a hit on Jan,10

**Comment by wiztigers** [comment]
@laurentprudhon, any thoughts?

**Comment by laurentprudhon** [comment]
See pull request #178 : total compilation time reduced by 66% (divided by 3)

**Comment by wiztigers** [comment]
```csharp
int updatedLineIndex = documentLines.IndexOf(codeElementsLine, codeElementsLine.InitialLineIndex);
```
brought by ca976f9114f5be6e56a7f99b65d87b7caf53bced.
kills performance.

**Comment by wiztigers** [comment]
For the first parsing of a given file, the problematic line seems to always returns `-1`: the call to `documentLines.IndexOf` must always run the whole list length, thus being the cause of our performance hit.

This line was originally written to prepare incremental parsing in `ProgramClass` ; however, today this feature dosn't exist.

As of 59839af7a2116257c7077eab6120edac1256f3f4, I've thus edited it to avoir the call to `documentLines.IndexOf` and give our tester a gulp of air until this line is able to serve its purpose.

I don't close this issue so we'll come back to it later.

**Comment by smedilol** [comment]
I propose to close this issue and create a new one when we'll work on incremental parsing in `ProgramClass`
