### ISSUE TITLE
Completion on List element fired error message

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1601]
### Description
Attemp at using completion on a List element hierarchy with the following structure
```cobol
01 ListObjects type ListObject.

01 ListObject typedef strict public.
   05 ListObjectGroupData type ObjectData occurs 200
                                          indexed by ListIdx.
```
using the following instruction
```cobol
Perform varying index from 1 by 1 until
                  ListObjects::ListObjectGroupData::{cursor here} (index) equal space
```
fired this message (happened only once)
![image](https://user-images.githubusercontent.com/57907033/71166122-58298480-2252-11ea-921a-d79a52231197.png)

### Tip
Myabe check for empty collection before calling System.Link.Enumerable.Last() method

**Comment by fm-117** [comment]
Strange, according to the stacktrace it shoud have been fixed in commit d0a52e3415c086c5cb3c48ee02b417bb2d373ec9. We need a procedure to reproduce.
Same remarks as in #1578
