### ISSUE TITLE
Syntax coloring on formatted comment doesn't recognize "<="

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1607]
**Description**
Syntax coloring fails on the following character sequence for ending "<=" :
 ````cob
%<<<=
 some formatted comment
%>>>
````
probably because editor interprets "<=" as a mathematical expression.

**Expected behavior**
Syntax coloring applies to every character comprised within opening "%<<<" and closing "%>>>"

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
