### ISSUE TITLE
Allow for input/ouput information in @Params argument description in formatted comment

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1608]
**Description**
@Params arguments description should allow for specifying input/output.
Maybe something such as:
```cobol
%<<<
*Description de la procedure.
 @Params:
    - input  Date1 description de Date1
    - output Param2 description de Param2
%>>>
declare procedure MyProcedure private
       input  Date1     type Date
       output Param2    pic X.
end-declare.
```

**Expected behavior**
Added information on input/output is compiled for documentation.

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
