### ISSUE TITLE
.xml error file contains only errors of the last file having errors.

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1612]
**Description**
When multiple files are specified in the CLI command line using -i option, the generated .xml error file contains only errors of the last file having errors, errors from other files are not reported.

**Expected behavior**
All errors of all files must be reported in the .xml file

**Comment by rooksdo** [comment]
Fixed by #1581

**Comment by fm-117** [comment]
> Fixed by #1581

Will be fixed after merge of #1603.
