### ISSUE TITLE
Add error for missing dot following PROGRAM-ID

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1620]
**Description**

Generate warning message when program id declaration is missing a dot :
```cob
PROGRAM-ID MYPROGRAM. 
``` 
instead of
```cob
PROGRAM-ID. MYPROGRAM. 
``` 
Warning message should notify programmer that adjacent dot after PROGRAM-ID is not optionnal.

PROGRAM-ID syntax control needs to be refactored in accordance.

**Comment by smedilol** [comment]
It look likes a problem in :
TypeCobol/Tools/APIHelpers/Helpers.cs

Check code under comment:
`//Issue #583, ignore a dependency if the same file will be parsed as an input file just after`
