### ISSUE TITLE
[Performance] Serialization

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#163]
Currently there is too much overhead regarding serialization.
I implemented it in a hurry, and it leaves much to be desired, in particular regarding performance.

Let's optimize this already!

**Comment by wiztigers** [comment]
Currently, there is a way to only track CodeElements that have been updated by the parser according to the text lines that were changed in the editor.
However, these particular CodeElements are currenty sent without context to listeners: we have to notify the editor that this particular CodeElement has changed, but it would be the editor's job to know what text corresponds to this CodeElement.

For example, currently, the Eclipse plugin editor only has a list of CodeElements corresponding to the file currently modified ; it expects the parser to __re-send the whole CodeElements list each time the file is edited__ (and that is currently the main serialization performance problem).
Without a way to directly place *just* the updated CodeElements in a persistent list, it would be a hassle and a waste of resources to appropriately place the CodeElement in the list. Worse, it wouldn't even be possible without the editor maintaining a more complex datastructure, which would allow it to get the *current* line of each CodeElement, despite the line order having changed since their creation ... which is equivalent to say: we have to duplicate the data structure representing CodeElements and their interactions between the parser and the editor.

This seems a bad idea.

Before duplicating data (eww!), this is a good time to think more in depth about the interface between our parser and the outside world. In particular, we can follow the "vscode" lead.

**Comment by wiztigers** [comment]
**BLOCKED BY #181**

**Comment by smedilol** [comment]
As VsCode protocol is now implemented, we can close this issue
