### ISSUE TITLE
Formalized comment are lost during export signature

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1636]
**Describe the bug**
My mistake, I didn't catch a regression :
Formalized comment are generated as standard Cobol comment when you export (see 5f9e162fad400a691a18360eabeb2f72efca1e25 reviewed in PR #1556).

The problem is that hover feature can show formalized comment of type and procedure of dependancies.
With this bug, we lose this feature.

**To Reproduce**
See test outputSignature_1 of CLI.
The output file "ProcedureCall-Public-Signatures.rdz.tcbl" must contains formalized comment.

**Comment by fm-117** [comment]
After discussion :
- formalized comments must be preserved during export (and they should not be converted into standard COBOL comments)
- single and multiline comments should be deleted during export
This issue can be combined with #1624 as both are related to the `SignatureGenerator` class.

**Comment by fm-117** [comment]
PR #1631 merged.
