### ISSUE TITLE
Error message not explicit for copy declaration with 01 level

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1637]
Considering copy YCOPYTS
```cob
01 Y:COPYTS:.
   05 :COPYTS:-DATA.
     10 :COPYTS:-ADR                 Pic X(50).
```

The following copy declaration 
```cob
01 COPYTS.   COPY YCOPYTS REPLACING ==:COPYTS:== BY ==COPYTS==.
```
generates error "Group item cannot be empty" when actually it should say :
"Copy declaration cannot use level 01 because a 01 level already exists in copy".

**Comment by smedilol** [comment]
Technical:
Dev must be done in CrossChecker.
Loot at property IsInsideCopy of CodeElement.
