### ISSUE TITLE
EI rule : Copy suffixing must be limited to COPY without replacing

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1644]
**Describe the bug**
Only for EI rules:
Copy suffixing must be limited to COPY without replacing.
When a COPY is used with a REPLACING, then use the standard Cobol mechanism to load it.

When a COPY is used without replacing, starts with a "Y", and contains 8 chars, then a special mechanism is used to load it. See #725 for details.

The bug here, is that even with a replacing, a COPY can be considered as a special copy (CPY). 

**To Reproduce**
Test with EI rules and AutoRemarks activated.
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPgm.
       data division.
       working-storage section.
         COPY YxxxInp  REPLACING ==:xxxInp:== BY ==xxxInp==.
         COPY YxxxInpA REPLACING ==:xxxInp:== BY ==xxxInpA==.
       END PROGRAM MyPgm.
```
File YxxxInp.cpy
```cobol
       01 :xxxInp:.
           05 :xxxInp:-Foo PIC X.
```

**Expected behavior**
COPY YxxxInpA REPLACING ==:xxxInp:== BY ==xxxInpA==. must produce an error because file YxxxInpA.cpy doesn't exists.
Copy YxxxInpA must be reported as missing copy.

**Technical**
The problem seems to be located in CompilerDirectiveBuilder.
See // Declaration found and copy name starts with Y => apply the legacy REPLACING semantics to the copy directive
Here we should check that the COPY doesn't use a REPLACE option.

Note that this control is already done in ReplaceTokensLinesIterator.
See `if (CopyReplacingDirective != null && CopyReplacingDirective.RemoveFirst01Level && CopyReplacingDirective.ReplaceOperations.Count == 0)`

**Comment by rooksdo** [comment]
Fixed by #1732
