### ISSUE TITLE
Handle invalid Nodes before generating

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#1659]
Following #1440 a new problem arose. Let's consider two files :

- DVZZPGM1.cbl
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZPGM1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 str-message TYPE DVZZPGM2::Type1.
       procedure division.
           DISPLAY str-message::var1
           .
       END PROGRAM DVZZPGM1.
```

- DVZZPGM2.cbl
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZPGM2.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Using voluntarily wrong syntax to create an invalid pgm
       01 Type1 typedef strict public
          05 var1 PIC X(20)
       procedure division.
           goback
           .
       END PROGRAM DVZZPGM2.
```

After fixing #1440, parser will now generate CodeElement and Node for both `Type1` and `var1` symbols therefore no semantic error will be raised when parsing `DVZZPGM1`. But the Type1 and var1 Nodes can't be used for generation because they miss PeriodSeparators in their Tokens.

The goal of this issue is to handle properly invalid Nodes before launching Codegen so as to prevent invalid code generation.

**Comment by fm-117** [comment]
Identificating invalid Nodes and handling are both part of this issue.
In the given example, a Diagnostic is only created on CodeElements, not directly on Node.

**Comment by smedilol** [comment]
Won't fix as TypeCobol language is not supported anymore.
