### ISSUE TITLE
Continuation lines

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#1673]
# Describe the bug
Generally speaking, continuation lines seem not to work well with incremental parsing and completion :
- real-time diagnostics are reported on continuation line but disappear after full reparsing (Ctrl-S)
- completion is broken on a continuation line (either no results or out of context results are returned)

# To Reproduce
From this code:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X(80) value 'a'.
       END PROGRAM MyPGM.
```

Change it first to:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X(80) value 'a
       END PROGRAM MyPGM.
```
A first error appear on the line of `Var1`: `Syntax error : Literal is not correctly delimited.`

Then change the code to:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X(80) value 'a
      -     'aaa'. 
       END PROGRAM MyPGM.
```
A second error appear on the new line:
`Syntax error : extraneous input ''aaa'' expecting {separator, statement starting keyword, keyword}`

Now save the document which trigger a full refresh of the document.
The 2 errors disappear.

# Expected behavior
The 2 errors must disappear as soon as the second line is inserted.

# Others tests
## Test 1
Test 1 is the example above.

## Test 2
From this code:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X(80) value 'a
      -     'aaa'. 
       END PROGRAM MyPGM.
```
Change it to:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X(80) value 'a
      -    'aaa
      -    'bbb'.        
       END PROGRAM MyPGM.
```

## Test 3
From this code
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X(80) value 'a
      -     'aaa'. 
       END PROGRAM MyPGM.
```
Delete characters to get:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X(80) value 'a'.
       END PROGRAM MyPGM.
```
No error expected.

## Test 4
From this code:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X(80) value 'a
      -    'aaa
      -    'bbb'.        
       END PROGRAM MyPGM.
```
Change it to:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Var1 pic X(80) value 'a
      -    'aaa'.      
       END PROGRAM MyPGM.
```

**Technical**
Will be edited by a team member.
Implementation details with the chosen solution.

**How to test automatically**
Use incremental tests.

**Comment by mayanje** [comment]
#2062 is another situation for this issue.
