### ISSUE TITLE
Empty IF ELSE should be allowed in grammar but checked in CrossChecker

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1676]
**Description**

Follow up to #1660 

Empty IF ELSE should be allowed in grammar but checked in CrossChecker.

Completion must still work on stand alone IF (e.g `IF a = b {completion}`).

**Comment by fm-117** [comment]
Pre-analysis shows that modifying the CUP grammar ([see attachment](https://github.com/TypeCobolTeam/TypeCobol/files/4474690/TypeCobolProgram.cup.txt)) would work without too much impact.

TODO
- Add Visit methods for `Then` and `Else` node to emit warning when no statement is present
- Add test case for various IF - ELSE - END-IF constructs
- Update existing tests with new warning messages
- Modify EmptyTypeCobolProgram.cup to keep in-sync
