### ISSUE TITLE
Can't build typecobol with visual studio 2019

### ISSUE THREAD

**Issue by alvaro-vantis-pt** [TypeCobolTeam/TypeCobol#1680]
Build errors while trying to build typecobol from souce codes with Visual Studio 2019 on Windows 10, both with latest patches installed.

1. Connect to TypeCobol on GitHub from Visual Studio
2. Open TypeCobol.sln
3. Restore nuget packages for solution
4. Build Solution and get the following errors:

>```
CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\CodeElementsListener.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\CodeElementsBaseVisitor.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\CodeElementsBaseListener.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\CodeElementsParser.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\CobolCompilerDirectivesBaseVisitor.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\CodeElementsVisitor.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\CobolCompilerDirectivesParser.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\CobolCompilerDirectivesListener.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\CobolCompilerDirectivesBaseListener.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\CobolCompilerDirectivesVisitor.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\TypeCobolCodeElementsListener.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\TypeCobolCodeElementsBaseListener.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\TypeCobolCodeElementsParser.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\TypeCobolCodeElementsBaseVisitor.cs' could not be found.
6>CSC : error CS2001: Source file 'C:\Users\alvaro\Source\Repos\TypeCobolTeam\TypeCobol\\obj\Debug\TypeCobol\TypeCobolCodeElementsVisitor.cs' could not be found.
```

**Comment by fm-117** [comment]
Hi. I think this is not related to VS2019, we use generated .cs files that are not picked up on first build. You have to build a first time then close solution and reopen it and then rebuild a second time.
Once you got the files generated, the next builds should be ok.

**Comment by alvaro-vantis-pt** [comment]
Thanks. Close Visual Studio and rebuild twice solved the problem.
