### ISSUE TITLE
Unexpected compile error for "INDEXED BY on redefined WORKING STORAGE area

### ISSUE THREAD

**Issue by alvaro-vantis-pt** [TypeCobolTeam/TypeCobol#1690]
A table defined in WORKING-STORAGE, that is REDEFINING another WORKING-STORAGE AREA, with "INDEXED BY" generates an error message of type 
"Syntax error : Symbol XXX is not referenced" for each statement on PROCEDURE DIVISION that references this INDEX

There was no DataDefinition/DataDescription for this INDEX.

This code compiles fines on z/OS compiler.

**To Reproduce**

1. Create an entry like this in working-storage section:

`05  W-ACTION                 PIC XX.
    05  W-RESULT                  PIC XX.
    05  W003-REQUESTS.
        10  W003-ACTION01-N               PIC 9.
        10  W003-ACTION02-N               PIC 9.
        10  W003-ACTION25-N               PIC X.
    05  W003-REQUESTS-CHAR          REDEFINES W003-REQUESTS
             OCCURS 3 TIMES INDEXED BY W003-IDX
                                          PIC X.

2. In procedure,:

PERFORM EA000-XX
        VARYING W003-INDX FROM CH-1 BY CH-1
            UNTIL W003-INDX GREATER THAN CH-NUM-REQ

**Expected behavior**
Have the appropriated DataDefinition/DataDescription created for this Index and no error messages relate to this on referenced statements.
```

**Comment by rooksdo** [comment]
Here is a sample to reproduce the bug 

```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOZDR02.
       DATA DIVISION.

       WORKING-STORAGE SECTION.
       01 W-VAR    PIC XXX.
      *KO W003-INDX is not referenced
      *01 W003-REQUESTS REDEFINES W-VAR  => uncomment to reproduce the bug
      *OK W003-INDX is referenced        => and comment line below
       01 W003-REQUESTS
                   OCCURS 3 TIMES INDEXED BY W003-INDX PIC X.

       PROCEDURE DIVISION.

           PERFORM VARYING W003-INDX FROM 1 BY 1
                     UNTIL W003-INDX GREATER THAN 10
                CONTINUE
           END-PERFORM
           .

       END PROGRAM TCOZDR02.
```

**Comment by smedilol** [comment]
Technical:
See ProgramClassBuilder, there should be a method `AddIndex` or `AddVariable` which takes an index as parameter.

**Comment by smedilol** [comment]
@alvaro-vantis-pt Hi, this issue is fixed.
You can try our last release v1.4.1_1
https://github.com/TypeCobolTeam/TypeCobol/releases/tag/V1.4.1_1
The code source is also up to date in master branch.

Let us know if it doesn't works.

**Comment by alvaro-vantis-pt** [comment]
Hi. Great Job. It's working. Thank you.
