### ISSUE TITLE
Cobol 6.2 : Add support for the COBOL V6.2 Conditional Compilation language feature

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1693]
**Description**
Add support for the COBOL 2002 Conditional Compilation language feature: 

- New DEFINE compiler option: https://www.ibm.com/support/knowledgecenter/SS6SG3_6.2.0/com.ibm.cobol62.ent.doc/PGandLR/ui/up4011.html

- New compiler directives:

    >>DEFINE: https://www.ibm.com/support/knowledgecenter/SS6SG3_6.2.0/com.ibm.cobol62.ent.doc/PGandLR/ref/rldirdef.html
    >>EVALUATE: https://www.ibm.com/support/knowledgecenter/SS6SG3_6.2.0/com.ibm.cobol62.ent.doc/PGandLR/ref/rldireva.html
    >>IF: https://www.ibm.com/support/knowledgecenter/SS6SG3_6.2.0/com.ibm.cobol62.ent.doc/PGandLR/ref/rldirif.html

**Comment by fm-117** [comment]
Status for all keywords used by Cobol 6.3 compiler directives.

| Keyword         | Status                                    |
|-----------------|-------------------------------------------|
| >>CALLINTERFACE | New token                                 |
| >>CALLINT       | New token                                 |
| DLL             | New token                                 |
| DYNAMIC         | Already exists                            |
| STATIC          | New token                                 |
| >>DATA          | New token (it already exists witout '>>') |
| >>INLINE        | New token                                 |
| ON              | Already exists                            |
| OFF             | Already exists                            |
| >>DEFINE        | New token                                 |
| AS              | New token                                 |
| PARAMETER       | New token                                 |
| OVERRIDE        | Already exists                            |
| >>EVALUATE      | New token (it already exists witout '>>') |
| >>WHEN          | New token (it already exists witout '>>') |
| THROUGH         | Already exists                            |
| THRU            | Already exists                            |
| OTHER           | Already exists                            |
| >>END-EVALUATE  | New token (it already exists witout '>>') |
| TRUE            | Already exists                            |
| >>IF            | New token (it already exists witout '>>') |
| >>ELSE          | New token (it already exists witout '>>') |
| >>END-IF        | New token (it already exists witout '>>') |
| IS              | Already exists                            |
| NOT             | Already exists                            |
| DEFINED         | New token                                 |

**Comment by fm-117** [comment]
Actually there is a problem with keywords:
- `AS`
- `DEFINED`
- `DLL`
- `PARAMETER`
- `STATIC`

While they have to be recognized as reserved words in some of the new directives, they are not part of the Cobol reserved-words list.
How do we implement contextual keyords in CUP ? :worried:

**Comment by smedilol** [comment]
Detection of conditional syntax is done. A diagnostics is set to state that we don't support this kind of syntax.
