### ISSUE TITLE
ParserTests failures

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#17]
* *Check_EntryCodeElements* continued failure is due to a "no viable alternative to EOF" error. This seems related to [this issue] (https://github.com/antlr/antlr4/issues/118); however we DO have **cobolCodeElements: codeElement* EOF;** as our start rule so I'm scratching my fluffy head, here.

* *TestParser.Check_ParserIntegration()* fails because it tests type compatibility during a move statement. However, TypeChecker is commented out. Moreover, TypeChecker commented code makes intensive use of unimplemented classes and parameters, even taking into account the fact that I branched the current HEAD of TypeCobol.

**Comment by smedilol** [comment]
Is it still a bug?

**Comment by wiztigers** [comment]
It was.
It isn't anymore.
