### ISSUE TITLE
Review AutoRemarks and UseEuroInformationLegacyReplacingSyntax options

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#1704]
The two options `AutoRemarks` and `UseEuroInformationLegacyReplacingSyntax` controls the EI legacy copy replacing/suffixing mechanism and should be updated.

At least one abnormal case has been found :
- when using EI_Release code on a program that contains a REMARKS directive, the directive will be rewritten no matter what value is set for AutoRemarks. The REMARKS lines should be left untouched when the option is set to `False`.

Also this whole mechanism may become useless if copies are preprocessed before calling the parser (after migrating on RTC).

The goal of this issue is to clarify the role of the options and discuss whether they should be updated or completely removed.

**Comment by fm-117** [comment]
PR #2132 removed the `AutoRemarks` option.

**Comment by smedilol** [comment]
No longer necessary as TypeCobol syntax is abandonned and `AutoRemarks` option has been removed.
