### ISSUE TITLE
Exception on CrossChecker when using RENAMES clauses

### ISSUE THREAD

**Issue by alvaro-vantis-pt** [TypeCobolTeam/TypeCobol#1711]
**Describe the bug**
CrossChecker exception when trying to get the references for a data-item defined in a 66 level.

**To Reproduce**
Compile the attached sample code.

[TSTRENMS.zip](https://github.com/TypeCobolTeam/TypeCobol/files/4416554/TSTRENMS.zip)

Also attached z/OS compiler output

[tstrenms.zip](https://github.com/TypeCobolTeam/TypeCobol/files/4416558/tstrenms.zip)

**Comment by rooksdo** [comment]
**Stacktrace**

![image](https://user-images.githubusercontent.com/57907033/78571272-4b8f6300-7826-11ea-8c39-6b83ed105b94.png)

**Comment by rooksdo** [comment]
**Unit test**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. PGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01   X.
            05  X1   PIC X.
            05  X2   PIC X.
            05  X3   PIC X.
            05  X4   PIC X.
            05  X5   PIC X.
       66   Y RENAMES
                 X2  THRU
                 X4.
       PROCEDURE DIVISION.
      *
              MOVE 'ABC' TO Y
      *
       END PROGRAM PGM.
```

**Comment by fm-117** [comment]
The error comes from the type-compatibility check that we perform on MOVE statements. In its current form, the code is unable to compare group types when a RENAMES has been used. We are working on a new type system which should cover this issue but this is mid-term goal.
As for the current code, we will look into it so as to skip the type-compatibility check and optionally emit a warning to inform user that the MOVE may be unsafe.
