### ISSUE TITLE
Potential grammar improvement: forbidden sections in procedures

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#1726]
Currently, the fact that a GLOBAL-STORAGE SECTION should not appear in a procedure is checked manually in a dedicated checker `GlobalStorageSectionChecker`.
This could be taken care of by the CUP grammar.

Also check for forbidden FILE SECTION in a procedure as it should also be treated as a parsing error.

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
