### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#173]
According to the new table of contents described in #166, technical info should be transferred from front page to appropriate technical wiki pages.

**Comment by wiztigers** [comment]
@laurentprudhon , could you please check if the new [API wiki page](https://github.com/TypeCobolTeam/TypeCobol/wiki/API) contains information that is up-to-date even after you big refactors of last year ?
So this page currently just contains information from root `README.md` -I didn't add/correct anything yet.

**Comment by smedilol** [comment]
Abandonned. Reopen issue when needed.
