### ISSUE TITLE
Allow for copy type (CPY or CPX/CPM) to be detected while parsing

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1732]
### Description
Allow for copy type (CPY or CPX/CPM) to be detected while parsing. Here are the two declarations that should be supported :

```cob
01 MYCOPY.         COPY YMYCOPY.
```
or using a `REPLACING` clause

```cob
01 MYCOPY.         COPY YMYCOPY REPLACING :MYCOPY: BY MYCOPY.
```

**Specific pretreatment for CPY must also be supported :        (does not apply to CPX/CPM/LTNV)**

1. Processing copy suffixing if the length of copy name > 7 characters
```cob
01 MYCOPY.         COPY YMYCOPY1. *> Same behavior as now
01 MYCOPY.         COPY YMYCOPY1S. *> Suffixing by 'S'
01 MYCOPY.         COPY YMYCOPY1L. *> Suffixing by 'L' must also be accepted
```
2. Suppressing level-01 when it is already declared in the copy, as in (YMYCOPY declares a level-01) :
```cob
01 MYCOPY.         COPY YMYCOPY.
01 MYCOPY.         COPY YMYCOPY REPLACING :MYCOPY: BY MYCOPY.
```

Currently the parser guess that a COPY is a CPY when a COPY is declared without replacing clause and the 8th character of the COPY name is not a `L`.
This rule must be replaced by a true detection of CPY based on an external file which contains the list of all CPY name.

### Test 1
YMYCOPY (CPY)
```cob
       01 YMYCOPY.
           05 MYCOPY-DATA           PIC X.
```
**Test 1.a**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ko because level 01 is systematically erased when included copybook is CPY
       COPY YMYCOPY.
       PROCEDURE DIVISION.
           .
       END PROGRAM Pgm.
```
**Test 1.b**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ok
       01 MYCOPY.     COPY YMYCOPY.
      *Ok suffixing YMYCOPY with '1'
      *All string matching 'MYCOPY' will be suffixed by '1' (giving MYCOPY1)
       01 MYCOPY1.    COPY YMYCOPY1.
       PROCEDURE DIVISION.
      *   Ok
           Move 'A'             to MYCOPY-Data
      *   Ok because a version of YMYCOPY is also declared suffixed by '1'
           Move 'A'             to MYCOPY1-Data
           .
       END PROGRAM Pgm.
```
**Test 1.c**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ok for syntax but the REPLACING clause doesn't work without placeholder
       01 MYCOPY1.    COPY YMYCOPY REPLACING ==MYCOPY== BY ==MYCOPY1==.
       PROCEDURE DIVISION.
      *   Ko MYCOPY1-Data is not defined (attempted suffixing by '1' failed because of placeholder)
           Move 'A'             to MYCOPY1-Data
           .
       END PROGRAM Pgm.
```
### Test 2
YMYCOPY (CPY with placeholder :MYCOPY:)
```cob
       01 Y:MYCOPY:.
           05 :MYCOPY:-DATA           PIC X.
```
**Test 2.a**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ko because level 01 is systematically erased when included copybook is CPY
       COPY YMYCOPY.
       PROCEDURE DIVISION.
           .
       END PROGRAM Pgm.
```
**Test 2.b**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ko because placeholders are not replaced
       01 MYCOPY. COPY YMYCOPY.
       PROCEDURE DIVISION.
           .
       END PROGRAM Pgm.
```
**Test 2.c**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ok
       01 MYCOPY. COPY YMYCOPY REPLACING ==:MYCOPY:== BY ==MYCOPY==.
      *Ok the placeholder can be replaced with an added suffix
       01 MYCOPY1. COPY YMYCOPY REPLACING ==:MYCOPY:== BY ==MYCOPY1==.
       PROCEDURE DIVISION.
      *   Ok
           Move 'A'             to MYCOPY-Data
      *   Ok
           Move 'A'             to MYCOPY1-Data
           .
       END PROGRAM Pgm.
```
**Test 2.d**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ok for declaration but suffixing YMYCOPY not working with placeholder
       01 MYCOPY1. COPY YMYCOPY1 REPLACING ==:MYCOPY:== BY ==MYCOPY==.
       PROCEDURE DIVISION.
      *   Ko because special CPY suffixing mechanism doesn't apply with placeholder
           Move 'A'             to MYCOPY1-Data
           .
       END PROGRAM Pgm.
```
**Test 2.e**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ok for declaration but suffixing YMYCOPY not working with placeholder, the REPLACING will suffix MYCOPY1
       01 MYCOPY1. COPY YMYCOPY1 REPLACING ==:MYCOPY:== BY ==MYCOPY1==.
       PROCEDURE DIVISION.
      *   Ok thanks to REPLACING clause
           Move 'A'             to MYCOPY1-Data
           .
       END PROGRAM Pgm.
```
**Test 2.f**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ok for declaration but suffixing YMYCOPY not working with placeholder 
      *Same as declaring {01 MYCOPY1 COPY YMYCOPY. REPLACING ==:MYCOPY:== BY ==MYCOPY==.}
       01 MYCOPY1. COPY YMYCOPY1 REPLACING ==:MYCOPY:== BY ==MYCOPY==.
       PROCEDURE DIVISION.
      *   Ok because special CPY suffixing mechanism doesn't apply with placeholder
           Move 'A'             to MYCOPY-Data
           .
       END PROGRAM Pgm.
```
### Test 3
YMYCOPY (CPX without placeholder :MYCOPY:)
```cob
       01 YMYCOPY.
           05 MYCOPY-DATA           PIC X.
```
**Test 3.a**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ok because level 01 is not deleted for CPX/CPM
       COPY YMYCOPY.
       PROCEDURE DIVISION.
      *   Ok
           Move 'A'             to MYCOPY-Data
           .
       END PROGRAM Pgm.
```
**Test 3.b**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ko because no automatic suffixing mechanism for CPX and YMYCOPY1 doesn't exist
       COPY YMYCOPY1.
       PROCEDURE DIVISION.
           .
       END PROGRAM Pgm.
```
**Test 3.c**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ok for syntax but the REPLACING clause doesn't work without placeholder
       COPY YMYCOPY REPLACING ==MYCOPY== BY ==MYCOPY1==.
       PROCEDURE DIVISION.
      *   Ko because MYCOPY1-Data not declared
           Move 'A'             to MYCOPY1-Data
           .
       END PROGRAM Pgm.
```
### Test 4
YMYCOPY (CPX with placeholder :MYCOPY:)
```cob
       01 Y:MYCOPY:.
           05 :MYCOPY:-DATA           PIC X.
```
**Test 4.a**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ko because placeholders not replaced
       COPY YMYCOPY.
       PROCEDURE DIVISION.
           .
       END PROGRAM Pgm.
```
**Test 4.b**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ok
       COPY YMYCOPY REPLACING ==:MYCOPY:== BY ==:MYCOPY:==.
       PROCEDURE DIVISION.
      *   Ok
           Move 'A'             to MYCOPY-Data
           .
       END PROGRAM Pgm.
```
**Test 4.c**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ko because YMYCOPY1 doesn't exist
       COPY YMYCOPY1 REPLACING ==:MYCOPY:== BY ==:MYCOPY:==.
       PROCEDURE DIVISION.
           .
       END PROGRAM Pgm.
```
**Test 4.d**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ok
       COPY YMYCOPY REPLACING ==:MYCOPY:== BY ==:MYCOPY1:==.
       PROCEDURE DIVISION.
      *   Ok
           Move 'A'             to MYCOPY1-Data
           .
       END PROGRAM Pgm.
```
**Test 4.e**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *Ko because YMYCOPY1 doesn't exist
       COPY YMYCOPY1 REPLACING ==:MYCOPY:== BY ==:MYCOPY1:==.
       PROCEDURE DIVISION.
      *   Ko because MYCOPY1-Data si not declared
           Move 'A'             to MYCOPY1-Data
           .
       END PROGRAM Pgm.
```
       

### Expected results
|     Test     |   ZComp  |
| ----------- | ----------- |
| 1.a          | Ko           |
| 1.b          | Ok           |
| 1.c          | Ko           |
| 2.a          | Ko           |
| 2.b          | Ko           |
| 2.c          | Ok           |
| 2.d          | Ko           |
| 2.e          | Ok           |
| 2.f          | Ok           |
| 3.a          | Ok           |
| 3.b          | Ko           |
| 3.c          | Ko           |
| 4.a          | Ko           |
| 4.b          | Ok           |
| 4.c          | Ko           |
| 4.d          | Ok           |
| 4.e          | Ko           |

**Technical tip**
As CPY copys are not allowed to be created anymore, we could extract all the existing CPY copys into a file and inspect it to find the copy name, in which case it would be considered of type CPY, otherwise of type CPX or CPM (no distinction between those two can be made using the parser at the present moment).

See property HasSuffix of TextNameVariation.

Se rule which check if there is no replace in `ReplaceTokensLinesIterator` :
`if (CopyReplacingDirective != null && CopyReplacingDirective.RemoveFirst01Level && CopyReplacingDirective.ReplaceOperations.Count == 0)`

**Comment by smedilol** [comment]
@rooksdo As discussed with @fm-117, we could remove the whole parsing of remarks when this issue is done.

**Comment by fm-117** [comment]
About the implementation, without considering the specs, I thought it is cleaner to have a new option for the CPY list instead of a static context.

**Comment by smedilol** [comment]
Yes I agree, we need an option for both CLI and LanguageServer to specify the file (list of copy) to use.

**Comment by mayanje** [comment]
Why file list of copy are differents between CLI and LanguageServer ?

**Comment by smedilol** [comment]
The file list is not different between CLI and LS, but we need a parameter to specify the path to the list and not a hardcoded file name hidden in a class.

**Comment by mayanje** [comment]
But we can also have a default fle name put in the same path then the CLI.exe, because there will be a predefined file that comes from the extraction of CPY list we made?

**Comment by rooksdo** [comment]
I agree with @mayanje , it's good to have a default file (i.e the extracted file). But we should still have the option to specify another one or none.

**Comment by smedilol** [comment]
Yes but just beware that our LanguageServer.exe runs with the default working directory set as `%TEMP%\tcbl` and not `.`.
So if the default file is meant to be a relative path, then it should be clear that the path is relative to the default working directory or the location of LanguageServer.dll.

**Comment by mayanje** [comment]
Yes, by default like for the default TypeCobol.CLI.log file it will be the directory of the TypeCobol.languageServer.exe or TypeCobol.CLI.exe.

**Comment by fm-117** [comment]
Indeed, we have the same problem with paths to custom analyzers (`-ca` option). Relative paths are computed from current working directory which may or may not be the .exe location depending on the client choice.

**Comment by mayanje** [comment]
ok right so, one can use System.Reflection.Assembly.GetExecutingAssembly().Location get the right directory.

**Comment by fm-117** [comment]
`Assembly.GetExecutingAssembly()` is the running assembly so it may not work, `Assembly.GetEntryAssembly()` would work i guess. There is also `Process.GetCurrentProcess()` but the question is should we really change the logic for paths ? I mean it is normal behavior to build full path from relative using working dir. So if the client has chosen a non-default working dir, it is aware that relative paths are related to this dir. I think we should handle this client-side, CLI and/or LanguageServer may validate the paths before using them though.

**Comment by mayanje** [comment]
For locating CLI and Server location at runtime System.Reflection.Assembly.GetExecutingAssembly().Location is enough because it will be called by itself.

**Comment by fm-117** [comment]
Let's consider this just like another external file passed to the Server/CLI. It works exactly like Intrinsic file for example, and the client just pass the full path to the intrinsics file so we should do just the same without considering a default file name and/or location.

**Comment by mayanje** [comment]
This means that we should not consider a default COPY list file if none is supplied.

**Comment by fm-117** [comment]
Absolutely. Default for me is that there is no CPY definitions, all copies are considered 'regular' copies and there is no need to alter them before inclusion.

**Comment by mayanje** [comment]
@fm-117 @smedilol @rooksdo , now I am little be confused, because the purpose here is also to remove the current treatment performed by detecting 8th character.  So a COPY list file of CPY is always needed.

**Comment by mayanje** [comment]
But @fm-117 is right Assembly.GetEntryAssembly() should work, if the default file is set by CLI or Server.

**Comment by smedilol** [comment]
@mayanje If there is no list of CPY provided, then only standard Cobol mechanism for COPY apply:
- No suffixing
- Don't touch level 01 inside COPY
