### ISSUE TITLE
LSP incremental Warnings diagnostics are not cleared

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1734]
**Description**

Incremental Warning Diagnostics are not cleared, there is an accumulation of such diagnostics in each notification. See the the Diagnostics dump below. But ERROR notifications are not duplicated only WARNING notifications.

**Dump**

START DIAGNOSTICS TIME : Fri Jun 05 09:54:14 CEST 2020
Diagnostic [
  range = Range [
    start = Position [
      line = 29
      character = 8
    ]
    end = Position [
      line = 29
      character = 12
    ]
  ]
  severity = Error
  code = "27"
  source = "Find the syntax diagram describing the statement in error in the language reference"
  message = "Syntax error : extraneous input 'lkhlh' expecting {separator, numeric literal, symbol, statement starting keyword, keyword, Formalized Comments elements}"
]
Diagnostic [
  range = Range [
    start = Position [
      **_line = 68_**
      character = 8
    ]
    end = Position [
      line = 68
      character = 28
    ]
  ]
  _**severity = Warning**_
  code = "37"
  source = ""
  **_message = "Warning: a End statement is not aligned with the matching opening statement"_**
]
Diagnostic [
  range = Range [
    start = Position [
      line = 68
      character = 8
    ]
    end = Position [
      **_line = 68_**
      character = 28
    ]
  ]
  **_severity = Warning_**
  code = "37"
  source = ""
  **_message = "Warning: a End statement is not aligned with the matching opening statement"_**
]
Diagnostic [
  range = Range [
    start = Position [
      line = 68
      character = 8
    ]
    end = Position [
      **_line = 68_**
      character = 28
    ]
  ]
  **_severity = Warning_**
  code = "37"
  source = ""
  **_message = "Warning: a End statement is not aligned with the matching opening statement"_**
]
END DIAGNOSTICS TIME : Fri Jun 05 09:54:14 CEST 2020

**Comment by smedilol** [comment]
We already had this issue #1208.
It seems there are again Diagnostics attached to CodeElement in CrossChecker.
We should find a permanent solution:
- Split DiagnosticUtils in 2 and put them in 2 different namespace
   - DiagnosticUtils.AddError(CodeElement, ...) 
   - DiagnosticUtils.AddError(Node, ...) -> CrossChecker Will only use this class
- Check that CodeElement are not altered after CodeElement phase

**Comment by smedilol** [comment]
Fixed with #2037
