### ISSUE TITLE
Handle qualified paragraph references

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#1737]
`SymbolTable.GetParagraph` currently does not support qualified names for paragraphs. This is required for both #1710 and CFG integration (PR #1735). So the goal of this issue is to add this capability in `SymbolTable`.

Pseudo algorithm is as follow:
- Test if symbol reference is qualified
  - if no, simply return results using `symRef.Name`
  - if yes
    - select paragraph with name `symRef.Name`
    - cast symRef to `QualifiedSymbolReference`
    - search for section using `qualifiedSymRef.Head.Name`
    - keep only paragraphs whose parent is the found section

**Comment by rooksdo** [comment]
This issue will be done as part of #1710
