### ISSUE TITLE
Write our roadmap

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#175]
Our roadmap must be available on the project's wiki

**Comment by wiztigers** [comment]
I wrote a basic roadmap [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/Roadmap).

It doesn't contain the list of TypeCobol language specific features we want, though.
@smedilol , do you volunteer to formalize this ?

**Comment by smedilol** [comment]
Yes, I'll complete the page as soon as I take the time to do it ;)

**Comment by wiztigers** [comment]
I just added some stuff about TypeCobol, just to have an idea.

Feel free to correct/complete.

In particular, about the point "Make the generated code Cobol debugging friendly", I wasn't sure how specific I could be about the specific tools we have in mind ...

**Comment by smedilol** [comment]
Roadmap is up to date
