### ISSUE TITLE
Integrate DFA in CFG_SemanticDomainLite

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1750]
**Description**
The purpose of this issue is to integrate DFA algorithms based on the integration of the CFG in the SemanticDomainLite, this according to the work done in following issues:

#1260 Implement TypeCobol Data Flow Analysis

# Data Flow Analysis (DFA) #
## Data structures and Graphs (DFG) (A06) ##
- #1270 Increase the CFG graph with data structures and fields for DFA. (A06.T01).

## DFG and DFA Development. (A07) ##
- #1271 Identify TypeCobol instructions targeted by DFA. (A07.T01) 
- #1272 Apply the DFA algorithms. (A07.T02) 

## DFG/GraphViz Visualization and Tests. (A08). ##
- #1273 Generate the .dot file of a DFG graph. (A08.T01) 
- #1274 Test DFG dot graphs and visualization. (A08.T02)

# DFA in Practice #
## Identification of the target modules of a CALL. (A09) ##
- #1275 Identify the modules called by a CALL statement. (A09.T01) 

## CFG/DFA TypeCobol Tests. (A10) ##
- #1276 Write CFG and DFA test sets for TypeCobol. (A10.T01)

**Comment by rooksdo** [comment]
Fixed by #1751
