### ISSUE TITLE
Handle copy replacing with ==::==

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1752]
**Describe the bug**
Our parser cannot use standard Cobol Copy with a replacing clause containing string `::`.
```cobol
       01  xxxENT. COPY YxxxENT REPLACING ==::== BY ====. 
```
YxxxENT contains:
```cobol
           05  xxxENT::-FCT01.
               10 xxxENT::-FCT01-Var1            PIC X(05).
```

The parser interpret `::` as TypeCobol operator but inside a replacing clause (Pseudo text), this operator should be considered as plain text.

**Expected behavior**
No error.
The expanded source is:
```cobol
       01  xxxENT. 
           05  xxxENT-FCT01.
               10 xxxENT-FCT01-Var1            PIC X(05).
```

**Technical**
See Scanner class and use property `IsInsidePseudoText` of the ScanState to inhibit creation of token `::` inside pseudo text.

**Comment by fm-117** [comment]
Testing for `IsInsidePseudoText` won't be enough, we'll have to allow the creation of a PartialCobolWrod for text `::` and double colon must be replaced correctly while parsing the copy (as for now `::` will be materialized as a QualifiedNameSeparator token).
It means that interpretation of the text `::` inside a copy depends on the active REPLACING clause.
See #428 for other out-of-ordinary REPLACING clauses.
One way to tackle this could be to avoid creating original tokens of a copy but only create the replaced ones. This is a rather large change of the Scanner though...

**Comment by rooksdo** [comment]
To be in conformity with the specifications, replacing clause should handle any placeholder between ==[placeholder]==

**Comment by smedilol** [comment]
@fm-117 @mayanje Goal for this issue: In the scanner:
Inside a copy, do not recognize the `::` operator. Only recognize two `:`  in a row.

**Comment by fm-117** [comment]
Reopening because current solution does not allow direct parsing of a copy without initial ScanState.

**Comment by fm-117** [comment]
So I have created [this branch](https://github.com/TypeCobolTeam/TypeCobol/tree/1752_ImproveInitialScanStateHandling) to change when the initial scan state is created (see 809508738e7947cae2b3924f5ed7d38463b0cb5e) but all this will certainly change again with support of direct copy parsing, so no PR for the moment.

**Comment by fm-117** [comment]
See #1870, the handling of initial scan state will be done with direct copy parsing.
