### ISSUE TITLE
Copy replacing for a level

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1753]
**Describe the bug**
Copy replacing that want to change a level number doesn't works.
It certainly related to #428 (check the proposed solution)
When this issue is resolved, also if it resolves #599.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 MyGroup.
           COPY YXXXENT REPLACING  ==:XXXENT:==  BY ==XXXENT==
                                   ==01 :XXXENT:== BY ==02 XXXENT==.
      
       END PROGRAM DVZF0OSM.
```

With YXXXENT :
```cobol
       01 :XXXENT:.
          05 :XXXENT:-G1.
                20 :XXXENT:-Var1        PIC X(01).
```
Our parser report the error `Syntax error : A group item cannot be empty.` on variable `MyGroup`
The replacing `==01 :XXXENT:== BY ==02 XXXENT==` doesn't works

**Expected behavior**
No error.
Variable `01 :XXXENT:` is replaced by `02 XXXENT`.

**Comment by rooksdo** [comment]
Fixed by #1795
