### ISSUE TITLE
Delete Antlr PreProcessor

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1788]
We have 2 implementations of the PreProcessor:
- With Antlr : legacy and not used anymore
- With CUPS : new implementation and used

Antlr implementation is not used since a long time.
So we can delete this implementation.

**Comment by fm-117** [comment]
Delete property `UseAntlrProgramParsing` in `TypeCobolOptions` and update usages. Remove all unused methods tied to ANTLR program parsing.

**Comment by smedilol** [comment]
As we still have to migrate our CodeElement grammar from Antlr to CUPS, I suggest to keep `UseAntlrProgramParsing` in `TypeCobolOptions`.
