### ISSUE TITLE
COPY in data descriptions and anonymous REDEFINES

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#179]
This may be 2 different issues:
1. The current way of creating data descriptions doesn't support copies.
2. Anonymous data descriptions are not stored in the symbol table.

This is the kind of data description I'm talking about:
```cobol
01  SOMETHING.
   02  AREA1.
      COPY MYCOPY1.
   02  AREA2 PIC X(4000).
   02  REDEFINES AREA2.
      COPY MYCOPY2.
```

**Comment by smedilol** [comment]
This issue is referenced in: #216 and #235
I propose to close this one.
