### ISSUE TITLE
Identifiers

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#18]
Because they are so widely used everywhere in the grammar, identifiers must be properly parsed.
These are not CodeElements, but nodes of our symbol tree that have a lot of other nodes (subscripts, reference modifiers, ...) under them.

**Comment by wiztigers** [comment]
I'm yet unclear on what is exactly a *special register*, and especially when it can be used. 
On one hand, there is a whole list of special registers including **ADDRESS OF**, **LENGTH OF** on p16, with only the usage of some of them being noted ; on the other hand, words like **DEBUG-ITEM** are called special registers too, but are not in the list.

So : 
* are special registers allowed anywhere identifiers are allowed ? Or does it depend on the statement considered ?
* what is an exhaustive list of special registers ?

Thanks for your comments.

**Comment by wiztigers** [comment]
Is *LENGTH OF* a function identifier or a special register ?

Are function identifiers allowed everywhere identifiers are allowed ? I've seen it only in a `MOVE` statement yet.

**Comment by osmedile** [comment]
special registers are:
`ADDRESS OF
DEBUG-ITEM  which is defined as:
01 DEBUG-ITEM.
  02 DEBUG-LINE PICTURE IS X(6).
  02 FILLER PICTURE IS X VALUE SPACE.
  02 DEBUG-NAME PICTURE IS X(30).
  02 FILLER PICTURE IS X VALUE SPACE.
  02 DEBUG-SUB-1 PICTURE IS S9999 SIGN IS LEADING SEPARATE CHARACTER.
  02 FILLER PICTURE IS X VALUE SPACE.
  02 DEBUG-SUB-2 PICTURE IS S9999 SIGN IS LEADING SEPARATE CHARACTER.
  02 FILLER PICTURE IS X VALUE SPACE.
  02 DEBUG-SUB-3 PICTURE IS S9999 SIGN IS LEADING SEPARATE CHARACTER.
  02 FILLER PICTURE IS X VALUE SPACE.
  02 DEBUG-CONTENTS PICTURE IS X(n).

JNIENVPTR
LENGTH OF
LINAGE-COUNTER
RETURN-CODE
SHIFT-OUT
SHIFT-IN
SORT-CONTROL
SORT-CORE-SIZE
SORT-FILE-SIZE
SORT-MESSAGE
SORT-MODE-SIZE
SORT-RETURN
TALLY
WHEN-COMPILED
XML-CODE
XML-EVENT
XML-TEXT
XML-NTEXT
XML-NAMESPACE
XML-NNAMESPACE
XML-NAMESPACE-PREFIX
XML-NNAMESPACE-PREFIX
XML-INFORMATION
CURRENT-DATE
TIME-OF-DAY

**Comment by wiztigers** [comment]
GRAMMAR CHANGE:
`LENGTH OF` special register can be written without `OF` in production code.
So, we have to differentiate between, for example :
`MOVE FUNCTION LENGTH (x) TO y` <-- this is an intrinsic function call
`MOVE LENGTH OF x TO y` <-- this is a special register usage
`MOVE LENGTH x TO y` <-- this is a special register usage, too

**Comment by wiztigers** [comment]
Identifier are widely implemented ; the only remaining issue is #50.
Let's close this ticket to minimize duplicates.
