### ISSUE TITLE
NullReferenceException with wrong Cobol instruction `set xxx up to`

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1805]
**Describe the bug**
NullReferenceException with wrong Cobol instruction `set xxx up to `

   à TypeCobol.Compiler.Parser.CobolExpressionsBuilder.CreateVariableOrExpression(VariableOrExpression2Context context) dans TypeCobol\Compiler\Parser\CodeElementBuilder\CobolExpressionsBuilder.cs:ligne 1475
   à TypeCobol.Compiler.Parser.CobolStatementsBuilder.CreateSetStatementForIndexes(SetStatementForIndexesContext context) dans TypeCobol\Compiler\Parser\CodeElementBuilder\CobolStatementsBuilder.cs:ligne 1141
   à TypeCobol.Compiler.Parser.CodeElementBuilder.EnterSetStatement(SetStatementContext context) dans TypeCobol\Compiler\Parser\CodeElementBuilder\CobolCodeElementBuilder.cs:ligne 2104
   à TypeCobol.Compiler.Parser.Generated.CodeElementsParser.SetStatementContext.EnterRule(IParseTreeListener listener) dans obj\EI_Debug\TypeCobol\CodeElementsParser.cs:ligne 24360
   à Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   à Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   à TypeCobol.Compiler.Parser.CodeElementsParserStep.ParseProcessedTokensLinesChanges(TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 documentLines, IList`1 processedTokensLinesChanges, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, PerfStatsForParserInvocation perfStatsForParserInvocation) dans TypeCobol\Compiler\Parser\CodeElementsParserStep.cs:ligne 257

**To Reproduce**
Instruction `SET I-TAB-MAX                 UP TO I-DTL` instead of `SET I-TAB-MAX                 UP BYI-DTL` causes this exception.

Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. RB1BCTLB.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 W-TAB.
          05 W-TAB2 OCCURS 50 INDEXED BY I-DTL.
            10 W-TAB-ELT                  PIC X(07).
       01 I-TAB-MAX                           PIC S9(02) COMP-5.
      
       PROCEDURE DIVISION.
           SET I-TAB-MAX                 UP TO I-DTL
           .
       END PROGRAM RB1BCTLB.
      
```

**Expected behavior**
No exception.
Diagnostic to report the syntax error.

**Comment by rooksdo** [comment]
Is this issue related to #1803 ?
