### ISSUE TITLE
IAnalyser and new execution step for quality rules

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1816]
### The need
We plan to develop more quality rules with our parser.

These quality rules will be done on a private repository, so we need a way to "plug" quality rules inside the parser.
A quality rule must be executed when all symbol have been resolved.
These quality rules could become slow. Code completion for LSP must remains as fast as possible.
As Completion within LSP requires  CrossCheck execution step to be complete, we need a new execution step to be sure that quality rules will not be executed.

Diagnostics of quality rules and all others diagnostic must be sent by LSP 500ms after no update of texte have been received by LSP.
When completion is requested, only diagnostics up to CrossCheck step will be sent by LSP.

### Raw solution
Extend the IAnalyser to provide a way to create quality rules.
This IAnalyser will be executed in a new step after CrossCheck.

### Out of perimeter of this issue:
- Load quality rules from an external DLL. See #1825.
- Define how a quality rule return information. Fow now we use Diagnostics.

**Comment by fm-117** [comment]
- [ ] Introduce new compilation step `QualityCheckStep`
- [ ] Introduce new analyzer type `IASTAnalyzer` (extending both `IAnalyzer` and `IASTVisitor`) and update analyzer provider mechanism
- [ ] On LSP, modify `RefreshSyntaxTree` method
  - add new boolean parameter `refreshCodeAnalysis`
  - when set to true, call the new execution step on the FileCompiler instance
  - this new boolean will be set to true for timer event and node refresh action
  - for the other usages, this would depend of the current request (see usages of `GetDocumentContextFromStringUri`)
