### ISSUE TITLE
Distinguish filenames from identifiers

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#183]
Since a027643b019d948cdcae27541f2e81c89aa87afd, the COBOL grammar doesn't separate filenames from identifiers anymore (and even before that, the rule to reduce filenames was never consumed).

Now that filenames are 'just' identifiers, we may need a way to distinguish between the two.

**Comment by wiztigers** [comment]
As a file name is just a user defined word, and as an identifier can be just a data name, which is just a user defined word, the problem doesn't seem to be easy to solve.

The behaviours we don't want to run into is :
* either mark all filenames as undeclared symbols (ie. data references not found in symbol table).
* or not find undeclared symbols at all (because they might maybe be filenames)

**Comment by wiztigers** [comment]
Filenames tend to only be used in very specific statements, like `OPEN`, `CLOSE` and the like. In these cases, identifiers can't be there, so the grammar can enforce the fact that we found a filename.

Off the top of my head, there are at least two exceptions to this:
* `WRITE` can accept record names. These are "not data" and must be declared as FD entries.
* `CALL BY REFERENCE` can accept filenames. This is an IBM extension that we have to support (our target being COBOL for zOS). It seems these are something that must be declared as a FD entry, too.

So, a solution may be: when we parse an identifier that we know that in can be a filename in the specific context of this statement, we set a boolean `MaybeFilename` or something like that. And when later we can't find some name in the symbol table, we could check this identifier.
* if it's `false`, we raise a "symbol not found" error and call it a day as we always did
* if it's `true`, we raise a "symbol not found" error _only if it's no a FD entry, either_

Our current symbol table doesn't support FD entries for now, however.
Thus, I'll aprreciate opinions about this topic before implementing the feature.

**Comment by smedilol** [comment]
I vote for your proposal with " MaybeFilename" bool.
As the grammar can't help us to distinguish fileName from identifier in certain cases, I think it's best to remove _fileName_ from grammer (only leave a comment so say that a fileName can be present according to the spec).

**Comment by smedilol** [comment]
Is it still a RFC issue?

**Comment by wiztigers** [comment]
Nah, I don't think so.
This will be taken care of during merging of PR #249.

**Comment by wiztigers** [comment]
#249 took care of this
