### ISSUE TITLE
Warning if READY TRACE is used

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1832]
Warning if READY TRACE is used

Cobol code to check
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. NOMPGM.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-370
                      WITH DEBUGGING MODE
                      .
       SPECIAL-NAMES. DECIMAL-POINT IS COMMA.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
         01 WS-FOO PIC X(42).
         01 WS-BAR PIC X(42).
      
       PROCEDURE DIVISION.
      *Warning ready trace
           READY TRACE
           goback
           .
       END PROGRAM NOMPGM.
      
```

**Comment by delevoye** [comment]
@smedilol Do we need to flag `RESET TRACE` too?
IBM documentation tells both should not be used anymore.

**Comment by fm-117** [comment]
`READY/RESET TRACE` are represented as `CompilerDirective` instances by the parser so we can't get them from `Node` or `CodeElement`. Those directives are stored on `ProcessedTokensLine` so they can be retrieved through a `ProcessedTokensDocument` but currently no analyzer can access this kind of snapshot.

**Comment by smedilol** [comment]
@delevoye Yes you can also flag `RESET TRACE`.

@fm-117 Yes RESET/READY TRACE are Compiler directive. I didn't see that. 
Maybe we can create a new checker which would be called by `CompilerDirectiveBuilder`.

**Comment by fm-117** [comment]
We already have a mechanism to add diagnostics on directives, it is not a separate Checker class but anywway it would be fairly easy to add the warning for `RESET/READY TRACE` directly in the parser.
The question is: should we add a mechanism for external analyzers to check CompilerDirectives ?

**Comment by fm-117** [comment]
Now that #1869 is closed, this check can be handled in an external analyzer. Closing the issue.
