### ISSUE TITLE
Codegen build fails with VS2019

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1833]
**FOLLOWING OF #1680**

It seems there is still a bug during the build of TypeCobol with VS2019.
Error on Codegen project : The "TemplateClassGenerationTask" task returned false but did not log an error.

Others projects works except for those which depend on Codegen.

**Comment by fm-117** [comment]
The problem has been identified, there are 2 bugs in the custom msbuild tassk used to generate skeleton class from xml description. This will be fixed with [this PR](https://github.com/TypeCobolTeam/TypeCobol.TemplateTranspiler/pull/8) and integrated along with #1834.

**Comment by fm-117** [comment]
Change reverted.
