### ISSUE TITLE
Upgrade to .NET 4.7.2 framework

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1834]
### Description

In order to improve security an upgrade to .NET framework 4.7.2 is required.

**Comment by fm-117** [comment]
- check `TargetFrameworkVersion` in *.csproj, and props
- check all dependencies

**Comment by fm-117** [comment]
Change reverted.

**Comment by fm-117** [comment]
Patch file to upgrade later.
[Patch_UpgradeNET472.diff.txt](https://github.com/TypeCobolTeam/TypeCobol/files/5856595/Patch_UpgradeNET472.diff.txt)
