### ISSUE TITLE
Missing END PROGRAM diagnostic is incomplete

### ISSUE THREAD

**Issue by delevoye** [TypeCobolTeam/TypeCobol#1844]
**FOLLOWING #1162**

**Describe the bug**

- Position of the diagnostic may be wrong
- Parser does not check if the name of declaring program and first END PROGRAM encountered are the same

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Main.
       PROCEDURE DIVISION.
           GOBACK
           .
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Nested1.
       PROCEDURE DIVISION.
           GOBACK
           .
      *END PROGRAM Nested1.
       END PROGRAM Main. 
```
Diagnostic is placed on `PROGRAM-ID. Main.`

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Main.
       PROCEDURE DIVISION.
           GOBACK
           .
       END PROGRAM whatever. 
```

No diagnostic created.

And add a configurable severity.
In TypeCobolConfiguration, add a new property:
`public TypeCobolCheckOption CheckEndProgram { get; set; }` to dynamically activate the rule.

**Expected behavior**
Diagnostic should be placed on `PROGRAM-ID. Nested1.` for example 1.
New diagnostic should be placed on `END PROGRAM whatever.` for example 2.

**Technical**
See ProgramClassBuilder.EndCobolProgram

**Comment by fm-117** [comment]
For reference, here are the IBM compiler messages for both samples:
- `End of source file was encountered or an "END PROGRAM" marker for a containing program was found, but an "END PROGRAM" marker for program "NESTED1" was not found. "END PROGRAM NESTED1" was assumed.`
- `Program-name "WHATEVER" did not match the name of any open program. The "END PROGRAM" marker was assumed to have ended program "MAIN".`
They are both placed on the latest line.
