### ISSUE TITLE
Allow direct parsing of copy

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1870]
### Description

Enable the parser to parse directly a copy.

How to do it :
 - When parsing a copy, generate a mock skeleton program in which the content of the target copy is injected in `WORKING-STORAGE SECTION`.
 - Any diagnostic would be reported on the copy line using an offset (due to the use of the skeleton program)

**Comment by smedilol** [comment]
We discussed 2 solutions:
1. Add generated lines around the COPY to include it a program
2. Parse a program that include the COPY 

Solution 1:
- Encapsulte the COPY in a program is easy to do with TextChange (see TypeCobol.Test/Parser/Performance/Performance.cs for an example). The name of the program can use the name of the COPY.
- Diagnostics will be reported on the wrong line. Need to map them to correct line
- Risk to report error on generated line

Solution 2:
- Diagnostics will be reported on the line that include the COPY
  - Some diagnostics detect that they are in a COPY
- We need to be sure that all diagnostics are reported (#1865)
- COPY are loaded from physical file. The name of the program that include the COPY cannot use the name of the COPY.

I think solution 1 is easier to implement.
