### ISSUE TITLE
Debug property on CodeElement

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#1878]
**SEE ALSO #1533**

A quality rule need to know if the CodeElement is in debug or not.

There is no easy way to get this info.
In CodeElementChecker class, we check if lines of each consumed token start with a `D` or `d`.

A CodeElement can be accross lines in debug and NOT in a debug.

Proposals:
Add new property(ies) on CodeElement:
- CodeElement.IsInDebug or UseDebug or AtLeastOneLineInDebug  (true if at least one line is in Debug)
- CodeElement.NoDebug (true if **no** lines are in Debug)
- CodeElement.MixNonDebugAndDebug (true if there is at least 1 line of Debug and 1 line without Debug)
- CodeElement.Debug which is an enum : NoDebug, Mix, AllDebug

What do you think?

What to do:
- Provide new property on CodeElement
- Update CodeElementChecker class to use this property.
- Create a dedicated test in `Misc` folder to test all cases

Technical hint:
- Reuse code in CodeElementChecker class to provide this property.

**Comment by mayanje** [comment]
I think it's a good suggestion.

**Comment by smedilol** [comment]
@delevoye You can go for : `CodeElement.Debug which is an enum : NoDebug, Mix, AllDebug`
