### ISSUE TITLE
' " ''

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#189]
In _IBM Entreprise COBOL 5.1 for zOS_ **p34**, it is said numeric literals can be declared between single quotes `'` or double quotes `"`.
I understand that if you want the value `HELLO`, you declare it either `'HELLO'` (single quote) or `'HELLO'` (double quotes).

But what do I get if I declare my litteral as `''HELLO''`, using _**two single quotes** at each side_ ?
Do I get the value **1:**`'HELLO'` ? Or **2:**`HELLO` ?

**Comment by delmasgu** [comment]
For alphanumeric literals we should use enclosing quotation marks (") or apostrophes (').

Delimiter used for the opening should be the same as for closing (i.e. "HELLO" or 'HELLO").

If you want to include an embedded quotation mark or apostrophe , when they are used as delimiter, you should use a pair of quotation marks ( " " ) or a pair of apostrophes ( '  ' ).

Then to have a ltteral containing  'HELLO' with the apostrophes, you can code either  " ' HELLO ' " or ' ' ' HELLO ' ' ' ( spaces between quotation marks and apostrophes are only here for a better readability of the example).

**Comment by delmasgu** [comment]
Sorry, a typo in the first example; of course you should read : "HELLO" or 'HELLO' !

**Comment by wiztigers** [comment]
Okay, so two single quotes doesn't equal one double quote, and alphanumeric literals are only delimited by one character on each side.
Thus I have nothing more to do that I've already done.
Thanks.
