### ISSUE TITLE
Exception on System.Collections.Generic.Dictionary2.Add(TKey key, TValue value)

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1896]
### Description

The following exception is thrown : 

`
Runtime error: System.ArgumentException: Un élément avec la même clé a déjà été ajouté.
   à System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   à TypeCobol.Compiler.CupParser.NodeBuilder.ProgramClassBuilder.Enter(Node node, CodeElement context, SymbolTable table) dans C:\repositories\TypeCobol\TypeCobol\Compiler\CupParser\NodeBuilder\ProgramClassBuilder.cs:ligne 129
   à TypeCobol.Compiler.CupParser.NodeBuilder.ProgramClassBuilder.OnInitializeStatement(InitializeStatement stmt) dans C:\repositories\TypeCobol\TypeCobol\Compiler\CupParser\NodeBuilder\ProgramClassBuilder.cs:ligne 926
   à TypeCobol.Compiler.CupParser.CUP_TypeCobolProgramParser_actions.CUP_TypeCobolProgramParser_do_action(Int32 CUP_TypeCobolProgramParser_act_num, lr_parser CUP_TypeCobolProgramParser_parser, StackList`1 xstack1, Int32 CUP_TypeCobolProgramParser_top) dans C:\repositories\TypeCobol\TypeCobol\Compiler\CupParser\TypeCobolProgramParser.cs:ligne 3912
   à TypeCobol.Compiler.CupParser.TypeCobolProgramParser.do_action(Int32 act_num, lr_parser parser, StackList`1 CUP_parser_stack, Int32 top) dans C:\repositories\TypeCobol\TypeCobol\Compiler\CupParser\TypeCobolProgramParser.cs:ligne 1435
   à TUVienna.CS_CUP.Runtime.lr_parser.parse() dans C:\repositories\TypeCobol\CSCupRuntime\lr_parser.cs:ligne 584
   à TypeCobol.Compiler.CupParser.NodeBuilder.CupParserTypeCobolProgramDiagnosticErrorReporter.SyntaxError(lr_parser parser, Symbol curToken) dans C:\repositories\TypeCobol\TypeCobol\Compiler\CupParser\NodeBuilder\CupParserTypeCobolProgramDiagnosticErrorReporter.cs:ligne 115
   à TypeCobol.Compiler.CupParser.TypeCobolProgramParser.syntax_error(Symbol cur_token) dans C:\repositories\TypeCobol\TypeCobol\Compiler\CupParser\TypeCobolProgramParser.cs:ligne 1510
   à TUVienna.CS_CUP.Runtime.lr_parser.parse() dans C:\repositories\TypeCobol\CSCupRuntime\lr_parser.cs:ligne 610
   à TypeCobol.Compiler.Parser.ProgramClassParserStep.CupParseProgramOrClass(TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 codeElementsLines, TypeCobolOptions compilerOptions, SymbolTable customSymbols, PerfStatsForParserInvocation perfStatsForParserInvocation, ISyntaxDrivenAnalyzer[] customAnalyzers, SourceFile& root, List`1& diagnostics, Dictionary`2& nodeCodeElementLinkers, List`1& typedVariablesOutsideTypedef, List`1& typeThatNeedTypeLinking) dans C:\repositories\TypeCobol\TypeCobol\Compiler\Parser\ProgramClassParserStep.cs:ligne 90
`

for the sample code :

```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
           REPLACE
             ==:Toto:==               By
             ==
             Initialize MyVar1 Replacing Alphanumeric By Space
             Initialize MyVar2 Replacing Alphanumeric By Space
             ==
             .
       PROCEDURE DIVISION.
      
           :Toto:
      
       END PROGRAM Pgm..
```

And this sample doesn't seem to throw any exception :

```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
           REPLACE
             ==:Toto:==               By
             ==
             Initialize MyVar1 Replacing Alphanumeric By Space
             ==
             .
       PROCEDURE DIVISION.
      
           :Toto:
      
       END PROGRAM Pgm.
```

The following sample also throws the exception
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
           REPLACE
             ==:Debut Pgm:==                 By
             ==
               Set  MyVAr1                   To True
               Set  MyVAr2                   To True
             ==
           .
      
       PROCEDURE DIVISION.
             :Debut Pgm:
             .
      
       END Program Pgm.
```

but not this sample
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
           REPLACE
             ==:Debut Pgm:==                 By
             ==
               Set  MyVAr1                   To True
             ==
           .
      
       PROCEDURE DIVISION.
             :Debut Pgm:
             .
      
       END Program Pgm.
```
Finally, this sample does not throw any exception :
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
           REPLACE
             ==:Toto:==               By
             ==
             Initialize MyVar1 Replacing Alphanumeric By Space
             Set  MyVAr2                   To True
             ==
             .
       PROCEDURE DIVISION.
      
           :Toto:
      
       END PROGRAM Pgm.
```

**Comment by fm-117** [comment]
The exception comes from the insertion into `NodeCodeElementLinkers` dictionary. To compare two CodeElements we use their consumed tokens, and in that case we are comparing replaced tokens. Replaced tokens are all positioned on the line of replaced text so despite the fact there are 2 distincts lines for `Set MyVar1 To True` and `Set MyVar2 To True` in the REPLACE instruction, those two will be put on the same line and the comparison will conclude that they are identical.

This may be solved by tweaking the `Equals/GetHashCode` implementations for `ReplacedToken` and `ReplacedTokenGroup` but... There is another bug, see #1903.
