### ISSUE TITLE
TypeCobol: TYPEDEF

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#191]
As specified on this [page](https://github.com/TypeCobolTeam/TypeCobol/wiki/Cobol02TYPEDEF).

**Comment by wiztigers** [comment]
Currently `SymbolTable` is not able to find data references if they are nested inside more than 1 level of `TYPEDEF`.
__TODO:__ upgrade `Get(QualifiedName)` to make good use of the `CustomTypes` map.

**Comment by smedilol** [comment]
As specified in [1c04612f9886e4f8c95faf16f8e7800fdb343d9e], tests were not complete.
So TYPEDEF is not fully implemented yet

**Comment by wiztigers** [comment]
@smedilol , I proposed an upgrade regarding syntax to the specification you've written [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/Cobol02TYPEDEF) :
- a page layout that resembles more to the COBOL specification (to maybe be the least confusing we can to long-time COBOL users)
- the use of `KEYWORD` instead of KEYWORD so language keywords better stand out
- the use of code highlighting. There is no typecobol highlighting (if it can be done, it would be nice to roll our own ♥‿♥), so I used cobol highlighting.

**Comment by wiztigers** [comment]
* [x]	`TYPEDEF` clause must immediately follow type-name
* [x]	`TYPEDEF` clause can only be used for level 01 entries
* [x]	Type-name can be an elementary or group item; for group-items all subordinate items of the group are part of the type declaration
* [x]	`TYPEDEF` clause cannot be specified in the same data description entry as following entries: 
  * `EXTERNAL`
  * `REDEFINES`
* [ ]	`TYPEDEF` clause can only be specified in the `WORKING-STORAGE`, `LOCAL-STORAGE`, `LINKAGE`, or `FILE` sections of a program.
* [ ]	If the `TYPEDEF` clause is specified with the `GLOBAL` clause, the scope of the `GLOBAL` clause applies to the type-name, and to any data items subordinate to the type-name. The `GLOBAL` attribute is not acquired by a data item that is defines using a global type-name within a `TYPE` clause
* [x]	Group items can be strongly or weakly typed. A typed group item is strongly typed in any of the following cases:
  *	The item is described with a `TYPE` clause that references a type declaration specifying the `STRONG` phrase.
  *	The item is subordinate to a group item described with the `TYPE` clause that references a type declaration specifying the `STRONG` phrase.
* [x]	Elementary items cannot be strongly typed.

**Comment by wiztigers** [comment]
@smedilol  should I implement rules 9,10,11, 12 from this [page](https://github.com/TypeCobolTeam/TypeCobol/wiki/Cobol02TYPEDEF). These seem to not be part of our specification ?

**Comment by smedilol** [comment]
TYPE definition must be case insensitive

**Comment by wiztigers** [comment]
Done 22d61705b00610ea50c04d63ea3aa99921ba3944 in #241.
If this ticket is only blocked by what is described in #241, please close it.

**Comment by smedilol** [comment]
This issue can't be closed: unit tests are wrong or at least not complete.

**Comment by smedilol** [comment]
What's left to do:
- create unit test for TYPEDEF and global (rule  __TCTYPE_GLOBAL_TYPEDEF__)
- fix unit test typedef: the following error is wrong:
`[1,63]<30,Error,Semantics>Semantic error: Can't write  to strongly typed variable myStrongChars:CharsStrong (use UNSAFE keyword for that) ([1>63] on line 194)`
what is expected is rule except Rule TCTYPE_LIMITED_STRONG_RECEIVER for lines 194 and 199
- except error `[1,31]<30,Error,Semantics>Semantic error: TYPE 'TypeNotDefined' is not referenced ([1>31] on line 58)`

**Comment by smedilol** [comment]
I close this issue because there is only #355 now.
