### ISSUE TITLE
TypeCobol: TYPE

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#192]
As specified on this [page](https://github.com/TypeCobolTeam/TypeCobol/wiki/Cobol02TYPE).

**Comment by wiztigers** [comment]
As its `DataType` is computed as soon as a `DataDescriptionEntry` is added to the syntax tree, a custom type referenced by a data description using the `TYPE` keyword must already have been declared using the `TYPEDEF` keyword.

We *could* remove this limitation by doing two passes: the first for adding data descriptions and custom type declarations to the symbol table, the second to compute the type of each variable.
But it's not requested, so ...

**Comment by smedilol** [comment]
Type usage must be case insensitive.

**Comment by wiztigers** [comment]
Done 22d61705b00610ea50c04d63ea3aa99921ba3944 in #241.
All tests pass, and I see no pending "new test to fix" regarding case sensitivity.
So, if this ticket is only blocked by what is described in #241, please close it.

**Comment by smedilol** [comment]
There is still Rule 11, [https://github.com/TypeCobolTeam/TypeCobol/wiki/Cobol02TYPEDEF](https://github.com/TypeCobolTeam/TypeCobol/wiki/Cobol02TYPEDEF) to implement

**Comment by smedilol** [comment]
Only #355 remains

**Comment by smedilol** [comment]
I close this issue because there is only #355 now.
