### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#193]
Allow TypeCobol.Server to run either:
 * as a server, listening to a pipe for file diffs
 * as a one-shot parser

This two features must be available through a command-line interface.

**Comment by wiztigers** [comment]
Mono.Options included as a standalone file from [here](https://github.com/mono/mono/blob/master/mcs/class/Mono.Options/Mono.Options/Options.cs).

**Comment by smedilol** [comment]
Works fine.
Can be used as a preprocessor with RDZ.
