### ISSUE TITLE
Infinite loop on COPY

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#194]
If one uses the same name as the library name in a `COPY` directive, the parser runs into an infinite loop (it always ends calling `CompilationDocument.RefreshProcessedTokensDocumentSnapshot` in a loop).

For example, writing in any program the following COBOL line will make you run into the infinite loop :
```cobol
01  YZENVIR.   COPY YZENVIR.
```

The problem doesn't seem to be directly related to the `*REMARKS` syntax, because the infinite loop happens wether or not `*REMARKS` is present.

**Comment by smedilol** [comment]
This bug doesn't happens anymore.
