### ISSUE TITLE
Completion after keyword Perform should also list available sections

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1942]
### Description
Completion after keyword `Perform` should also list sections.

**Sample**

```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       PROCEDURE DIVISION.
           Perform {cursor here}
           .
       SEC01 SECTION.
       PAR01.
           continue
           .
       END PROGRAM Pgm.
```
Asking for completion (ctrl+space) in the above sample will only list `PAR01`, when `SEC01` should also be available since it's a valid option.

**Comment by fm-117** [comment]
Removed from CobolEditor milestone as our private editor already handle the section in completion list.
Keeping the issue opened for TC LanguageServer as a stand-alone.
