### ISSUE TITLE
Incorrect completion for procedure

### ISSUE THREAD

**Issue by rooksdo** [TypeCobolTeam/TypeCobol#1954]
### Description
The completion result for a `PERFORM` instruction should list only procedures (paragraphs, sections) and not variables.

**Sample**
```cob
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 num1         pic 9(03).
       01 num2         pic 9(03).
       01 num3         pic 9(03).
       PROCEDURE DIVISION.
      *Completion lists num1, num2, num3, PAR01, PAR01 in SEC01, SEC01 and many other builtin functions
           perform {cursor here}
           GOBACK
           .
       SEC01 SECTION.
       PAR01.
           .
       END PROGRAM Pgm.
```

**Expected result**
Completion should only list procedures : PAR01 and SEC01 first and then only builtin functions

**Comment by fm-117** [comment]
Completing with numeric variables is actually correct because Cobol has the `PERFORM n TIMES` statement.
