### ISSUE TITLE
TC-style qualified name for copies

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#1971]
**Describe the bug**
The syntax `COPY library-name::text-name.` is not supported by our CUP compiler directives parser. It is implemented in the ANTLR compiler directives parser but is not present in its CUP counterpart.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *KO Syntax is not supported by Cup compiler directives parser
       COPY SYSLIB::SOMECOPY.
       PROCEDURE DIVISION.
           GOBACK
           .
       END Program Pgm.
```

**Expected behavior**
As long as the copy is present on disk, this code should compile without error.

**Comment by smedilol** [comment]
Won't do as TypeCobol is abandonned.
