### ISSUE TITLE
Handle Identifiers that look like subtractions with no space as a compiler option

### ISSUE THREAD

**Issue by alvaro-vantis-pt** [TypeCobolTeam/TypeCobol#1982]
This request is related to discussion in #65 and a TypeCobol limitation stated on https://github.com/TypeCobolTeam/TypeCobol/wiki/Limitations. IBM z/OS Compiler accepts that and I have several programs in this situations, and I can image that this is true in real world programs.

I understand the reasons, performance and clear messages on other situations, but what I´m requesting is to handle this as a specific compiler option, so it can accept this kind of identifiers only on programs compiled with this option.

This will make TypeCobol more compliance with IBM z/OS Compiler.

EDIT:
**To Reproduce**
Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPgm.
       data division.
       working-storage section.
       procedure division.
      
       REPLACE ==:-MAJ:== BY ====.
      *Ok
           PERFORM EACGAPEL-C0001:-MAJ:.

      *Ok
           perform
           300-000-PAR2
      *Ok
           perform 300-000-SEC1
           perform 300 TIMES
           perform 300-000-PAR2 THRU 300-000-SEC1
           perform 300-000-PAR2 THRU 300-000-SEC1 300 TIMES
           perform 300-000-PAR3 OF 300-000-SEC1 300 TIMES
           perform 300-000-PAR3 OF 300-000-SEC1 THRU 
                   300-000-PAR3 OF 300-000-SEC1 300 TIMES
      *Ok Number too big
           perform 300303030303030303030303030303030303030 TIMES
           goback.
           REPLACE ==:PAR1:== BY ==PAR2==.
      *Ok
      
       300-000-:PAR1:.
           exit.
      *---------------------------------------------------------------*
       EACGAPEL-C0001-TRACE.
           continue
           .
      *---------------------------------------------------------------*
       EACGAPEL-C0001.
           continue
           .
       EACGAPEL-C0002.
           continue
           .
      *Ok
       300-000-SEC1 section.
           DISPLAY "IN SECTION".
       300-000-PAR3.
           exit.
       END PROGRAM MyPgm.
```

**Outside the scope of this issue**
Paragraph and section that use only integrer literal will not be handled in this issue.
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. Pgm.
      
       PROCEDURE DIVISION.
           perform 300.
         300.
           exit.
       END PROGRAM Pgm.      
```

**Technical**
Only the scanner need to handle the detection of the correct token.
Add a CodeElementChecker to detect variable name that don't have at least an alphabetic character.

**How to test automatically**
Add new program test, but also Scanner test.

**Comment by rooksdo** [comment]
Thank you very much for your feedback @alvaro-vantis-pt.

This issue will be addressed as soon as possible

**Comment by smedilol** [comment]
@alvaro-vantis-pt after a few tests, it seems to handle almost all cases. See my update below your original post.
We are working on it, it should be delivered during May.

**Comment by alvaro-vantis-pt** [comment]
@smedilol . Thank you for the feedback. I will test it with the programs I have in this situation.
