### ISSUE TITLE
Various unexpected exceptions in RDz Plugin LSR mode

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#2009]
**Purpose**

The purpose of this issue is to track any unexpected exception (Like NullReferenceException) that can be raised while working in LSR mode with the RDz plugin.

![image](https://user-images.githubusercontent.com/19149269/126347462-f9546ca1-61e3-4d41-b44b-f90e2fefa306.png)

**Comment by fm-117** [comment]
On line https://github.com/TypeCobolTeam/TypeCobol/blob/1a4d2a4a8334cece75e995795b43160e7ddfeeaf/TypeCobol.LanguageServer/Workspace.cs#L738
the only item that could be `null` is `DiagnosticsEvent` event handler so it's easy to fix, turn the call into `DiagnosticsEvent?.Invoke(...)` just like in line 743.

**Comment by mayanje** [comment]
Fixed in  #2010
