### ISSUE TITLE
ProgramCodeElement class

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#203]
Stabilize a class representing the concept of a node of the syntax tree.
This class:
- must reuse (ie. have a reference to) the CodeElement instance
- allows tree traversal whith abstract methods like GetChildren
- must have strongly typed properties allowing access to neighbouring nodes in an explicit way
- has SymbolInformation properties of the corresponding CodeElement objects
- must have all features to represent the data (eg. code generation)

- ProgramCodeElement corresponding to data item description must offer a representation of data hierarchy (levels) independent from syntaxic hierarchy

**Comment by smedilol** [comment]
Like discussed:
The current Syntax Tree Node is not enough typed.
The AST structure must follow a Cobol program structure.
We should have:
* ProgramNode
 * IdentificationDivisionNode
 * DataDivisionNode
 * ProcedureDivisionNode
   * SectionNode
     * MoveNode
      * IfNode
        ....

We must alors separate CodeElement from Node:
Currently DataDescrptionEntry is created during syntax parsing phase but reused between different semantic parsing phases. But some of its properties (like TopLevel) are set during semantic phase.
This property must only be placed in a DataDescriptionEntryNode.

**Comment by smedilol** [comment]
I'll create a new issue about the need for a more typed AST.
This issue can be close as our current AST is sufficient for Version 1.0
