### ISSUE TITLE
Diagnostics created on CodeElement during Node phase

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#2037]
**Describe the bug**
During the Node phase (not incremental), diagnostics MUST be created only on node objects because code elements are built incrementally.

**Bug example**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL06.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 A PIC 9.
       PROCEDURE DIVISION.
              IF (A = 0) THEN
              DISPLAY "0"
           END-IF
           GOBACK
           .
       END PROGRAM TCOMFL06.
```

1. The `IF` is not correctly aligned so during first Node phase, a diagnostic will be created on the `END-IF` code element.
2. Remove the spaces before `IF` so as to align the statement correctly with its `END-IF`
3. The diagnostics is still there, because the `END-IF` CodeElement has not been recreated and still holds the diagnostic from previous parsing round

**Expected behavior**
No diagnostic after the second Node phase.

**Technical**
Check usages of `DiagnosticsUtils.AddError` overloads accepting a `CodeElement` as first argument. Those methods must not be used in any phase taking place after CE building. As time of writing, the invalid usages are:
1. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/Diagnostics/CrossChecker.cs#L1138
2. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/Diagnostics/CrossChecker.cs#L144
3. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/CupParser/NodeBuilder/ProgramClassBuilder.cs#L813
  a. TC only, looks like it should be removed...
4. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/Diagnostics/CrossChecker.cs#L1113
5. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/Diagnostics/CrossChecker.cs#L535
6. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/Diagnostics/CrossChecker.cs#L556
7. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/Diagnostics/CrossChecker.cs#L757
8. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs#L640
9. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs#L659
10. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/Diagnostics/TypeCobolChecker.cs#L677
11. https://github.com/TypeCobolTeam/TypeCobol/blob/f294bd6a0d933f2daf8ff7145685abb36da24f0b/TypeCobol/Compiler/Diagnostics/Cobol2002Checker.cs#L129

For each of these usages, we must determine if it's truly a Node phase check or a misplaced CodeElement check. Solutions are:
- move to CodeElement phase (if the check does not require any structural information available only after Node phase)
- apply diagnostic on Node intead of CodeElement

**Comment by smedilol** [comment]
It must be the third that we have these problem.
We should add a control to prevent this from happening.
Proposals:
- Do a simple check like: compare number of diagnostics on CodeElement before and after Node phase
- See if the visibility `DiagnosticsUtils.AddError` for CodeElement can be reduced so only class related to CodeElement can use it
