### ISSUE TITLE
RDz files parsing

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#205]
Some files created by RDz are not properly supported by parser CLI.

**BLOCKS #193**

**Comment by wiztigers** [comment]
I just tested it with sample files from RDz ; it seems to have been fixed by acc2e8106b8c40765961c614976356570db533c3 for #212.
**TODO:** test it irl

**Comment by smedilol** [comment]
Tested several times.
It works fine now.
