### ISSUE TITLE
Replace with line break doesn't works

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2062]
**Describe the bug**
Spaces around separators in replace are removed. This also includes line breaks.
Currently this works fine with spaces but not line breaks.

**To Reproduce**
Cobol code that cause the bug :
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  W-IdcStr PIC 9(02) value 1.
           REPLACE ==:BlocJL1 :== BY ==30==
           ==:BlocJL2                   :== BY ==30==
           ==:BlocJL3
                   :== BY ==30==.
      
       01 W-Tab.
         10 W-COD1   PIC X          OCCURS :BlocJL1:.
         10 W-COD2   PIC X          OCCURS :BlocJL2:.
         10 W-COD3   PIC X          OCCURS :BlocJL3:.
       01 Var1 pic X.
      
       PROCEDURE DIVISION.
           MOVE W-COD1(W-IdcStr) TO Var1
           MOVE W-COD2(W-IdcStr) TO Var1
           MOVE W-COD3(W-IdcStr) TO Var1
           .
       END PROGRAM MyPGM.
```

IBM Cobol compiler will apply the replace like this:
```cobol
       01  W-Tab.
         10 W-COD1   PIC X          OCCURS 30.
         10 W-COD2   PIC X          OCCURS 30.
         10 W-COD3   PIC X          OCCURS 30.
```

**Expected behavior**
No error

**Comment by fm-117** [comment]
Ok this one is a bit silly... In the example, it would work fine if line 9 were a continuation line. So it seems IBM compiler allows this despite the missing continuation line indicator.

Considering the method `CobolTextLines.ComputeLineTypeFromIndicator`:

https://github.com/TypeCobolTeam/TypeCobol/blob/b71bca340f6dc4ab276df8e3a20a13594689af35/TypeCobol/Compiler/Text/CobolTextLine.cs#L405-L438

A working hack would be to add this case at the end:

```csharp
//Hack
else if (Type == CobolTextLineType.Source && SourceText.TrimStart().StartsWith(":" + TokenUtils.GetDisplayNameForTokenType(TokenType.PseudoTextDelimiter)))
{
    Type = CobolTextLineType.Continuation;
}
```
