### ISSUE TITLE
Allow replace text-word with any character.

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2066]
**Describe the bug**
Bug: A text that is the target of a replace cannot contains invalid character in its context.
It means, you cannot write invalid text and expect the replace to fix it.
This is because our replace is done after we scan the token of the source code.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM
       DATA DIVISION.
       Working-storage section.
       REPLACE ==/PAIBRGA-NB-MAX/== BY ==300==
               ==_PAIBRGA-NB-MAX_== BY ==300==.
      
       01  W-TAB.
      *No error expected
           05 W-TAB1 OCCURS /PAIBRGA-NB-MAX/.
             10 W-COD      PIC X(002).
      
      *No error expected
           05 W-TAB1 OCCURS _PAIBRGA-NB-MAX_.
             10 W-COD      PIC X(002).
      
      
      *Replace will not match because / is not a separator for partial
      *cobol word 
       01 W-Var/PAIBRGA-NB-MAX/ pic X.
      *It workds because character _ is allowed in variable name but
      *the replace will not takes place here
       01 W-Var_PAIBRGA-NB-MAX_ pic X.
       
       END PROGRAM DVZF0OSM.
```

**Technical**
Maybe we should wait to implement #1693 to review all the replace scanner/replace mechanisms.

**Comment by fm-117** [comment]
With this updated sample (without '@' char), it works on `2212-bug-in-replacereplacing-directives-with-multiple-operations`. I've added the corresponding test. Note that while the diagnotics are correct, the AST is broken and SYM comparator does not work.

**Comment by smedilol** [comment]
Ok, the broken AST was expected because the replace doesn't works for:
```cobol
       01 W-Var/PAIBRGA-NB-MAX/ pic X.
      *It workds because character _ is allowed in variable name but
      *the replace will not takes place here
       01 W-Var_PAIBRGA-NB-MAX_ pic X.
```
