### ISSUE TITLE
LSP Allow RefreshNodes Without Missing Copy Notification

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#2070]
**Description**
Missing Copy Notification can lead to recursive Missing Copy Notification when a refresh nodes notification is requested by the client, for instance after a Refresh All Copy actions and there still unresolved copy.
So the strategy to avoid such situation is to refresh node without sending again a Missing Copy Notification to the client.

**Comment by fm-117** [comment]
Isn't that a clienr preoccupation ? I don't see anything wrong with sending a MissingCopyNotification at the end of the RefreshNodes process.

**Comment by mayanje** [comment]
The fact here is that the client notifies the server that it has finished to load missing copies, when the server received the notification it reparses opened document, thus in this specific case the server should not send again a missing copy notification, because we can enter in an infinite loop of notifications.

**Comment by fm-117** [comment]
Yes I've understood where the loop comes from, no need to repeat.

In my opinion the server should continue sending a MissingCopyNotification after a node refresh but the client should not send any notification after loading copies. Copy loading is a client-side process only. Depending on whether the client succeeded or not to load all the copies, it could ask (so it is a request not a notification) the server for a node refresh. I personally think that the MissingCopyNotification is one-way only from server to client.

**Comment by mayanje** [comment]
It cannot be a request, a request is a blocking operation until the server responds to the request.
NodeRefreshParams is a notifiation, if so we should add a new options to this notification to not resend MissingCopyNotification

**Comment by mayanje** [comment]
As suggested by fm-117 the fix is client side not server side, the client should not send back a notification if none of requested copy is resolved.

**Comment by fm-117** [comment]
But we still need to remove the code MissingCopyNotification from client to server, so after the client has been updated we'll have to change the server.
