### ISSUE TITLE
TypeCobol: TYPEDEF DATE

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#209]
As specified on this [page](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolDate).

**Comment by wiztigers** [comment]
@smedilol asked me if it was possible to call this type `DATE`.

Well ... You have to make `UserDefinedWord | DATE` exceptions in multiple places of the grammar file. You have to propagate these multiple exceptions in C# factories. You propagate COBOL's legacy to make your grammar a mess instead of abstracting concepts.
--> IMO, more pain that it's worth it

So I'd rather not do it ¯\_(ツ)_/¯

**Comment by smedilol** [comment]
Type TC-Date should be named "date".
I know, "date" is a keyword in Cobol but it's more user/developer friendly.

**Comment by wiztigers** [comment]
Type Date is now loaded by default.
All tests pass, and I see no pending "new test to fix" regarding type Date.
So, if this ticket is not blocked by anything else, please close it or create a more specific issue.
