### ISSUE TITLE
Allow Language Server to use a CompilationProject instance associated to a set FileCompiler instances

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#2116]
**Purporse**

The Language Server uses a single CompilationProject instance for all FileCompiler instances created. The Goal of this issue is associate a CompilationProject instance to a set FileCompiler instances belonging to the same Project's key.
This depending on a Configuration Change notificaton that associates a Project key to  a document URIs.
The idea is to let the client decide (thru a notification) to which projet belongs an opened document.

**Comment by smedilol** [comment]
See new issue #2151
