### ISSUE TITLE
NullReferenceException in SymbolTable.GetParagraph / CodeElementFinder

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2125]
**Describe the bug**

Following code produces 2 exception:
![image](https://user-images.githubusercontent.com/13764482/151790434-c8b14108-13d9-4c33-b802-7573703f2c0a.png)
![image](https://user-images.githubusercontent.com/13764482/151790462-63c29ad9-fbbb-4803-bc2b-21335a8035e6.png)

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       PROCEDURE DIVISION
                          .
       PARA0.
           IF  OK
              SEARCH ALL MyArray 
      
              END-SEARCH
           END-IF
      
           PERFORM PARA1
      
           .
       PARA1.
      
           .
      
       END PROGRAM ABIT0013.
```

Expected (Type)Cobol code : 
No error.

**Comment by fm-117** [comment]
As for the error in LanguageServer, it happens on this line:

https://github.com/TypeCobolTeam/TypeCobol/blob/3280145ebccdf21a6c9aaeb7a9d3e6279fe876d7/TypeCobol.LanguageServer/TypeCobolServer.cs#L113

`ProgramClassDocumentSnapshot` is null.
