### ISSUE TITLE
Subscripting and qualified names

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#213]
**CHILD OF #201**
**FOLLOWS #116, #196**
**DUPLICATES #220** (kind of)

Implementation of COBOL subscripting is today not appropriated anymore to the table of symbols : qualified names don't support subscripting.
In addition to that, the new `::` operator grammar rules are not consistent with legacy qualified names grammar rules : the concept of subscripting is included in the qualified name rule, whereas the legacy way handle this separately.

Once analysis about how data must be reprensented is done, there is much reimplementation work to be tackled, in particular in `SyntaxElementBuilder` factories. Points of interest are marked with `TODO: subscripting` comments.

**Comment by wiztigers** [comment]
4506797122b96e022ec8a354df69bc999270e629 shows how the way factory work is not really adapted to `::` grammar rules anymore

**Comment by smedilol** [comment]
The new branch merge#249 changed a few things for QualifiedName. We need to test the branch completely.
As of operator ::, this issue will be continued in issue #201.
