### ISSUE TITLE
Codegen: too long whitespace line after generated REMARKS

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#2133]
**Describe the bug**
The generated fragment for REMARKS directive may be followed by a whitespace line that exceeds 80 characters and no error is reported.

**To Reproduce**
The bug is already covered by the `RemarksLess` codegen test.
See https://github.com/TypeCobolTeam/TypeCobol/blob/develop/Codegen/test/resources/input/TypeCobol/Remarks/RemarksLess.rdz.cbl (input) and https://github.com/TypeCobolTeam/TypeCobol/blob/develop/Codegen/test/resources/output/TypeCobol/Remarks/RemarksLess.rdz.cbl (output). The line 7 is made of 112 space characters.

**Expected behavior**
Generated code lines should never exceed 80 characters.

**Comment by smedilol** [comment]
Won't fix as TypeCobol language is not supported anymore.
