### ISSUE TITLE
Integrate the "select-clause" star syntax

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#2137]
### Description

The purpose of this issue, is to integrate into the parser, the **"select-clause" star** syntax described like that, using ANTLR notation

SELECT (ALL|DISTINCT) ? STAR
with
 STAR = *

The integration must:
- Adapt the SqlScanner to recognize SQL Tokens of the syntax (SELECT, ALL, ...)  and *
- In the file CobolWords.g4 add the following declaration
   - star: MultiplyOperator;
- In the file CobolCodeElements.g4 add at the following declaration
   - selectStatement:   fullselect;
   - fullselect: subselect;
   - subselect: selectClause;
   - selectClause: SELECT (ALL|DISTINCT) ? star;
   - add selectClause item in rule codeElement:
- In classes of namespace SqlCodeElements add support for the selectStatement CodeElement 
- Add a CUP Node syntax: selectStatement ::=  SelectStatement;
  - attached to sqlStatement definition
  - In classes of the namespace SqlNodes  add support for the subSelect Node

**Comment by smedilol** [comment]
@mayanje What do you mean by `Star will be a single CodeElement from ANTLR CobolWords resulting on the * (STAR) token`?
`SELECT` will be a CodeElement and `* token` will be another CodeElement ?

**Comment by mayanje** [comment]
@smedilol Please let's talk about that in the meeting.

**Comment by fm-117** [comment]
Done with #2164.
