### ISSUE TITLE
InvalidOperationException with debug mode and "picX"

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2140]
**Describe the bug**
An invalid data declaration which contains `picX` and with debugging mode active generate an exception.

**To Reproduce**
Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-370
                        WITH DEBUGGING MODE
                        .
       data division.
       working-storage section.
       01 debugVar picX.
       END PROGRAM MyPGM.
      
```
Exception on line that use invalid `picX` declaration.
```
Runtime error: System.InvalidOperationException: La séquence ne contient aucun élément.
   à System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   à TypeCobol.Compiler.CodeElements.CodeElement.<get_DebugMode>g__ComputeDebugMode|5_0()
   à TypeCobol.Compiler.CodeElements.CodeElement.get_DebugMode()
   à TypeCobol.Compiler.Diagnostics.CodeElementChecker.OnCodeElement(CodeElement codeElement, Boolean isDebuggingModeEnabled)
   à TypeCobol.Compiler.Parser.CodeElementBuilder.ExitCodeElement(CodeElementContext context)
   à TypeCobol.Compiler.Parser.Generated.CodeElementsParser.CodeElementContext.ExitRule(IParseTreeListener listener)
   à Antlr4.Runtime.Tree.ParseTreeWalker.ExitRule(IParseTreeListener listener, IRuleNode r)
   à Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   à TypeCobol.Compiler.Parser.CodeElementsParserStep.ParseProcessedTokensLinesChanges(ProcessedTokensDocument processedTokensDocument, IList`1 processedTokensLinesChanges, PrepareDocumentLineForUpdate prepareDocumentLineForUpdate, TypeCobolOptions compilerOptions, PerfStatsForParserInvocation perfStatsForParserInvocation)
```

Without debugging mode active, there is no Exception.

**Expected behavior**
No exception. Same behavior than without debugging mode.

**Comment by fm-117** [comment]
The exception happens here:

https://github.com/TypeCobolTeam/TypeCobol/blob/e4eb6f4dbd4f9e95f8292cefc07f942e968a84a2/TypeCobol/Compiler/CodeElements/CodeElement.cs#L48-L54

On an invalid CodeElement like `01 debugVar picX.`, it appears that the parser does not capture any consumed tokens so the `ConsumedTokens` collection is empty and the call to LINQ `First()` fails. In debug mode (meaning running in debug with VS not Cobol debug mode), the `Assert` fails prior to calling `First()`.

To solve this, we can either:
- replace the assertion with an actual `if` and decide that when no tokens have been consumed for a CE, its DebugMode is `None`,
- or check why we don't consume any token in this case.

The second solution is better but trickier as this is related to ANTLR behavior and therefore will concern the whole parser (depending on the actual modifications).
I think we can go with the first simple solution, as `DebugMode` is currently only used to create a diagnostic on CE having mixed content (mix of debug and non-debug lines). So we may end up with a wrong value for `DebugMode` but the CE being invalid, the parser will still issue at least one diagnostic on it and the user will have to correct the syntax first.

**Comment by smedilol** [comment]
I agree to go with the first solution, as the second will require a lot of time and there is no guarantee that new grammar rules respect this behavior.
