### ISSUE TITLE
LSP Server Introduce Workspace Project

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#2151]
Purporse

The Language Server uses a single CompilationProject instance for all FileCompiler instances created. The Goal of this issue is associate a CompilationProject instance to a set FileCompiler instances belonging to the same Project's key.
This depending on a Configuration Change notificaton that associates a Project key to a document URIs.
The idea is to let the client decide (thru a notification) to which projet belongs an opened document.

- a new open document notification (not LSP-compliant) including the project key and the associated copy folders

- a project configuration change containing the project key and the updated copy folders

**Comment by fm-117** [comment]
During our meeting, we discussed about 2 notifications:
- a new open document notification (not LSP-compliant) including the project key and the associated copy folders
- a project configuration change containing the project key and the updated copy folders

Is it still what is planned ?

**Comment by mayanje** [comment]
yes
