### ISSUE TITLE
Allow TypeCobol to be built by AppVeyor

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#217]
The current appveyor build fail.
Fix this!

**Comment by wiztigers** [comment]
As it failed miserably, I've removed the vscodeclient subproject from AppVeyor's custom solution file and fixed some subprojects line that weren't up-to-date anymore. 'Should build fine, now.

However, it seems our project is not built automatically by AppVeyor, as @smedilol and @vavans each of your configurations last build dates back many months ago.

I've no access to your individual setups.
Shouldn't we create an AppVeyor account dedicated to TypeCobolTeam, and properly setup the commit hook there ?

**Comment by smedilol** [comment]
Seems ok on master. I'll wait one day to see if builds are scheduled correctly.
Then I'll push commit 85b208a234500eeb397332f03955fcbb1c97e891 to branch merge#249

**Comment by wiztigers** [comment]
Badges in project main page (ie. README file) as long as in wiki welcome page now point to the TypeCobol project linked to a specific TypeCobolTeam account.
Commit hooks run with each commit on `master`, because our AppVeyor is setup to only build `master` branch.
