### ISSUE TITLE
New LSP notification refresh one COPY

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2184]
**Is your feature request related to a problem? Please describe.**
Provide a new LSP notification to refresh only one COPY.
This new notification is also here to optimize the refresh mechanism from LSP (`TypeCobol.LanguageServer.Workspace#ScheduleRefresh`)
Instead of calling `Workspace#ScheduleRefresh`, a new method must be created.

This new method will 
- [ ] Remove only the COPY to refresh from the cache.
- [ ] Refresh only document(s) that use this copy
- [ ] Optimize re-parsing mechanism #2159
   - Not sure if this issue will provide a significative gain as the slower step of the parser is CodeElement.
   - #2159 can also apply to `TypeCobol.LanguageServer.Workspace#ScheduleRefresh`

**Technical**
Notif parameters:
- COPY to refresh
- projectKey

How to do the refresh of one copy:
- Remove only the COPY (+ its variants) to refresh from the cache.
   - Create a new class for COPY cache.
      - Move method `ClearImportedCompilationDocumentsCache` into this class.
      - Create a new method to remove only one COPY (+its variants) from the cache.
      - Think about variant. See `cacheKey` in `CompilationProject#Import`
      - Caller of `ClearImportedCompilationDocumentsCache` will now access the copy cache from `CompilationProject`.
- Refresh only document(s) that use this copy
   - In `Workspace` (or `WorkspaceProjectStore` I didn't check #2158), iterate over all documents and use `CompilationUnit.CopyTextNamesVariations` to detect these cases.

**How to test ?**
LanguageServerRobot is not able to create a change in a COPY while the test is running as the content of the COPY is not managed by LSP messages.
So what to do:
1. Keep LSR running between 2 tests.
   - Create a first test to parse a source
   - Update the COPY file locally
   - Play another test which send `refresh single copy` notif.
2. Create a manual dedicated test without LanguageServerRobot ?
3. Extend LanguageServerRobot to be able to insert local script between LSP messages?
   - This local script will change the content of the COPY before the new refresh notification will be sent

The test can use 2 copys:
- Parse the document with these 2 copys.
- Change the 2 copy locally.
- Send refresh single copy notification for only 1 of the 2 copy.
- Reparse the document.
- Check that the document use the new version of the refresed copy but not the other one.

**Comment by fm-117** [comment]
Before changing the code, i'd like to discuss about what has to be done for the 'ScheduleRefresh' mechanism.

In #2158, we have 4 usages of ScheduleRefresh, and here we'll introduce a new one for the RefreshSingleCopy notification.
So let's list all of theses cases and review what should be done:

1- CopyWatcher
  - Using the data from the change event, find the copy that has been externally updated
  - Go to case 5: RefreshSingleCopy

2- DependenciesWatcher
  - As we don't have a simple way to find which program use which dependency, keep refreshing all opened files
    - no need to clear copy caches

3- UpdateMissingCopies
  - when there is no FileWatcher
    - find the project associated to the file
    - clear cache of the project
    - refresh concerned file

4- ProjectConfigurationChange / Configure
  - Refresh all files of the project
  - Depending whether the CompilationProject is fully recreated or not and whether the copy folders have been changed, clear the project copy cache

5- RefreshSingleCopy
  - Using TextNamesVariations, find which programs are concerned by the change
  - Evict from caches the copy (it may be in multiple caches)
  - Refresh all programs identified

We need a Refresh method for a single program and a list to avoid multiple refresh over the same program.

**Comment by smedilol** [comment]
Ok for [didChangeWatchedFiles](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWatchedFiles) notification. 
We can use an URI like "projectKey/copyName" to know which project to update.
And an URI like "$all/copyName" or "copyName" to specify that all projects must be updated.
