### ISSUE TITLE
Data POSITION and SIZE

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#219]
- each `DataDeclaration` must have a `position` and a `physical size`
  - the `physical size` of an elementary item is given by the PICTURE clause
  - the `position` is the sum of the `physical size`s of all data declared before
- a group item also have a size and a position
  - the `physical size` of a group item is the sum of all its children
  - the `position` is the sum of the `physical size`s of all data declared before
- an array `phsyical size` is equal to its `length` times its `physical size`
- the `position` of the first data of a program is **1**

**Comment by wiztigers** [comment]
**TODO:** diagnostics when
- name error on `REDEFINES` clause
- warning when redefining a larger area
- warning (error?) when redefining a smaller area

**Comment by smedilol** [comment]
@maxime645 I've updated the goal of this issue. As discussed, there is only physical size (no logical size anymore).
Tell me if it's not clear.
