### ISSUE TITLE
SQL TRUNCATE

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#2195]
**Description**

Integrate the [TRUNCATE](https://www.ibm.com/docs/en/db2-for-zos/12?topic=statements-truncate) Sql statement in the parser.

This implies:
- Ensure that all Keywords are recognized by the sql scanner
- To write the ANTLR grammar
- To write the CUP grammar
- Building the Truncate Statement CodeElement
- Building the Truncate Node
- Creating the corresponding Sql Object
   - Each options of the statement must be a boolean property (ex: IsDropStorage, IsReuseStorage; IsIgnoreDeleteTriggers, ...)
   - Each token that the form the Truncate statement must be stored in the SqlObject.
   - The _table name_ must be a StorageArea that holds  a SymbolReference
- Making corresponding CodeElement, Node and SqlObject classes visitable
- Write test unit

**Comment by fm-117** [comment]
`STORAGE`, `REUSE`, `IGNORE` and `TRIGGERS` are not reserved words.
