### ISSUE TITLE
SQL LOCK TABLE

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#2196]
**Description**

Integrate the [LOCK TABLE](https://www.ibm.com/docs/en/db2-for-zos/12?topic=statements-lock-table) Sql statement in the parser.

This implies:

- Ensure that all Keywords are recognized by the sql scanner
- To write the ANTLR grammar
- To write the CUP grammar
- Building the LockTable Statement CodeElement
- Building the LockTable Node
- Creating the corresponding Sql Object
   - Each options of the statement must be a property (ex: Partition, IsShare,...)
   - Each token that the form the LockTable statement must be stored in the SqlObject.
   - The _table name_ must be a StorageArea that holds  a SymbolReference
- Making corresponding CodeElement, Node and SqlObject classes visitable
- Write test unit

Prerequisites:
by #2183 the _integer_ constant is produced by the scanner.

**Comment by fm-117** [comment]
`SHARE`, `EXCLUSIVE` and `MODE` are contextual keywords.

**Comment by fm-117** [comment]
- no need for an `SqlObject`

We should end up with something like:

```csharp
public enum LockMode
{
    Shared,
    Exclusive
}

public class LockTableStatement : SqlStatementElement
{
    public TableViewCorrelationName Table { get; }

    public SqlConstant PartitionId { get; }

    public SyntaxProperty<LockMode> Mode { get; }
}
```

And for the ANTLR part (contextual keywwords are omitted):

```
lockTableStatement: LOCK TABLE tableOrViewOrCorrelationName (PARTITION IntegerLiteral)? IN (share | exclusive) mode;
```
