### ISSUE TITLE
Unexpected literal token type: NULLS 

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#2198]
**Description**

L'exception suivante est envoyé:

à TypeCobol.Compiler.CodeElements.NullPointerValue.get_Value() 
 à TypeCobol.Compiler.CodeElements.ConditionOperand.CheckEquivalence(Expression other) 
 à Qualis.CobolAnalyzers.ExpressionUtils.AreIsomorphic(Expression expA, Expression expB) 
 à Qualis.CobolAnalyzers.RuleSystem.RuleChecker.ASTRules.IdenticalBinaryOperationForbidden.CreateViolationIfIsomorphic(Expression expression1, Expression expression2, Expression root) 
 à Qualis.CobolAnalyzers.RuleSystem.RuleChecker.ASTRules.IdenticalBinaryOperationForbidden.CheckIsomorphism(Expression root) 
 à Qualis.CobolAnalyzers.RuleSystem.RuleChecker.ASTRules.IdenticalBinaryOperationForbidden.CheckLogicalChains(Expression root, Stack`1 logicalStack, Boolean insideCurrentLogicalChain) 
 à Qualis.CobolAnalyzers.RuleSystem.RuleChecker.ASTRules.IdenticalBinaryOperationForbidden.DoCheck(Expression expression) 
 à Qualis.CobolAnalyzers.RuleSystem.RuleChecker.AbstractRuleChecker`1.Check(T item)

**Comment by fm-117** [comment]
The `NullPointerValue` class does not seem to support the `NULLS` literal. Just add it in the switch and we should be good.
