### ISSUE TITLE
`OCCURS` clause

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#221]
`OCCURS` clause must be implemented for `DataDeclarationEntry`.
This allows to declare arrays in COBOL.

Each array must have:
- a boolean `isArray`
- a `length` which can :
  - either be an integer (fixed-length array)
  - or point to another variable (variable-length array)

**note:** although it seems to be represented the same way in memory, a data that is not an array does not have the same behaviour as an array of size 1: in particular, you cannot use indexing with the former, and you must use indexing with the latter.

**Comment by smedilol** [comment]
You can also have array with a variable length.
The length can depend on the value of another variable.

**Comment by wiztigers** [comment]
Good catch, @smedilol 
Would have done us no good to forgot this. (^_^; )

**Comment by smedilol** [comment]
Occurs is now implemented.
