### ISSUE TITLE
Context-sensitive words

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#224]
**FOLLOWS #191**

> **8.10 Context-sensitive words**
> The following are context-sensitive words and are reserved in the specified language construct or context. If a context-sensitive word is used where the context-sensitive word is permitted in the general format, the word is treated as a keyword; otherwise it is treated as a user-defined word
> -- ISO/IEC 1989:2014 (E), p170

Follow 3 pages of context-sensitive keywords.
Among them one can find `STRONG`, which is a keyword only inside a `TYPEDEF` clause.

In our current implementation, we don't have such a thing. In particular, once you set your input format to at least COBOL 2002, you cannot have variables called "strong" anymore, whereas it is permitted in COBOL 85 (but then you cannot use the `TYPEDEF` clause).

We could do better by customizing the method `TokenUtils.GetTokenTypeFromTokenString`.
This would allow us rather easily to change the keywords set according to other known information.
However, this method currently only used in the scanner phase, which (correct me if I'm wrong) is too early to know about rule contexts or clauses.

The goal of this issue is to debate about:
- the necessity for us to implement context-sensitive words
- how we'd do it

**Comment by wiztigers** [comment]
@laurentprudhon @osmedile @vavans @mayanje , thanks in advance for your feedback (´∀｀)♡

**Comment by fm-117** [comment]
Fixed with children issues, see PR #1968, #1970, #1972 and #1976.
