### ISSUE TITLE
DROP Table

### ISSUE THREAD

**Issue by laabidiHend** [TypeCobolTeam/TypeCobol#2244]
Description

The [Drop Table](https://www.ibm.com/docs/en/db2-for-zos/12?topic=statements-drop)  statement removes a Table at the current server.

This implies:
- To write the ANTLR grammar
- To write the CUP grammar
- Building the Drop Table Statement CodeElement
- Building the  Drop Table  Node
- Creating the corresponding Sql Object
- Making corresponding CodeElement, Node and SqlObject classes visitable
- Write test unit

**Comment by laabidiHend** [comment]
```csharp

public class DropTableStatement : sqlStatementElement 
{
		public TableViewCorrelationName TableName;
		public SqlColumnName AliasName ;
		
		public DropTableStatement(TableViewCorrelationName tableName, SqlColumnName aliasName)
		{
                           TableName = tableName;
		           AliasName = aliasName;
		}
}

```
And for the ANTLR part :

```
dropTableStatement: SQL_DROP SQL_TABLE ((tableName = tableOrViewOrCorrelationName) | (aliasName = new_column_name))

```

**Comment by fm-117** [comment]
Several problems in your proposed solution:
- we do not use public fields and certainly not read-write fields
  - replace with readonly properties
- alias-name and table-name are mutually exclusive so it is misleading to have a constructor requiring both
  - better create 2 constructor, one for each case
- why use `SqlColumnName` to modelize an alias ? We don't have any alias concept for now but it certainly isn't a colum name
  - replace with UserDefinedWord in grammar and use SymbolReference in object
