### ISSUE TITLE
Data with the same name

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#225]
Is the following declaration allowed?
```cobol
01  grp.
  05  a PIC X.
    10  a PIC X.
```
If so, what must be the compiler reaction to the following name qualifications?
```cobol
MOVE SPACES TO a
MOVE SPACES TO a      OF grp
MOVE SPACES TO a OF a
MOVE SPACES TO a OF a OF grp
```

**Comment by wiztigers** [comment]
```cobol
           MOVE SPACES TO A
IGYPS0037-S "A" was not a uniquely defined name.
            The definition to be used could not be determined from the context.
            The reference to the name was discarded.

           MOVE SPACES TO  A OF GRP
IGYPS0037-S "A OF GRP" was not a uniquely defined name.
            The definition to be used could not be determined from the context.
            The reference to the name was discarded.
                                                                                
           MOVE SPACES TO A OF A OF GRP

           MOVE SPACES TO A OF A
```

`05 a` can thus be declared but not qualified.

**Comment by wiztigers** [comment]
I don't know what to do with this issue.
`::` operator should allow to qualify `05 a`, but its specification is unfinished, so ... what I'm gonna do? (•ิ_•ิ)?

**Comment by smedilol** [comment]
I propose to close this issue: Cobol 85 allow you to declare 2 data with the same name, but at least one direct or indirect parent must have a different name.
all statements that reference variable must ensure that their variables have no ambiguities.


Specifications for operator "::" will be put into a new issue.

**Comment by wiztigers** [comment]
I agree.
`::` specification is currently too much vague for my implementation needs.
