### ISSUE TITLE
LSP : CopyFolders of default configuration must also be used for file opened in a project

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2295]
**Describe the bug**
With LSP:
When you open a source that references a default copy (like SQLCA), then this default COPY is not found if the source is open with notification "typecobol/workspace/didOpenProjectTextDocument".

**To Reproduce**
Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       program-id. MyPGM.
       data division.
       working-storage section.
           EXEC SQL
                INCLUDE SQLCA
           END-EXEC.
       end program MyPGM.
```

**Expected behavior**
No error, the default copy must be found.

**Technical**
In `WorkspaceProject.Configure`, we need to add all `Workspace.Configuration.CopyFolders` if they are not present yet in the specified new `copyFolders` parameter.

**How to test automatically**
Can be done with LSR tests as we reference copy ?
Otherwise it will be a manual tests on our editor side.

**Comment by fm-117** [comment]
Fixed by #2296.
