### ISSUE TITLE
LSP : Completion after When

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2297]
**What is the current problem**
Manage completion after `When` under an `evaluate` statement.

Cobol code to illustrate.
```cobol
       IDENTIFICATION DIVISION.
       program-id. MyPGM.
       data division.
       working-storage section.
       01 Var1 pic X.
       01 Group1.
          05 Group1-Var1 pic X.
          05 Group1-Var2 pic X.
      
       procedure division.
           evaluate true
      *       Completion must return all variables     
              when 
              
      *       Completion must return all variables that start with "Gr"
              when Gr
      
           .
       end program MyPGM.
```

**Technical**
In `CompletionElligibleTokens.elligibleCompletionTokens`, add `new Tuple<TokenType, bool>(TokenType.WHEN, false)`.
=> Maybe not useful.

#### Problem with CodeElement of When statement
ProgramClassBuilder.NodeCodeElementLinkers doesn't contains the real CodeElement of the When statement.
See ProgramClassBuilder.StartWhenConditionClause where we create another CodeElement.

Solutions:
1. Merge WhenSearchCondition and WhenCondition into a single CodeElement class ?
2. Manually link the real CodeElement with the Node. So for a When Node, we'll have:
```
     NodeCodeElementLinkers.Add(fakeCodeElementofTypeWhenCondition, WhenNode);
     NodeCodeElementLinkers.Add(realCodeElementofTypeWhenSearchCondition, WhenNode);
```

#### Add default completion ?
Add a default completion in `TypeCobolServer.OnCompletion`, in the `default` case of `switch (lastSignificantToken.TokenType)` ?
```C#
                        default:
                        {
                            items.AddRange(CompletionFactory.GetCompletionForVariable(docContext.FileCompiler, matchingCodeElement,
                                da =>
                                    da.Name.StartsWith(userFilterText, StringComparison.OrdinalIgnoreCase)));
                        }
                            break;
```
=> Maybe not useful.

**How to test automatically**
LSR Test.

**Comment by fm-117** [comment]
See also #2106 and #2147.

I'm not sure I understand, is there 3 distinct solutions ?
1. merging the two CE
2. altering the NodeCodeElementLinker
3. adding a default completion accounting for the input text

First seems complicated as the 2 distinct whens are here because of ANTLR.

Between 2 and 3, 3 seems the most beneficial as  it could help for other scenarios.
