### ISSUE TITLE
DataDescriptionEntry checking during semantic phases

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#230]
#Currently DataDescriptionEntry are checked during syntax phase and semantic phases.
During syntax phase, all checks are done in Listener (DataDescriptionChecker).
But during semantic phase, there is no specific listerner related to a creation of a DataDescriptionEntry tree.
I see 3 solutions:
* ProgramListener which is used during semantic phase could be called when entering working, local and linkage section.
* We can add a listener not called by Antlr but by our ProgramClassBuilder when a DataDescriptionEntry tree is created.
* We can change the semantic grammar (CobolProgramClass.g4) to regroup DataDescriptionEntry by level 01 / 77 / 66. Then Antlr will provide corresponding listerner.

@wiztigers, What do you think?

**Comment by wiztigers** [comment]
The `CodeElementBuilder` class is called by ANTLR. Its job is to turn ANTLR contexts containing `Tokens` into `CodeElements`. When a `CodeElement` is created, `CodeElementBuilder` notifies `CodeElementListeners` through a `CodeElementDispatcher`.
The `ProgramClassBuilder` class is called by ANTLR. Its job is to turn ANTLR contexts containing `CodeElements` into `Nodes`. Thus, when a `Node` is created, `ProgramClassBuilder` should notify `NodeListeners` through a `NodeDispatcher`. This corresponds to your second solution.

**Comment by wiztigers** [comment]
Today, all should be available to create a DataDescriptionEntry listener and throw away `AddError` statements from `ProgramClassBuilder` into their own Checker(s).

**Comment by wiztigers** [comment]
done.
just implement `NodeListener` interface. every `NodeListener` will be called by the dispatcher each time a `Node` is exited.
