### ISSUE TITLE
Usage of a badly declared TYPE doesn't generate error or warning.

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#231]
**WAIT FOR ISSUE #418**

if you have the following:

``` Cobol
01 MyType TYPEDEF STRONG EXTERNAL.
    05 aaa pic X.

01 MyVar TYPE MyType.
```

Here `MyType` is invalid because a strong type can't be external. But `MyType` will still be added to the SymbolTable during semantic phase.
I think `MyVar`declaration should generate an error because `MyType` can't be used.
An error not a warning, because it must prevent Cobol generation.

**Comment by wiztigers** [comment]
My opinion is that, at the moment, we shouldn't mark as invalid each usage of something that has an invalid declaration. This would be a costly trend to follow, and I'll try to explain why.

For example, in the case you describe, `MyType` type definition will be marked with a diagnostic telling the writer about the incompatibility of `EXTERNAL` clause. It is, IMO, counter-productive to create many diagnostics with a vague error message like "hey, you've got a problem in your declaration !". What would be better would be to propagate the declaration error message to the line using the improperly-declared stuff. But, for this to be NOT confusing, this usage error would have to hold a clear reference to the declaration error and allow to "jump to definition", so the writer doesn't loose time either analyzing the wrong area of code or searching for the definition. All this heavily depends of the IDE used, and is clearly a GUI-dependent issue. However, we don't even have our "own" GUI yet.
Of course, this GUI will need an appropriate way of linking the line of usage to the declaration error, and this is clearly the parser's job. However, will you spend dev time now to prepare something you can't specify until we're clear about what our Editor will look like ?

Thus, I suggest you close this issue and create less specific one like "Create an usage error at each usage of an improperly declared symbol, and allow to jump from usage error to declaration error with a click" ... once we have begun to work on a specific editor ...

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
