### ISSUE TITLE
Test : Compare Cobol 85 source file with its generated code

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#234]
Compare Cobol 85 source file with its generated code. Files must be identical.

**Comment by wiztigers** [comment]
You can activate comparison between input source file and output generated file by setting `codegen = true`(default) in *GrammarTest.cs*.
@smedilol please confirm this fulfills your need

**Comment by wiztigers** [comment]
Done and used for #243, so please close this. ヾ(＾∇＾)

**Comment by smedilol** [comment]
I finally took the time to test Codegen.
Current comparison between expected generated source code and actual one is working but not precise enough.
For example, if 1 line is missing in the actual source code, all following lines will be listed in the diff.
I think we need a proper Diff API for this task.

**Comment by wiztigers** [comment]
Personally I don't have this as a "need". I leave it to you it would be "nice to have", indeed.
I've created an enhancement issue with a lower priority.

**SPAWNED #327**
