### ISSUE TITLE
Invalid Picture when using spaces

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#2359]
**Describe the bug**
Picture character string is not correctly parsed when it contains spaces.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL06.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 TITI PIC X (20).
       PROCEDURE DIVISION.
           GOBACK
           .
       END PROGRAM TCOMFL06.
```
This will translate into a `PIC X` (equivalent to `X(1)`) instead of `PIC X(20)` !

**Expected behavior**
Correct interpretation of tokens.

**Technical**
Scanner is wrong ? TokenType `PictureCharacterString` is heresy ?

**How to test automatically**
TODO

**Comment by smedilol** [comment]
This syntax won't compile, so our behavior is ok.
IBM compiler will create error `"("was invalid.  Scanning was resumed at the next area"A"item, level-number, or the start of the next clause.`
