### ISSUE TITLE
PreprocessorStep navigate through document lines in reverse order

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2373]
**Describe the bug**
In `TypeCobol.Compiler.Preprocessor.PreprocessorStep.CheckIfAdjacentLinesNeedRefresh`, see
```C#
            // Navigate forwards to the end of the multiline compiler directive 
            if (lineIndex < (documentLines.Count - 1))
            {
                int nextLineIndex = lineIndex;
                IEnumerator<ProcessedTokensLine> enumerator = documentLines.GetEnumerator(nextLineIndex + 1, true);
```
The `true` parameter in `GetEnumerator` is used to incidate that the enumerator must be in reverse order which contradicts the goal to navigate forwards to the end.

Fix : Change this `false`.

**Technical**
Will be edited by a team member.
Implementation details with the chosen solution.

**How to test automatically**
Will be edited by a team member.
Only if our current automated tests doesn't handle this.

**Comment by fm-117** [comment]
Changing from `true` to `false` does not break any test. We need a test:
- incremental
- where edit takes place inside a multiline compiler directiv

**Comment by fm-117** [comment]
Using this code, removing the `DISPLAY var2` line and checking the code elements or node should do the trick.

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL06.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 var1 pic x.
       01 var2 pic x.
       01 var3 pic x.
       PROCEDURE DIVISION.
       REPLACE ==:debug-code:== BY ==
           DISPLAY var1
           DISPLAY var2
           DISPLAY var3
           ==.
           :debug-code:
           GOBACK
           .
       END PROGRAM TCOMFL06.
```
