### ISSUE TITLE
Replace : comma is allowed to separate replace clause

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2374]
**Describe the bug**
Comma is allowed to separate replace clause

**To Reproduce**
Cobol code that cause the bug :
```cobol
  REPLACE                        
     ==:NbrMaxCpy:== BY ==50==,  
     ==:NbrMaxCpyCol:== BY ==25==
     .                           
```

TODO check other symbols allowed.

**Expected behavior**
No error.

**Technical**
Will be edited by a team member.
Implementation details with the chosen solution.

**How to test automatically**
Will be edited by a team member.
Only if our current automated tests doesn't handle this.

**Comment by fm-117** [comment]
See also if it is allowed in `REPLACING` clause.
