### ISSUE TITLE
Debug lines after Replace off are scanned even if debugging mode is off

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2381]
**Describe the bug**
Debug lines after Replace off are scanned even if debugging mode is off

**To Reproduce**
Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       REPLACE OFF.
       procedure division.
      D move a to b
           goback.
       END PROGRAM MyPGM.
```
This code will produce errors:
`Semantic error: Symbol a is not referenced`
`Semantic error: Symbol b is not referenced`

**Expected behavior**
Debug lines are never scanned if debugging mode is off.

**Technical**
Bug should be located in Scanner.

**How to test automatically**
Will be edited by a team member.
Only if our current automated tests doesn't handle this.

**Comment by fm-117** [comment]
ScanState is wrong when reaching the debug instruction. `ScanState.InsideReplaceDirective` is true and therefore the scanner will interpret the move instruction as source code instead of comment.
