### ISSUE TITLE
Exception in CrossChecker 'An item with the same key has already been added'

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#2393]
**Describe the bug**
An exception is thrown when a table declaring duplicate keys is used in a binary search.

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID.  Pgm.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01.
        02 DSRCE-TAB  OCCURS 83
                      ASCENDING KEY IS  DSRCE-KEY-A
                      DESCENDING KEY IS DSRCE-KEY-A
                      INDEXED BY Idx, Idx2.
            05 DSRCE-KEY-A           Pic 99.
            05 DSRCE-KEY-D           Pic 99.
            05 DSRCE-SRCE-VAL        Pic S9(3).
      
       01 WS-KEY                     Pic 99.
       01 WS-KEY2                    Pic 99.
       01 WS-SRCE-VAL                Pic S9(3).
       01 I                          Pic 99.
      
       PROCEDURE DIVISION.
      
           SEARCH ALL DSRCE-TAB
              AT END
                 DISPLAY 'VALUE NOT FOUND'
      *  Ok
              WHEN DSRCE-KEY-A (Idx) = WS-KEY
                 DISPLAY 'VALUE FOUND'
           END-SEARCH

           GOBACK
           .
      
       END PROGRAM Pgm.
```

**Expected behavior**
No exception and correct diagnostics.

**Technical**
Check this part:

https://github.com/TypeCobolTeam/TypeCobol/blob/00daee94f7a65d1dfdc37822d5cf0fac2979e5d0/TypeCobol/Compiler/Diagnostics/CrossChecker.cs#L372-L378

The `usedKeys` should either support duplicate entries (multimap ?) or discard duplicates when populating the dictionary.

**How to test automatically**
Standard parsing tests

**Comment by smedilol** [comment]
I suggest to keep only unique key in `usedKeys` as this is used only to check that all keys ared used.
And add new diagnostic when a duplicate keys is detected.
