### ISSUE TITLE
Case insensitive names

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#241]
Symbol names are case insensitive in COBOL and TypeCobol.
Make sure type and function names are detected whatever their case.

**Comment by wiztigers** [comment]
This seems to have been fixed by 22d61705b00610ea50c04d63ea3aa99921ba3944.
Is there a case we forgot? It doesn't seem so, as all tests pass.
Please confirm and, if so, close this issue.

**Comment by smedilol** [comment]
tests are ok
