### ISSUE TITLE
Invalid AST with empty AT END

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2434]
**Describe the bug**
Following #2185 there is one case where we produce an Invalid AST: when there is an empty `AT END`.

**To Reproduce**
Load the following code into our custom IDZ plugin.
I guess a direct full parsing of the code must also trigger the bug.
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MyPGM.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 Group1.
           05 Array1 OCCURS 60 TIMES
                              INDEXED BY MyIndex.
             10 Array1-Elt1             PIC X(03).

       PROCEDURE DIVISION.
           SEARCH Array1 VARYING MyIndex
           at end


           END-SEARCH
           .

       MyParagraph.
           display "Foo"

           .
       END PROGRAM MyPGM.
```

**Expected behavior**
No bug/correct AST : `MyParagraph` must be attached to `procedure division`.

**Technical**
Will be edited by a team member.
Implementation details with the chosen solution.

**How to test automatically**
Create standard test for direct parsing.
Or an incremental test if a direct parsing doesn't reproduce the bug.

**Comment by fm-117** [comment]
This can be fixed by allowing empty `onAtEnd` in CUP grammar:

https://github.com/TypeCobolTeam/TypeCobol/blob/5edb126826a03f8c3d356660ba1567e4db5037a2/TypeCobol/Compiler/CupParser/TypeCobolProgram.cup#L1649-L1651

We'll need to ensure that a diagnostic is still created to signal the invalid construct.
