### ISSUE TITLE
InvalidCastException SentenceEnd to ProgramEnd

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2441]
**Describe the bug**
With parser 1.5.26:
 à TypeCobol.Compiler.Diagnostics.CrossCompleteChecker.CheckEndProgram(Program node)
   à TypeCobol.Compiler.Diagnostics.CrossCompleteChecker.Visit(Program program)
   à TypeCobol.Compiler.CodeModel.SourceProgram.VisitNode(IASTVisitor astVisitor)
   à TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)
   à TypeCobol.Compiler.Nodes.Node.VisitChildrens(IASTVisitor astVisitor, Boolean continueVisit, IEnumerable`1 childrenNodes)
   à TypeCobol.Compiler.Nodes.Node.AcceptASTVisitor(IASTVisitor astVisitor)
   à TypeCobol.Compiler.Parser.ProgramClassParserStep.CrossCheckPrograms(SourceFile root, TemporarySemanticDocument temporarySemanticDocument, TypeCobolOptions compilerOptions)
   à TypeCobol.Compiler.CompilationUnit.RefreshProgramClassDocumentSnapshot()
   à TypeCobol.LanguageServer.Workspace.<RefreshSyntaxTree>g__RefreshNodes|100_0(<>c__DisplayClass100_0& )
   à TypeCobol.LanguageServer.Workspace.RefreshSyntaxTree(FileCompiler fileCompiler, SyntaxTreeRefreshLevel refreshLevel)
   à TypeCobol.LanguageServer.Workspace.<>c__DisplayClass98_0.<TimerEvent>g__Refresh|0()
   à TypeCobol.LanguageServer.TypeCobolServerHost.MessageHandler(IMessageHandler messageHandler, TypeCobolServer typeCobolServer)

**To Reproduce**
Shortest code that I found to trigger the bug.

```cobol
       IDENTIFICATION division.
       PROGRAM-ID. MyPGM.
       data division.
       working-storage section.
       01  MyArray.
          05 TAB-EXC-ELE occurs 1 to 50
                          indexed by TAB-EXC-IDX.
             10 TAB-EXC-CLE   pic X(08).

       procedure division.
           perform varying TAB-EXC-IDX from 1 by 1
                   until   TAB-EXC-IDX > 50

                    TODO : case1.
                    TODO : case2.
           end-perform
           .
       end program MyPGM.
```

**Expected behavior**
No InvalidCastException 

**Technical**
Will be edited by a team member.
Implementation details with the chosen solution.

**How to test automatically**
Will be edited by a team member.
Only if our current automated tests doesn't handle this.

**Comment by fm-117** [comment]
This bug has been introduced by #2436. 😞

The `InvalidCastException` can also happen on other end-elements like `IfStatementEnd` for example.

**Comment by smedilol** [comment]
See #2451 to review error recovery in CUP
