### ISSUE TITLE
Functions declaration

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#245]
Implement suntax to declare functions as described [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax).
In the context of this issue, as multi-output procedures are a generic case of single-output functions, procedures and functions should be implemented ATST.

**Comment by wiztigers** [comment]
Here are the rules about TypeCobol custom procedures and functions, as long as where they are implemented:

* [x] __TCRFUN_DECLARATION_AS_NESTED_PROGRAM__ *TypeCobolProgram.g4*
* [x] __TCRFUN_FIXED_FORMAT__ Scanner takes care of it.
* [x] __TCRFUN_NO_DEFAULT_ACCESS_MODIFIER__ *TypeCobolCodeElements.g4*
* [ ] __TCRFUN_NO_SECTION_OR_PARAGRAPH_IN_LIBRARY__ *TODO*
* [ ] __TCRFUN_DOTS__ *TODO*
* [ ] __TCRFUN_NO_CALL_TO_ENCLOSING_PROGRAM__ *TODO*
* [ ] __TCRFUN_PARAMETER_DECLARATION_ORDER__ *TODO*
* [ ] __TCRFUN_PARAMETER_DESCRIPTION__ *TODO*
* [ ] __TCRFUN_0_TO_N_PARAMETERS__ *TODO*
* [ ] __TCRFUN_NO_INOUT_OR_OUTPUT_FOR_FUNCTIONS__ *TODO*
* [ ] __TCRFUN_0_TO_1_RETURNING_PARAMETER__ *TODO*
* [ ] __TCRFUN_NO_RETURNING_FOR_PROCEDURES__ *TODO*
* [ ] __TCRFUN_NO_COPY_IN_PARAMETERS__ *TODO*
* [ ] __TCRFUN_LEVEL_88_PARAMETERS__ *TODO*

For the exact implementation location(s), `grep` the rule name in the source code.

**Comment by smedilol** [comment]
Issue #339 cancelled so this one can be closed.
