### ISSUE TITLE
Fix bugs found with generator AddEmptyLineInTheMiddleThenRemove

### ISSUE THREAD

**Issue by fm-117** [TypeCobolTeam/TypeCobol#2456]
Child of #2364.

Fix anomalies found when using `AddEmptyLineInTheMiddleThenRemove` on all files in `TypeCobol.Test\Parser\Programs`

**Comment by fm-117** [comment]
Here are the 12 tests created from failing programs with this generator (after applying fix from #2459).
And the diff with what is currently produced by our parser

[AddEmptyLineInTheMiddleThenRemove.zip](https://github.com/TypeCobolTeam/TypeCobol/files/10816277/AddEmptyLineInTheMiddleThenRemove.zip)
[FailingTests.#2456.diff.txt](https://github.com/TypeCobolTeam/TypeCobol/files/10816278/FailingTests.2456.diff.txt)

There are 3 categories of differences
- code element duplication
- missing diagnostics
- new or altered diagnostics

**Comment by fm-117** [comment]
With this fix, we have only 4 remaing failing tests.
[FixDuplicateCodeElement.#2456.diff.txt](https://github.com/TypeCobolTeam/TypeCobol/files/10824747/FixDuplicateCodeElement.2456.diff.txt)

**Comment by fm-117** [comment]
'Fix' for InitializeStatement test
[InitializeStatement_AlteredDiagMessage.#2456.diff.txt](https://github.com/TypeCobolTeam/TypeCobol/files/10825555/InitializeStatement_AlteredDiagMessage.2456.diff.txt)

**Comment by fm-117** [comment]
Details on the 3 remaining tests:

## CopyReplace4Colon
TODO
## DebugLinesWithDebugging
TODO
## InitialValuesContinuations
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL01.
       data division.
       working-storage section.
       01 var1 PIC X(120) VALUE "start1
      -    "end1".
       01 var2 PIC X(120) VALUE 'start2
      *comment
      -    'end2'.
       01 var3 PIC X(120) VALUE "start3
      
      -    "end3".
       01 var4 PIC X(120) VALUE 'start4
      -
      -    'end4'.
       01 var5 PIC X(120) VALUE "start5
      -    "extension
      -    "end5".
       procedure division.
           display var1
           display var2
           display var3
           display var4
           display var5
           goback
           .
       end program TCOMFL01.
```
Adding a blank line after `01 var4 PIC X(120) VALUE 'start4` breaks the scanner. The continued token `start4                                 end4` is not correctly reparsed and we end up with an invalid token stream. The problem is located in the scanner when building the continuation group to rescan. See https://github.com/TypeCobolTeam/TypeCobol/blob/72b357bbbaf18be512499c46c6c118d6238cdfda/TypeCobol/Compiler/Scanner/ScannerStep.cs#L229 and the rest of the algorithm.

**Comment by smedilol** [comment]
For `CopyReplace4Colon` the bug also happens when each Replace are written on a single line.
