### ISSUE TITLE
Encoding problem in generated code

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#246]
When using the preprocessor to convert a TypeCobol file edited with RDZ to a Cobol 85 one, the generated doesn't handle special characters correctly:
`Test é è à ù`
is generated into:
`Test Ã© Ã¨ Ã  Ã¹`

It happens either with or without the parameter "-e rdz"

**Comment by wiztigers** [comment]
Did you test since 96f244cd6cc30ccbbdbeb06d5381cde758a567fb ?
Before this version, there was an error in the encoding used by the test engine to read the output file, but AFAIK the output format is good.

With which editor do you open the generated file? RDz ?

**Comment by smedilol** [comment]
yes my version is up to date.
I use RDZ and notepad++, the problem is present with both editors.

**Comment by wiztigers** [comment]
Strange ... it happens despite of the fact that I use same `Encoding` for writing the output file as the one I get from the input file `DocumentFormat` ... 
Gotta have a second look ... :eyeglasses:

**Comment by smedilol** [comment]
This issue will be delegated to TypeCobolOffshore
