### ISSUE TITLE
Stop correctly incremental reparsing if a COPY contains a Replace

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#2472]
**What is the current problem**
Two problems here related to copies containing REPLACE directive(s).

- Unoptimized CodeElementsParserStep
  - When looking for next REPLACE directive (in order to define end of reparse section), the current code does not account for directives coming from copies, so the reparse section may be larger than it needs to.
- Bug when including a COPY containing a REPLACE
  - When including a COPY in an incremental change, if the COPY contains a REPLACE, the parsr won't apply the directive because the reparse section will end prematurely.

**Describe the solution you'd like**
`CodeElementsParserStep` should consider imported documents when looking for next REPLACE directive.

**Technical**
The `lookForNextReplaceDirective` mechanism must be updated. To determine whether a COPY contains a REPLACE or not, use the new property `ActiveReplaceDirective`. This would work only for already imported copies becausse the property itself is set by `CodeElementsParserStep`.

**How to test automatically**
Use incremental testing.

**Comment by fm-117** [comment]
Although #2476 fixes the optimization problem, it is not complete as it does not handle `REPLACE OFF` correctly and also does not work right away when a new COPY containing `REPLACE` is included.

Another way to solve this would be to detect `REPLACE` directives on-the-fly in `TokensLinesTokenStream`:
- stop at `StopToken` when no `REPLACE` is encountered
- if a `REPLACE` is found, stop at next `REPLACE`. Resume if StopToken has not yet been found
- a `REPLACE OFF` deactivates the 'look for next REPLACE' behavior
