### ISSUE TITLE
Have RETURN-CODE as an intrinsic variable

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#250]
Variable RETURN-CODE must be known by default. Its definition is:
01 RETURN-CODE GLOBAL PICTURE S9999 USAGE BINARY VALUE 0.

**Comment by smedilol** [comment]
Our intrinsic file in CLI interface doesn't seems to register intrinsic variables.
It works fine for TYPEDEF.

**Comment by wiztigers** [comment]
That'd be easy to do.
However, I won't do it until the specification of all the **TCRFUN_EXPECTED_RETURNS_xxx** rules from the [Functions & Procedure syntax specification page](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax) are not finalized.
Until then, adding more default scope variables is just creating clutter.

**Comment by smedilol** [comment]
Following 8edbc611d7605742711bd0867193e7ee1a22d61d RETURN-CODE is now a special register variable
