### ISSUE TITLE
spaces around `::` operator

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#251]
**CHILD ISSUE OF #201**

Currently, `::` operator is defined in _TypeCobolCodeElements_ grammar  as:
`ColonSeparator ColonSeparator`

As at least one blank must be between each token, this prevents writing `x::y::z` as a qualified name, forcing to write `x :: y :: z` (with spaces before and after `::`) instead.

Furthermore, as `::` is not a single token, `:y:` in `x::y::z` could have the nasty effect of being substituted by the preprocessor as `x:something:y` which makes no sense.

**Comment by laurentprudhon** [comment]
Here is a suggested fix : 
1. Add a new value to the enumeration TokenType : QualifiedNameSeparator. Update TokenFamily and TokenUtils, anbd CobolBase grammar accordingly.
2. Update Scanner.cs line 652 : 
if(currentIndex <= lastIndex && line[currentIndex + 1] == ':')
{
   // consume both :: chars
   currentIndex += 2;
   return new Token(TokenType.QualifiedNameSeparator, startIndex, startIndex + 1, tokensLine);
 }
3. Update TypeCobolCodeElements grammar and replace ColonSeparator ColonSeparator by QualifiedNameSeparator.

**Comment by wiztigers** [comment]
well ... it seems that, after merging #249, you can now write `x::y ::z` and it will be parsed without error and recognized as `x.y.z`/`z OF y OF x`.

@laurentprudhon did you do anything regarding this issue in your majestic pull request ?
It seems at least step **2.** is done in `Scanner.CheckForPartialCobolWordPattern` (ll1993-1997).
So I guess what remains to do is steps **1.** and **3.** to get a more digest grammar ...

As I just noticed this while doing something else (#306), I'll mark this issue as **To Test** further.

**Comment by smedilol** [comment]
Everything seems to works fine according to our unit tests
