### ISSUE TITLE
Procedure declaration

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#252]
Implement syntax to declare procedure as described [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax)

**Comment by wiztigers** [comment]
**DUPLICATES #245**

**Comment by wiztigers** [comment]
Shouldn't we close this ?
It really seems to me to be a duplicate of #245 ...

**Comment by smedilol** [comment]
Yep okay.
I'm updating the wiki with the last specs. A new issue is coming !
