### ISSUE TITLE
Statement: PERFORM

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#26]
Implement PERFORM statement (4 formats).

**Comment by wiztigers** [comment]
shows an issue about the grammar as written p388.
Is phrase2 mandatory in PERFORM..VARYING ?
Spec says it is, but tests are written as it was not !

I'm waiting for some COBOL expert position to settle this issue. Thanks in advance !

**Comment by wiztigers** [comment]
By comparing with "real" code, it really seems phrase2 is NOT mandatory.
66f711ff93a7670c13c5d98c667fccf0231b1b44 I modified the grammar according to "real" COBOL code.

**Comment by wiztigers** [comment]
![SPEC GAP!](http://png-2.findicons.com/files/icons/1014/ivista/128/warning.png "SPEC GAP!")
p387 of the spec, there is *NO WAY* to write PERFORM .. UNTIL without tossing in a THRU. Either you write "PERFORM *procedure_1* THROUGH *procedure_N* UNTIL *condition*", or you write "PERFORM UNTIL *condition* *imperative_statements*".
However, real code contradicts this.

c4e437d73bc586c417220c46a0dd986d5b4662ab I modified the grammar according to "real" COBOL code.

**Comment by wiztigers** [comment]
PerformStatement should implement FlowControl as was done for IfStatement in 02982b7219923bd41a5bcda248ccd80ae66e52b3.

**Comment by osmedile** [comment]
perform until p387:
Yes it's allowed to write:
`perform procedure-name-1 UNTIL condition-1`
So specs must be wrong.

**Comment by osmedile** [comment]
perform varying p388:
phrase 2 is optionnal, it's allowed to write
`perform procedure-name-1 varying identifier-2 from identifier-3 BY identifier-4 UNTIL condition-1`

**Comment by wiztigers** [comment]
TODO:
split PERFORM into two s

**Comment by smedilol** [comment]
Is there still a problem with PERFORM?

**Comment by wiztigers** [comment]
It's not as much a problem as a "work in progress" situation.
I'm currently building the syntax tree during the semantic analysis phase (in `ProgramClassBuilder`), and the `PERFORM` statement (as long as the other flow control statements such as `IF` or `EVALUATE`) must have a correct and tested node construction before our work on these last statements can be considered done.
