### ISSUE TITLE
node.SymbolTable can ben null when parsing nested programs since this commit.

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#262]
Following d7713df630a43e281dda8a1b8f692cda667a50d5
node.SymbolTable can ben null when parsing nested programs since this commit.
This can currently only be tested with our private programs sample.
I will put a dedicated test in TypeCobol.Test

**Comment by smedilol** [comment]
Mode details:
Line 65 in `ProgramClassbuilder`:
`node.SymboleTable` can be null when called from `Enter(CurrentProgram.SyntaxTree.Root, context);` for a nested program (called from line 104 of `ProgramClassbuilder`)

**Comment by smedilol** [comment]
@wiztigers can you take a look?
I put tests to reproduce ths bug inside `NewTestsToFix/HighPriority`

**Comment by wiztigers** [comment]
no problem.
I'll take a look once I'm done with #249
