### ISSUE TITLE
END PROGRAM <nothing?>.

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#263]
**CHILD OF #243**

Our specification, _IBM Entreprise COBOL 5.1 for zOS - Language Reference_, p53, says that ending a program with its explicit name is mandatory (except for the outermost program, and then only in some specific cases).
So, our grammar says THIS:
```cobol
END PROGRAM program-name.
```
... with _program-name_ being mandatory.

But @smedilol , in unit test file _InnerPgmWithEvaluate.cbl_ (since 96af68fdcdc52adc005a21037e34cc0259268c42) has asked me to allow THIS:
```cobol
END PROGRAM.
```

**Comment by wiztigers** [comment]
I've allowed writing `END PROGRAM.` with no _program-name_, as I assume it's IBM 5.1 compiler's behaviour.
@smedilol, please confirm the grammar change then close this issue.

**Comment by smedilol** [comment]
The *program-name* is mandatory in the `END PROGRAM` statement
The *program-name* must match `PROGRAM-ID. ` in `ID DIVISION`

**Comment by smedilol** [comment]
Test is now:
C:\Users\SMEDILOL\workspaces\TypeCobol\TypeCobol.Test\Compiler\Parser\Samples\Programs\NestedImplicit.cbl
