### ISSUE TITLE
Adjust FILLER should take in account OCCURS

### ISSUE THREAD

**Issue by efr15** [TypeCobolTeam/TypeCobol#2648]
**Describe the bug**
When a REDEFINES has an OCCURS clause the adjusted size for FILLER is not correct

**To Reproduce**
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL06.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 group1.
          05 target-zone PIC X(1000).
          05 redef  REDEFINES target-zone OCCURS 10.
             10 var PIC X(20).
       PROCEDURE DIVISION.
            GOBACK
            .
       END PROGRAM TCOMFL06.
```
When applying the refactoring on this document, FILLER is inserted with size = **800**.

**Expected behavior**
Size should be **80**
Warning: a FILLER can also have an OCCURS clause

**Technical**
`AdjustFillerVisitor `should consider possible OCCURS when determining the adjusted size.

**How to test automatically**
LSR tests.

**Comment by fm-117** [comment]
`OCCURS` on `REDEFINES` is forbidden. IBM compiler returns `An"OCCURS"clause was found in the definition of a level-1 item.  The"OCCURS"clause was discarded.` however our parser does not have this check (yet).

**Comment by fm-117** [comment]
My bad the error is caused by the level of the OCCURS but OCCURS on REDEFINES of level > 1 seems to be allowed. Reopening and changing the source.
