### ISSUE TITLE
Ambiguity with level-01 item.

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#266]
**SPAWN OF #261**

Consider the following TypeCobol function declaration:
```cobol
DECLARE FUNCTION ReturnZ PRIVATE.
         DATA DIVISION.
         LINKAGE SECTION.
           01 a PIC 9(04).
             05 x PIC 9(04).
             05 z PIC 9(04).
         PROCEDURE DIVISION
             INPUT z PIC 9(04).
             RETURNING result PIC 9(04)
         .
           MOVE 0 TO result.
           ADD z to result.
       END-DECLARE.
```
It is valid regarding **TCRFUN_DECLARATION_LEVEL_01**, as there is no level-01 item called either `z` or `result`.

It will be generated to COBOL 85 as the following (nested) program.
```cobol
       PROGRAM-ID. ReturnZ.                              
         DATA DIVISION.
         LINKAGE SECTION.
           01 a PIC 9(04).
             05 x PIC 9(04).
             05 z PIC 9(04).
           01 result PIC 9(04).
           01 z PIC 9(04).                                                    
         PROCEDURE DIVISION                                                   
             USING BY REFERENCE z                                             
             RETURNING result                                                 
         .                                                                    
           MOVE 0 TO result.
           ADD z to result.
       END PROGRAM ReturnZ.  
```

Isn't the use of `z` in `ADD z to result.` ambiguous ?
Shouldn't we forbid _all_  items inside linkage section with the same name as a parameter of the function, _whether their level_ ?

**Comment by smedilol** [comment]
Even in TypeCobol, there is an ambiguity between `z` Inside linkage section and `z` as an input parameter.
So I propose to change the rule *TCRFUN_DECLARATION_LEVEL_01* to:
*TCRFUN_DECLARATION_NO_DUPLICATE_NAME* data inside linkage section cannot have the same name as a parameter declared as INPUT, OUTPUT, INOUT or RETURNING. This applies to all level of data declared Inside linkage section.
