### ISSUE TITLE
Codegen: debug lines

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#267]
Debug lines from the TypeCobol file must be copied in the COBOL 85 file.

**Comment by wiztigers** [comment]
Done.
However, debug lines are copied "AS IS" in COBOL85.
It means that, in the current state Parser (which does not part debug lines at all), debug lines containing invalid COBOL won't provoke any error.

**Comment by smedilol** [comment]
Ok thx.
This is acceptable for our first release (version 1).
I'll create an issue to handle debug lines correctly in the future.
