### ISSUE TITLE
Codegen: COPY

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#268]
COPY statements from the TypeCobol file must be copied in the COBOL 85 file.

**Comment by wiztigers** [comment]
The way this issue was fixed in a0ee0cfb13a096364200c49373291f33b422693a does NOT solve all ways of writing COPY directives. Please test.

**Comment by smedilol** [comment]
It's ok with our current parser implementation.
We need a CopyNode to fully manipulate COPY directive during codegen -> #368
