### ISSUE TITLE
Conditional Expressions

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#27]
Widely used everywhere in the grammar, conditional expressions must be properly parsed.

**Comment by wiztigers** [comment]
AS of today, some abbreviated conditional expression remain yet unimplemented.
Hey, me! Go fix this already! shoo!

**Comment by wiztigers** [comment]
Everything works excepted abbreviated relation conditions : these are incorrectly built.
They are so thorny ༶ඬ༝ඬ༶ they deserve their own issue: #151

**Comment by wiztigers** [comment]
Logical expressions were commented as part of #178.
They have to be re-enabled, including abbreviated conditional expressions.

**Comment by wiztigers** [comment]
**BLOCKED BY #151**

**Comment by wiztigers** [comment]
Should be taken care of during integration of PR #249.

**Comment by smedilol** [comment]
To test with branche merge#249

**Comment by wiztigers** [comment]
**BLOCKED BY #289**

**Comment by wiztigers** [comment]
Conditional expressions are properly parsed in our unit tests as long as in our production sample.
We don't exactly know if abbreviated relation conditions are largely used, so these ones could use some more unit tests, due to their complexity. However, they have their own issue.

**SPAWN #151**
