### ISSUE TITLE
<function-name>-RESULT

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#274]
For function invocations, the codegen always generates in the corresponding generated `CALL` statement the same return value holder variable for a given function call : **<function-name>-RESULT**.
Two problem with this variable:
* If the function does not return anything, this variable should not be generated.
* If this variable is needed, it should be created in the current scope `LOCAL STORAGE`.

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
