### ISSUE TITLE
Functions declaration: codegen

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#278]
These rules apply to any TypeCobol program containing at least one `PUBLIC` function declaration.
In the following rules, such a program will be called a library.
- [x] **TCRFUN_CODEGEN_POINTER_ARRAY**  
  An array of pointers to COBOL programs corresponding to TypeCobol functions must be generated in `WORKING-STORAGE SECTION`. There must be two items in this array for each declared `PUBLIC` function : a unique `PIC X(08)` hash and a function pointer.
- [x] **TCRFUN_CODEGEN_REDEFINED_ARRAY**  
  A `REDEFINES` of the pointer array must be generated in `WORKING-STORAGE SECTION`.
- [x] **TCRFUN_CODEGEN_IS_LOADED**  
  A condition item for whether or not the pointer array is loaded must be generated in `WORKING-STORAGE SECTION`.
- [x] **TCRFUN_CODEGEN_LIBRARY_COPY**  
  A copy directive using the copy name defined by **TCRFUN_LIBRARY_COPY** must be generated in `LINKAGE SECTION`.
- [x] **TCRFUN_CODEGEN_CALL_DATA**  
  An item allowing the library to figure which way it is called (either from a TypeCobol function call or a COBOL `COPY` directive) must be generated in `LINKAGE SECTION`.
- [x] **TCRFUN_CODEGEN_CALLS_ARRAY**  
  An array containing all functions used by the caller (either from the current library or from others) must be generated in `LINKAGE SECTION`.
- [x] **TCRFUN_CODEGEN_PROCEDURE_DIVISION**  
  `PROCEDURE DIVISION` is modified by the addition of the `USING CallData` directive.  
  `CallData` let the library know if it is called either TypeCobol-style or via a COPY directive.
- [x] **TCRFUN_CODEGEN_ADAPTABLE_BEHAVIOUR**  
  If the library is called from a TypeCobol function call, the `FctList-Process-Mode` paragraph must be performed. If the library is called from a `COPY` directive, the `Copy-Process-Mode` paragraph must be performed.  
  This conditional behaviour is implemented using `CallData` and must be generated at the beginning of the `PROCEDURE DIVISION`.
- [x] **TCRFUN_CODEGEN_TYPECOBOL_BEHAVIOUR**  
  The `FctList-Process-Mode` paragraph must be generated in the `PROCEDURE DIVISION`.
- [x] **TCRFUN_CODEGEN_COPY_BEHAVIOUR**  
  The `Copy-Process-Mode` paragraph must be generated in the `PROCEDURE DIVISION`.

**Comment by smedilol** [comment]
Following last evening meeting, the current solution with a generic function name and a pointer in a COPY is not the best one.
We can find something better.
For the moment, this issue can be delayed.

**Comment by wiztigers** [comment]
What's the matter?
Can you expand a bit on what are the shortcomings of generating a `SET <function-name> TO <generic-label>` statement for each declared function ?

Can one say that the current implementation "_works, but can be improved_", or it is that it "_doesn't work at all, must be redone_" ?

**Comment by smedilol** [comment]
@reydelpa Patrick can you update the wiki page:
https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsCodegen
with the last specs.

**Comment by wiztigers** [comment]
* [ ] TCRFUN_CODEGEN_IS_LOADED
* [ ] TCRFUN_CODEGEN_POINTER_ARRAY
* [ ] TCRFUN_CODEGEN_REDEFINED_POINTER_ARRAY

**Comment by wiztigers** [comment]
All current function declaration codegen rules are now implemented.
