### ISSUE TITLE
Statement: SEARCH

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#28]
Implement SEARCH statement (2 formats).

**Comment by wiztigers** [comment]
```cobol
SEARCH something
WHEN   condition1
WHEN   condition2
    CONTINUE
END-SEARCH
```
Writing n subsequent `WHEN` clauses in `SEARCH` statement is explicitely forbidden by the specification (_see grammar_ **p408** _for proof_). So the above snippet should be illegal.

However, writing n subsequent `WHEN` is allowed by `EVALUATE`.

So, what should I do ?

**Comment by delmasgu** [comment]
That's correct.

With EVALUATE statement you can have subsequent WHEN but with SEARCH statement you will have following error message (tested with IBM Enterprise COBOL for z/OS  4.2.0) .

IGYPS2079-S_ Expected a verb or "NEXT SENTENCE", but found "WHEN".  The statement was
            discarded.

**Comment by wiztigers** [comment]
Okay, so no grammar change, then.
Thanks @delmasgu .
