### ISSUE TITLE
Increase parser robustness

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#288]
On some input file which contain COBOL errors (for example simple things like forgotten dots, forgotten statement end keywords, and so on) we encounter harsh runtime exceptions like null pointer errrors or cast errors. This breaks the program, we are unable to continue parsing untill end of file, unable to dump any diagnostics and the user (which we can name for example @reydelpa ヾ(-‿-; )) is left clueless with no indication about what is happening.

How could we protect our program by making it able to restart on this kind of error ?
At best, we need something like protecting each `EnterXXX(XXXContext...)` method with its own `try ... catch ...`, create at this place an object like `CodeElementInError` or `NodeInError` which would contain the source code interval causing problem, and a diagnostic message containing the runtime exception.

However, wouldn't this systematic and generic `try ... catch ...` heavily impact performance ?
@laurentprudhon @osmedile @mayanje  @KOBISCAL , any opinions ?

**Comment by smedilol** [comment]
According to:
http://stackoverflow.com/questions/52312/what-is-the-real-overhead-of-try-catch-in-c
http://stackoverflow.com/questions/1308432/do-try-catch-blocks-hurt-performance-when-exceptions-are-not-thrown
The real cost is to throw an exception. having try/catch in your code doesn't seems to have a real impact in performance.

As Antlr already throw an exception, I'd say that you can catch it in order to improve robustness of the parser.

**Comment by wiztigers** [comment]
Code parsed by our parser is intrinsically wrong the majority of the time.
A lifetime wouldn't suffice to test _all_ that can be wrong in _all_ TypeCobol or COBOL programs. Altough our unit tests try to reach this goal, they won't cover _all_ edge cases until faaar in the future.
Until know, our `CodeElement`/`Node` factory methods can theorically break anytime because of a thrown runtime exception (null pointer access error, cast error and so on).

That's why, after discussing with @smedilol and @laurentprudhon , we deemed a `try ... catch ...` to ultimately be necessary, even if we work at increasing our behaviour consistency through efforts like the one discribed in #294.

**Comment by wiztigers** [comment]
This [sample file](https://raw.githubusercontent.com/TypeCobolTeam/TypeCobol/cb8f870fb6e884a95492d5c6fd7ac94afa0f0439/TypeCobol.Test/NewTestsToFix/Parser/Samples/HighPriority/RuntimeExceptions.cbl) provided by @mayanje makes our Parser run in some (NPE) runtime errors.
I _won't_ correct the precise errors, because I'll make use of this file to test the global try/catch when implemented.

**Comment by wiztigers** [comment]
I've added `try ... catch ...` conditions at seemingly appropriate places in `CodeElementParserStep` and `ProgramClassParserStep`.
When a runtime exception is thrown by any `XXXBuilder`, it is caught there, and parsing of the current program will stop abruptly, but at least without crashing the Parser.
As the parsing ends with at least one error diagnostic (the runtime one), we should never end parse an input file or generate an output file successfully.

What remains to be done is:
* test if these two additions are sufficient to protect against all the kinds of null pointer, invalid cast and whatever runtime errors that are thrown during incomplete programs analysis
* decide if dumping the exception stack trace is okay as an error diagnostic
* measure if there is a noticeable performance hit when parsing a sizeable (correct) production sample

@smedilol , do you have some spare time to lend me a hand on these performance analysis ?

**Comment by smedilol** [comment]
It seems to work fine.
No performance hit.

On our extended production sample, I get the following error (I don't remember it from a previous test):
```
--- Diagnostics ---
[0,0]<31,Error,Semantics>Runtime error: System.ArgumentException: CodeElementHolder must be a Node.
   à TypeCobol.Compiler.Nodes.CodeElementHolderExtension.CodeElement[T](CodeElementHolder`1 holder) dans C:\Users\SMEDILOL\workspaces\TypeCobol\TypeCobol\Compiler\Nodes\Node.cs:ligne 233
   à TypeCobol.Compiler.Diagnostics.WriteTypeConsistencyChecker.GetTypeDefinition(SymbolTable table, Node symbol) dans C:\Users\SMEDILOL\workspaces\TypeCobol\TypeCobol\Compiler\Diagnostics\Cobol85Checkers.cs:ligne 423
   à TypeCobol.Compiler.Diagnostics.WriteTypeConsistencyChecker.CheckVariable(Node node, QualifiedName wname, Object sent) dans C:\Users\SMEDILOL\workspaces\TypeCobol\TypeCobol\Compiler\Diagnostics\Cobol85Checkers.cs:ligne 371
   à TypeCobol.Compiler.Diagnostics.WriteTypeConsistencyChecker.OnNode(Node node, ParserRuleContext context, Program program) dans C:\Users\SMEDILOL\workspaces\TypeCobol\TypeCobol\Compiler\Diagnostics\Cobol85Checkers.cs:ligne 363
   à TypeCobol.Compiler.Parser.NodeDispatcher.OnNode(Node node, ParserRuleContext context, Program program) dans C:\Users\SMEDILOL\workspaces\TypeCobol\TypeCobol\Compiler\Parser\CodeElementDispatcher.cs:ligne 92
   à TypeCobol.Compiler.Parser.CobolNodeBuilder.Exit() dans C:\Users\SMEDILOL\workspaces\TypeCobol\TypeCobol\Compiler\Parser\NodeBuilder\CobolNodeBuilder.cs:ligne 77
   à TypeCobol.Compiler.Parser.CobolNodeBuilder.ExitStatement(StatementContext context) dans C:\Users\SMEDILOL\workspaces\TypeCobol\TypeCobol\Compiler\Parser\NodeBuilder\CobolNodeBuilder.cs:ligne 546
   à TypeCobol.Compiler.Parser.Generated.ProgramClassParser.StatementContext.ExitRule(IParseTreeListener listener) dans C:\Users\SMEDILOL\workspaces\TypeCobol\obj\Debug\TypeCobol.Grammar\ProgramClassParser.cs:ligne 2583
   à Antlr4.Runtime.Tree.ParseTreeWalker.ExitRule(IParseTreeListener listener, IRuleNode r)
   à Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   à Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   à Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   à Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   à Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   à Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   à Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   à TypeCobol.Compiler.Parser.ProgramClassParserStep.ParseProgramOrClass(TextSourceInfo textSourceInfo, ISearchableReadOnlyList`1 codeElementsLines, TypeCobolOptions compilerOptions, SymbolTable customSymbols, Program& newProgram, Class& newClass, IList`1& diagnostics) dans C:\Users\SMEDILOL\workspaces\TypeCobol\TypeCobol\Compiler\Parser\ProgramClassParserStep.cs:ligne 49 ([0>0] on line -1)
```

Otherwise, there is no new errors.

**Comment by wiztigers** [comment]
yay for no performance hit ! ヾ(＾∇＾)
so your analysis of Sep,21 was accurate. Cheers !

Concerning the error, I think I need the source program where it happens. 
Could you put it as a NewTestToFix and create a dedicated issue ? Thanks

**Comment by smedilol** [comment]
This issue has been fixed
