### ISSUE TITLE
Codegen - missing lines

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#300]
Following elements are not copied by codegen (tests made with Cobol 85 code):
- INPUT-OUTPUT SECTION
  - FILE-CONTROL
  - SELECT
  - File description (FD)
- when (except for when other)
  - when with literal seems to work
- REPLACE
- EXEC

**Comment by osmedile** [comment]
New PR#318 fix this issue, except for the replace.
I can fix the REPLACE for Cobol85 files (modify TreeToCode.ShouldCopy and check if ICobolTextLine as IProcessedTokensLine hasCompilerDirective), but this won't work with the action "expand" of Codegen which is by Function and Procedure of TypeCobol.

I'll describe the problem in a new issue (I'll edit this comment once it's done).

**Comment by smedilol** [comment]
Remains to fix:
- EXEC
- REPLACE

**Comment by wiztigers** [comment]
Please test after a75ce1833991d1c37dcb3e6a53ea44a4680c5e7c.

**Comment by smedilol** [comment]
It's now working
