### ISSUE TITLE
EXEC SQL INCLUDE on multiple lines doesn't works

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#321]
New bug detected when EXEC SQL INCLUDE is written on multiple lines

``` cobol
   COPY TCEUCGT    *> works fine
```

``` cobol
   COPY 
                 TCEUCGT    *> works fine
```

``` cobol
 EXEC SQL INCLUDE TCEUCGT   *> works fine                               
 END-EXEC.   
```

``` cobol
 EXEC SQL 
           INCLUDE TCEUCGT   *> Bug
 END-EXEC.   
```

``` cobol
 EXEC 
       SQL INCLUDE TCEUCGT   *> Bug
 END-EXEC.   
```

``` cobol
  EXEC SQL INCLUDE 
                     TCEUCGT END-EXEC. *> Works fine
```

``` cobol
 COPY TCEUCGT *> works fine
 EXEC SQL 
           INCLUDE TCEUCGT   *> works fine
 END-EXEC.   
```

I think problem is in PreprocessorStep.ProcessTokensLinesChanges on step 6.

**Comment by collarbe** [comment]
See Scanner.cs line 1667. 

```if (lastIndex - startIndex >= 6 && line.Substring(startIndex, 7).Equals("INCLUDE", StringComparison.InvariantCultureIgnoreCase))```

**Comment by fm-117** [comment]
@smedilol, I've tested the two bug cases and it seems to work fine on the latest version. But the code initially mentioned by @collarbe has not changed.

**Comment by smedilol** [comment]
@fm-117 Good news. It should have been fixed by recent work on scanner.
To close this issue we need to integrate unit test.
