### ISSUE TITLE
[warning] hides inherited member

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#323]
There are currently many warnings regarding subclasses that _seem_ to override a superclass member, but that in fact do nothing (thus creating dead code), because the superclass member is not marked `virtual`, and the subclass doesn't use the `new` keyword.

We should get rid of these warnings, because they potentially hide inconspicuous bugs.

**Comment by smedilol** [comment]
This is now handled by a ruleset, see #1026
