### ISSUE TITLE
AppVeyor must build EVERYTHING

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#325]
Currently AppVeyor does not build each and every version of our software anymore.
Some commits are ignored, some others seem to be built multiple times.

@smedilol , could you check your settings, please ?
A continuous integration shouldn't behave like that !
Have `skip_commits` or `only_commits` been set, or what ?

Thanks in advance

**Comment by smedilol** [comment]
Appveyor is now triggered every hour.
I'll see later how to do trigger it after each commit.

**Comment by wiztigers** [comment]
Sorry, but I can't consider this issue closed.
On hour delay to build a version, although the compile+testing time is under 1 minute, is juste not enough. It contradicts the principles of incremental building and especially fast delivery that drive the continuous integration idea.

Can't we just empty the "Build schedule" in your project settings and be done with it ?

**Comment by smedilol** [comment]
Appveyor build is now triggered after each commit

**Comment by wiztigers** [comment]
yay ! Ｏ(≧▽≦)Ｏ
