### ISSUE TITLE
Complete file diff for unit tests

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#327]
**SPAWN OF #234**

In #234, @smedilol wanted a real file diff usable for unit tests.
Such an enhancement would improve codegen unit tests in error, and could be used instead of the current file comparison which marks as a diff the first differing line as long as every line after it.

**Comment by smedilol** [comment]
Check https://github.com/mmanela/diffplex

**Comment by smedilol** [comment]
No longer necessary with autoreplace feature of the expected file for tests.
