### ISSUE TITLE
TCRFUN_LIBRARY_COPY

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#328]
**SPAWN OF #278**

Rule **TCRFUN_LIBRARY_COPY** must be specified.
I've made a proposal in [this page](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolNewFunctions), which I have already implemented, because I needed it for #278.

**Comment by smedilol** [comment]
2 quick remarks:

1. the word `SERVICE` have a special meaning and can't be mixed with procedure and functions. We need to find another keyword.
2. The feature to call procedure and functions with a COPY is nice but out of the scope of or first beta.

**Comment by smedilol** [comment]
Not useful anymore
