### ISSUE TITLE
InvalidCastException on CobolNodeBuilder.AttachEndIfExists if missing sentenceEnd

### ISSUE THREAD

**Issue by osmedile** [TypeCobolTeam/TypeCobol#331]
With the following code:
```cobol
ID Division. 
Program-ID. MissingSentenceEnd.          
Procedure division.
move a to b
End Program MissingSentenceEnd. 
```
A dot is missing after `move a to b`.
The code 
```C# 
(CodeElementEnd)terminal.Symbol
```
throw the Exception:
```
Exception thrown: 'System.InvalidCastException' in TypeCobol.exe
Method CobolNodeBuilder.AttachEndIfExists
Additional information: Unable to cast object of type 'TypeCobol.Compiler.Scanner.Token' to type 'TypeCobol.Compiler.CodeElements.CodeElementEnd'.
```
`terminal.Symbol` is 
```
terminal.Symbol = {[1,21:<missing SentenceEnd>]<HexadecimalNationalLiteral>{<missing SentenceEnd>}}
```

Edit: updated test following 143930e

**Comment by wiztigers** [comment]
I cannot reproduce this error on `master`.
When you notice something on your fork that is not reproduceable on `master`, please don't open isses here, as it obscures our vision of what works and what doesn't for next milestone.

Can you open issues related to your fork on your fork's repository ? Thanks in advance.

**Comment by wiztigers** [comment]
Then, this is a **CHILD ISSUE OF #288**
