### ISSUE TITLE
TCRFUN_MATCH_PARAMETERS_COMPRESSION

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#335]
The rule **TCRFUN_MATCH_PARAMETERS_COMPRESSION** must be implemented, as described on [this page](https://github.com/TypeCobolTeam/TypeCobol/wiki/FunctionsDeclaration/#TCRFUN_MATCH_PARAMETERS_COMPRESSION).

**Comment by smedilol** [comment]
Current specs is:
The physical compression of all `INPUT`, `INOUT` and `OUTPUT` parameters provided on a given procedure call must match the physical compression (same comp-* between caller and callee) of all parameters of at least one declared procedure of the same name.

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
