### ISSUE TITLE
TCRFUN_EMPTY_CALL

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#336]
The rule **TCRFUN_EMPTY_CALL** must be implemented, as described on [this page](https://github.com/TypeCobolTeam/TypeCobol/wiki/FunctionsDeclaration/#TCRFUN_EMPTY_CALL).

**Comment by collarbe** [comment]
Don't know how to create the test file in TypeCobol to try TCRFUN_EMPTY_CALL

Here is a file example 

       IDENTIFICATION DIVISION.
       PROGRAM-ID. ProcedureCall.

       DATA DIVISION.
       LOCAL-STORAGE SECTION.

       01  somedate     TYPE Date.
       01  someformat   PIC X(08).
       01  flag         TYPE Bool.
       01  realformat   PIC X(08).

       PROCEDURE DIVISION.
       
       DECLARE PROCEDURE ValidateDateFormat PRIVATE
           INPUT mydate        TYPE Date
                 format        PIC X(08)
          OUTPUT okay          TYPE Bool
                 actual-format PIC X(08).
         .
         PROCEDURE DIVISION.
           CONTINUE.
       END-DECLARE.

       DECLARE PROCEDURE EmptyProc PRIVATE
         .
       PROCEDURE DIVISION.
           CONTINUE.
       END-DECLARE.

      DECLARE FUNCTION DoesNothing PRIVATE.
         PROCEDURE DIVISION.
           DISPLAY 'I DO NOTHING'
           .
       END-DECLARE.

      DECLARE FUNCTION StrangelyReturnsItsInput PRIVATE
             INPUT     x      PIC 9(04)
             RETURNING result PIC 9(04)
           .
       PROCEDURE DIVISION.
           IF x = 0
             MOVE 0 TO result
           ELSE
             MOVE x TO result
           END-IF.
       END-DECLARE.

       TRAITEMENT.
      * __________________________________________________
      * OK : proper parameter list (TCRFUN_CALL_PARAMETER_ORDER)
           CALL ValidateDateFormat
                    INPUT      somedate someformat
                    OUTPUT     flag     realformat
       
           CALL ValidateDateFormat
                    INPUT      somedate by content 'YYYYMMDD'
                    OUTPUT     flag     realformat
           END-CALL
      * __________________________________________________
      * KO : procedure doesn't exist
           CALL ValidateDatFormatt
                    INPUT      somedate someformat
                    OUTPUT              realformat
           END-CALL
      * __________________________________________________
      * OK : parameter number for a procedure
      *      however, this is parsed as a standard COBOL call
      *    Will change after issue #366
           CALL ValidateDateFormat END-CALL
      * __________________________________________________
      * KO : wrong parameter number (TCRFUN_MATCH_PARAMETERS_NUMBER)
           CALL ValidateDateFormat
                    INPUT      somedate someformat
                    OUTPUT              realformat
           END-CALL
      * __________________________________________________
      * KO : wrong parameter order (TCRFUN_MATCH_PARAMETERS_TYPE)
           CALL ValidateDateFormat
                    INPUT      someformat somedate
                    OUTPUT     realformat flag
      
      * OK with INPUT on the same line as call
           CALL ValidateDateFormat INPUT      somedate 
                                              by content 'YYYYMMDD'
                                   OUTPUT     flag     realformat
           END-CALL
           .
      * __________________________________________________
      * KO : Contains INOUT keyword
       DECLARE PROCEDURE MyProc1 PRIVATE
          INPUT  mydate        TYPE Date
                 format        PIC X(08)
          INOUT  var1          type Date
          OUTPUT okay          TYPE Bool
                 actual-format PIC X(08).
         .
         PROCEDURE DIVISION.
           CONTINUE.
       END-DECLARE.
           CALL MyProc1
                    INPUT      somedate someformat 
                    INOUT      somedate
                    OUTPUT     flag someformat

           .
      * __________________________________________________
      * OK : Contains IN-OUT keyword
       DECLARE PROCEDURE MyProc2 PRIVATE
          INPUT  mydate        TYPE Date
                 format        PIC X(08)
          IN-OUT  var1          type Date
          OUTPUT okay          TYPE Bool
                 actual-format PIC X(08).
         .
         PROCEDURE DIVISION.
           CONTINUE.
       END-DECLARE.
           CALL MyProc2
                    INPUT      somedate someformat 
                    IN-OUT     somedate
                    OUTPUT     flag someformat

           .
      * __________________________________________________
      * OK : procedure invocation without INPUT, IN-OUT, OUTPUT (TCRFUN_EMPTY_CALL) 
      * Recognize an empty call of an empty procedure
           CALL EmptyProc

      * KO : procedure invocation with INPUT, IN-OUT, OUTPUT (TCRFUN_EMPTY_CALL) 
      * Recognize an empty call to an no empty procedure
           CALL ValidateDateFormat
      
      * OK : function ivocation witout INPUT or RETURNING (TCRFUN_EMPTY_CALL) 
      *      Recognize an empty call of an empty function
           CALL DoesNothingFunc

      * KO : function ivocation with INPUT and RETURNING (TCRFUN_EMPTY_CALL) 
      * Recognize an empty call to non empty function
           CALL StrangelyReturnsItsInput 

           END-CALL
           .
      * __________________________________________________
       END PROGRAM ProcedureCall.
