### ISSUE TITLE
TCRFUN_LIBRARY_COPY  generate code only for a TypeCobol caller

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#338]
Procedure and fonctions:  TCRFUN_LIBRARY_COPY  if no library copy is specified generate code only for a TypeCobol caller

**Comment by wiztigers** [comment]
The following 3 rules were previousely formulated like this:

* **TCRFUN_LIBRARY_COPY**  
A library must declare the filename of a copy to be generated. This copy file will contain the declaration of all `PUBLIC` function declared in the library, so they can be called from a COBOL program by using the `COPY` directive.
* **TCRFUN_CODEGEN_CALL_DATA**  
An item allowing the library to figure out which way it is called (either from a TypeCobol function call or a COBOL `COPY` directive) must be generated in `LINKAGE SECTION`.
** If the library function is called via a `COPY` directive, this item must contain the library name.
** If the library function is used through a TypeCobol function call, this item must be an array containing one element for each function called by the caller program.

According to this issue, they have been rewritten as follows:

* **TCRFUN_LIBRARY_COPY**  
A library can declare the filename of a copy to be generated. If a filename is declared, the copy file will contain the declaration of all `PUBLIC` function declared in the library, so they can be called from a COBOL program by using the `COPY` directive.  
If no filename is declared:
  * no copy file is generated ;
  * the rule **TCRFUN_CODEGEN_LIBRARY_COPY** doesn't apply ;
** calling any function from this library using a `COPY` directive in a COBOL 85 program is not possible.
* **TCRFUN_CODEGEN_CALL_DATA**  
An item allowing the library to figure out which way it is called (either from a TypeCobol function call or a COBOL `COPY` directive) must be generated in `LINKAGE SECTION`.
  * If the library function is called via a `COPY` directive, this item must contain:
    * the copy name, if an only if it was declared (see rule **TCRFUN_LIBRARY_COPY**) ;
    * the fixed label `'CALL FROM COBOL NOT SUPPORTED'` if no copy name was declared.
  * If the library function is used through a TypeCobol function call, this item must be an array containing one element for each function called by the caller program.
