### ISSUE TITLE
Procedure : declaration

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#340]
Implement procedure declaration as defined [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctions) and [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax)

**Comment by wiztigers** [comment]
Despite the issue description referencing [this page](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax) as a whole, I consider the following rules as out of the scope of this issue:
- **TCRFUN_FUNC_COMMA_SEPARATOR**
- **TCRFUN_ERROR_CODE_DECLARATION_ORDER**
- **TCRFUN_ERROR_CODE_OPTIONAL**

@smedilol , please confirm.

**Comment by smedilol** [comment]
Yes, these 3 rules are included in issue #313 and #309 targeted for milestone [Beta 1](https://github.com/TypeCobolTeam/TypeCobol/milestone/29)

**Comment by wiztigers** [comment]
Thanks @smedilol

**Comment by wiztigers** [comment]
All rules regarding procedure declaration (syntax and codegen) are now implemented, excepted the 3 we've discussed about.
