### ISSUE TITLE
TCRFUN_NO_CALL_TO_ENCLOSING_PROGRAM > TCRFUN_NO_PERFORM_OF_ENCLOSING_PROGRAM

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#343]
**CHILD ISSUE OF #340**
The rule **TCRFUN_NO_CALL_TO_ENCLOSING_PROGRAM** must be implemented as described on [this page](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax).

**Comment by smedilol** [comment]
CHILD OF #245

**Comment by wiztigers** [comment]
The current rule formulation is as follows:

**TCRFUN_NO_CALL_TO_ENCLOSING_PROGRAM** A function or procedure cannot call a paragraph or section of the enclosing program.

This is rather confusing, because the rule name and description seem to speak about `CALL` statement. However, paragraphs and sections can be invoked only with `PERFORM` statements.
Thus, I propose the following title and description change:

* **TCRFUN_NO_PERFORM_OF_ENCLOSING_PROGRAM**  
A function or procedure cannot use any `PERFORM` statement that targets a paragraph or section of the enclosing program.


That being said, we must discuss about which `CALL` statements can be put inside a function or procedure declaration. In particular:
* can I `PERFORM` the enclosing program ?
* can I `PERFORM` a subprogram nested in the enclosing program ? That could look nice in TypeCobol, but doesn't seem to work once generated to COBOL
* can I `PERFORM` other functions ?

... and so on.
These questions should be discussed in another issue.

**Comment by wiztigers** [comment]
In accordance with @smedilol, I've updated the rule **TCRFUN_NO_CALL_TO_ENCLOSING_PROGRAM** as **TCRFUN_NO_PERFORM_OF_ENCLOSING_PROGRAM**.
