### ISSUE TITLE
TCRFUN_0_TO_N_PARAMETERS

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#344]
**CHILD ISSUE OF #340**

The rule **TCRFUN_0_TO_N_PARAMETERS** is described on [this page](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax).

However, the _INPUT_, _INOUT_ and _OUTPUT_ clauses are implemented like this:
```
inputPhrase:  INPUT  parameterDescription+;
inoutPhrase:  INOUT  parameterDescription+;
outputPhrase: OUTPUT parameterDescription+;
```

As it uses the wording "should not" instead of "must not", the rule specification can be interpreted as making the following declarations legal (for example when declaring a getter of some sort, that takes no input but "returns" something):
```cobol
DECLARE FUNCTION  GetSomething     PUBLIC INPUT RETURNING result.
DECLARE PROCEDURE GetSomethingElse PUBLIC INPUT INOUT OUTPUT result.
```
However, these declaration are illegal according to the current grammar.

If we don't want keywords with no parameter list behind, we should rewrite the rule as follows:

* **TCRFUN_0_TO_N_PARAMETERS**
Lists of _input_, _inout_ and _output_ parameters can contain 0 to N parameters.
  * The list of _input_ parameters can be empty. In this case, the function/procedure takes no _input_ parameters and the `INPUT` keyword must not be used.
  * The list of _inout_ parameters can be empty. In this case, the procedure takes no _inout_ parameters and `INOUT` keyword must not be used.
  * The list of _output_ parameters can be empty. In this case, the procedure takes no _output_ parameters and `OUTPUT` keyword must not be used.

**Comment by wiztigers** [comment]
@smedilol , what's your opinion ?

**Comment by smedilol** [comment]
Ok for this modification, it's better like that.

**Comment by wiztigers** [comment]
Done (wiki:25d336423f3614d79feb3e601f4f032041e1de9b).
