### ISSUE TITLE
TCRFUN_NO_INOUT_OR_INPUT_FOR_FUNCTIONS > TCRFUN_NO_INOUT_OR_OUTPUT_FOR_FUNCTIONS

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#345]
**CHILD OF #340**

The rule **TCRFUN_NO_INOUT_OR_INPUT_FOR_FUNCTIONS** from [this page](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax) is currently described as follows:

* **TCRFUN_NO_INOUT_OR_INPUT_FOR_FUNCTIONS** A function cannot have inout or output parameters.

The rule name talks about _inout_ and _INPUT_, but the description talks about _inout_ and _OUTPUT_.

It should thus be rewritten as follows :

* **TCRFUN_NO_INOUT_OR_OUTPUT_FOR_FUNCTIONS**
  A function can only declare _input_ parameters (using the `INPUT` clause) and one _returning_ parameter (using the `RETURNING` clause). A function cannot declare _inout_ or _output_ parameters.

**Comment by wiztigers** [comment]
@smedilol, what is your opinion ?

**Comment by smedilol** [comment]
Yes, my mistake.
Ok for the modification.

**Comment by wiztigers** [comment]
Done (wiki:f8b372afe6ed8ae7248142b20b0385d15435938f).
