### ISSUE TITLE
TCRFUN_DECLARE_FUNCTION_OR_PROCEDURE

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#346]
**CHILD OF #340**

In commit b54acdf328badaceae2d2e01fa74a78b01097255, I implemented my understanding the `DECLARE PROCEDURE` syntax.

However, our [specification](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax) does not explicitely describe if the `FUNCTION` or `PROCEDURE` keywords are mandatory.
As existing rules **TCRFUN_NO_INOUT_OR_OUTPUT_FOR_FUNCTIONS** and **TCRFUN_NO_RETURNING_FOR_PROCEDURES** are explicit enough for our parser to know what is the _intent_ of the developper regarding the nature of what (s)he is implementing (whether it is a procedure or a function), I chose to implement the `FUNCTION` or `PROCEDURE` to _NOT_ be mandatory. If the developper does not describe explicitely whether (s)he is implementing a procedure or a function, (s)he makes the choice to leave the decision to our parser.

What the parser is able to find can be seen in b54acdf328badaceae2d2e01fa74a78b01097255, and in particular in this [sample test](https://github.com/TypeCobolTeam/TypeCobol/blob/master/TypeCobol.Test/Compiler/Parser/Samples/Statements/DECLARE.cbl) and the corresponding [expected result](https://github.com/TypeCobolTeam/TypeCobol/blob/master/TypeCobol.Test/Compiler/Parser/ResultFiles/Statements/DECLARE.txt) (the interesting part is the end of each line of the expected result, that dumps "what the user declared"/"what is detected according to input/inout/output/returning clauses").

I chose to _always_ follow the developper's intent. For example, if (s)he declare the following:
```cobol
DECLARE PROCEDURE MyProcedure PRIVATE
   INPUT    MyParameter TYPE MyType.
```
It will be detected only as a procedure, even if it could be called like a function.
Being only detected as a procedure will thus prevent inline call, even if its parameters would allow this.

We must decide if it this behaviour is acceptable.
If so, I propose to add the following rule to our [specification page](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax):

* **TCRFUN_DECLARE_FUNCTION_OR_PROCEDURE**
A function is declared using the `DECLARE FUNCTION` statement.
A procedure is declared using the `DECLARE PROCEDURE` statement.
The `FUNCTION` or `PROCEDURE` keywords are not mandatory. If both of these keywords are omitted, the following rules apply:
  * The nature of what is declared is decided according to the rules **TCRFUN_NO_INOUT_OR_OUTPUT_FOR_FUNCTIONS** and **TCRFUN_NO_RETURNING_FOR_PROCEDURES**.
  * If the parameter list declaration uses both the `RETURNING` keyword and any of the `INOUT` or `OUTPUT` keywords, the `DECLARE` statement will be in error, as what is declared cannot be either a function or a procedure.
  * If there are only _input_ parameters (or no parameter at all) and no _inout_, _output_ or _returning_ parameter, the resulting declaration can be called either like a function or like a procedure.

**Comment by wiztigers** [comment]
As I side note, I'd add that I'm not fond of the last of the 3 "subrules".
I added it because, according to our current specification, it seems it is not possible to call a function like a procedure, and vice-versa.
If we'd allow to call a function using our procedure-style `CALL` statement, this last subrule could be rewritten like:
* **TCRFUN_DECLARE_FUNCTION_OR_PROCEDURE**

  _... blah blah blah ..._
  * If there are only _input_ parameters (or no parameter at all) and no _inout_, _output_ or _returning_ parameter, the `PROCEDURE` keyword is assumed.

**Comment by wiztigers** [comment]
@smedilol @reydelpa @delmasgu , any opinions ?

**Comment by smedilol** [comment]
Why not with your proposition to specify that keywords `FUNCTION` and `PROCEDURE` are not mandatory. 


About your last subrule:

> If there are only input parameters (or no parameter at all) and no inout, output or returning parameter, the FUNCTION keyword is assumed.

there is the rule:
__TCRFUN_FUNC_ALLOW_CALL__ `Functions can also be called like a procedure. This syntax make it easier to test the error-code.`

So your proposition makes sens, except that with `FUNCTION` there is less control in case of error.
Let's wait for other opinions.

**Comment by wiztigers** [comment]
Aw yes, I remember this rule, now. I didn't manage to find it last time I checked.
So, I can just use my second formulation of the third subrule without loosing any features. The sample `MyProcedure` given in this issue's description will thus be a function, that just won't be able to be called as a procedure untill **TCRFUN_FUNC_ALLOW_CALL** is implemented.

**Comment by wiztigers** [comment]
In accordance about what we've discussed in this issue, I've just added the following rule to our specification:

* **TCRFUN_DECLARE_FUNCTION_OR_PROCEDURE**  
A function is declared using the `DECLARE FUNCTION` statement.
A procedure is declared using the `DECLARE PROCEDURE` statement.
The `FUNCTION` or `PROCEDURE` keywords are not mandatory. If both of these keywords are omitted, the following rules apply:
  * The nature of what is declared is decided according to the rules **TCRFUN_NO_INOUT_OR_OUTPUT_FOR_FUNCTIONS** and **TCRFUN_NO_RETURNING_FOR_PROCEDURES**.
  * If the parameter list declaration uses both the `RETURNING` keyword and any of the `INOUT` or `OUTPUT` keywords, the `DECLARE` statement will be in error, as what is declared cannot be either a function or a procedure.
  * If there are only _input_ parameters (or no parameter at all) and no _inout_, _output_ or _returning_ parameter, the `FUNCTION` keyword is assumed.
