### ISSUE TITLE
TCTYPE_LIMITED_STRONG_RECEIVER

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#355]
CHILD OF #191 #192
Rule is described here :
https://github.com/TypeCobolTeam/TypeCobol/wiki/Cobol02TYPEDEF

Test is:
NewTestsToFix/Samples/HighPriority/Type-TCTYPE_LIMITED_STRONG_RECEIVER.tcbl

**Comment by wiztigers** [comment]
`TCTYPE_LIMITED_STRONG_RECEIVER.pgm` unit test program now passes with the required errors.
