### ISSUE TITLE
Bool variable name are not correctly referenced in generated code

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#358]
The following TypeCobol :
```cobol
declare procedure check private
            returning   result type bool.
procedure division.
            set result to true.
end-declare.
```
is generated into
```cobol
IDENTIFICATION DIVISION.
       PROGRAM-ID. fafff951.
       DATA DIVISION.
       LINKAGE SECTION.
       01 result-value PIC X     VALUE LOW-VALUE.
           88 result       VALUE 'T'.
           88 result-false VALUE 'F'.
       PROCEDURE DIVISION
             USING BY REFERENCE result
           .
            set result to true.
       END PROGRAM fafff951.
```

The problem is that the name of the `result` variable change from `result` to `result-value`.
So the generated line `USING BY REFERENCE result` is wrong. It should be:
`USING BY REFERENCE result-value`

I see 2 options:
- Fix this and reference correctly bool variable everywhere in the generated code
  @wiztigers is it easy?
- Change our specs so the `result` variable is still named `result` in generated code
 ```cobol
        01 result PIC X     VALUE LOW-VALUE.
           88 result-true  VALUE 'T'.
           88 result-false VALUE 'F'.
```
  @reydelpa @delmasgu @sarterbe  what do you think?

**Comment by wiztigers** [comment]
IMO changing the parameter name in the generated code is less impacting than changing the spec and the way booleans are implemented. It is not even a worry regarding TypeCobol functions generated code being called from pure COBOL programs, as the name of the parameter is of no importance in that case (what matters is its "type").

So I fixed it in the more satisfying way in f0a0c5f5a184b43f6030f1dfbb0870e03abfae1b.
Reopen this issue if I didn't take the right course of action.
