### ISSUE TITLE
"Invisible" exceptions

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#38]
If a statement to be tested throws an exception somewhere in the parser (currently: *NotImplementedExceptions*), it is not directly seen by the test runner.
For example : you have a clean test, you add a statement at the end that provokes an exception, but your test will be a success nevertheless.

**Comment by osmedile** [comment]
Maybe commit 0fe4feed604cf68ebb181aa8f5cb6b1f5140510b fixed this

**Comment by wiztigers** [comment]
@osmedile nope, it isn't fixed.
One can still put an NPE somewhere and break silently.
