### ISSUE TITLE
Statement: SET

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#40]
Implement SET statement (7 formats).

**Comment by smedilol** [comment]
Format 1, 5, 6 and 7 fo the set statement can be ambiguous:
Ex:
set userDefinedWord-1 TO userDefinedWord-2

We will need to wait the phase after parsing to determine the real type of the userDefinedWord and then determine which type of set statement it is.

So this four different set statement will be implemented as a single CodeElement.
The grammar rules can be let as four different rules.

**Comment by smedilol** [comment]
Fixed with commit a075f3f8fdd2b825b8d665624da21b975923af22

**Comment by wiztigers** [comment]
Are there enough unit tests to cover the new SET statement grammar ?
If so, you can remove the **To Test** label as described [here](https://github.com/TypeCobolTeam/TypeCobol/wiki/IssueLifecycle). :)
