### ISSUE TITLE
Subscript diagnostics

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#400]
Our current subscript checker doesn't works.
We need to implement it to manage any dimension of arrays.

**Comment by smedilol** [comment]
All errors related to subscripts will be deactivated in our parser.
The standard IBM compiler will do the work for now.

**Comment by smedilol** [comment]
Quick algo:
1. Get Susbsripts of variable
2. Get the DataDefinition of the Variable
3. From the DataDefinition itself and all parent recursively, create a list of all occursed Node 
4. Compare the subscripts list and occursed Node list
                List must match in number of elements
                Each subscript must not exceed the size the max size of the related Node

**Comment by fm-117** [comment]
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL06.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 tab1.
          05 oc1 occurs 10.
             10 item PIC X.
       01 elt PIC X.
       01 tab2.
          05 oc1 occurs 10.
             10 oc2 occurs 20.
                15 oc3 occurs 30.
                   20 item PIC X.
       PROCEDURE DIVISION.
           MOVE item OF tab1 (30)          TO elt
           MOVE item OF tab2 (40, 40, 40)  TO elt
           GOBACK
           .
       END PROGRAM TCOMFL06.
```

IBM compiler reports error on every subscript, message is `Subscript or index literal"40"exceeded the maximum occurrence value"30"for the table.  The maximum occurrence value was assumed.`

**Comment by fm-117** [comment]
Literals in subscripts are now checked (see PR #2004). Tables declared in TypeCobol typedefs are not supported, see issue #2018.
