### ISSUE TITLE
File description entry

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#41]
Implement file description entry (4 formats).

**Comment by wiztigers** [comment]
Spec says (pp170-173) it must be written `BLOCK CONTAINS 0 (CHARACTERS | RECORDS)`, but real code says it can be written `BLOCK CONTAINS 0`. Where is the truth?

**Comment by wiztigers** [comment]
![SPEC GAP!](http://png-2.findicons.com/files/icons/1014/ivista/128/warning.png "SPEC GAP!")
GRAMMAR CHANGE:
Some tests have showed that `BLOCK CONTAINS 0` is allowed.

**Comment by smedilol** [comment]
Check if the generated code is ok.
If so, then this issue can be postpone to Milestone Version 2.0

**Comment by smedilol** [comment]
No problem detected with our sample.

**Comment by wiztigers** [comment]
If no problem is detected, this issue should be closed.
