### ISSUE TITLE
Tokens replaced need the MultilineScanState to determine their type

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#428]
Number scanned after a REPLACE has been evaluated are considered as Token of type LevelNumber.

```cobol
000000 IDENTIFICATION DIVISION.
000000 PROGRAM-ID. TestReplace.
000000 DATA DIVISION.       
000000 working-storage section.
000000 replace ==:MAX:==  by ==0020== .
000000 01 Array.
000000    05 Elt1  pic X  Occurs :MAX:.                                       
000000 PROCEDURE DIVISION.
000000  .
```
Here `:C-NBR-MAX:`  will be replaced by `0020`but will be considered as LevelNumber instead of Number.

The cause is method `Scanner. ScanIsolatedTokenInDefaultContext` create a new `MultilineScanState` with property `InsideDataDivision` to true.
Then properties `LastSignificantToken` and `BeforeLastSignificantToken` are lost.
Further the Scanner will change the Token type because it thinks he's at the beginning of a sentence.
`(if(tokensLine.ScanState.InsideDataDivision && tokensLine.ScanState.AtBeginningOfSentence)).`

After discussion with @laurentprudhon  : 

> Quotes from him:

> 
> When scanning replacement tokens with REPLACE directive, we are by definition out of context.
> 
> This replacement tokens can be theoretically inserted anywhere in the soure code.
> The same replacement token whose text is `01` can be inserted as a LevelNumber (`01 TBL-TAUCCAU` or a numeric literal `TBL-TAUCCAU VALUE 01`).

> To handle all this cases, we should in ReplaceTokensLinesIterator :
> -	Compare the text of token to replace and not their type
> -	Inject text of replacement tokens in the line (or lines) et scan again all tokens in the context. Currently we only use the remplacement token
> -	Do the same on all successive lines until we the scanner state is synchronized again
> 
> Implement such a behavior can be very bad for performance, especially if we imagine incremental compilation in the future.
> 
> To be more pragmatic, this behavior is only necessary if we replace a token whose type is affected by the scanner state.
> It's the case only with the following replacement :
> -	On keywords : DATA, DECLARATIVES, END, FILE, ID, NEXT, PROCEDURE, SERVICE, WHEN
> -	levelNumber > IntegerLiteral, paragraphNameDefinition > UserDefinedWord, sectionNameDefinition > UserDefinedWord
> ```cobol
> REPLACE == PROCEDURE == BY == MOVE == ?
> REPLACE == :LEVEL1: == BY == 10 == == :LEVEL2: == BY == 15 == == :LEVEL3: == BY == 20 ==  … ?
> REPLACE == :PARAGRAPH: == BY == ComputeSum == ?
> ```
> 
> (check 4th tab of https://github.com/TypeCobolTeam/TypeCobol/blob/master/TypeCobol/Documentation/Studies/Code%20elements%20starting%20tokens.xlsx)
> 
> It seems very unlikely that a REPLACE fall in this cases with real source code.
> 
> So we will implement only what's needed for our source code found in our enterprise.
> 
> For a partial replace.
> ```cobol
>    REPLACE == :Prefix : == BY == MyData ==
>    01 :Prefix:-Length PIC 9(3)
> ```
> 
> What to do:
> Change initialization of MultilineScanState inside method ScanIsolatedTokenInDefaultContext :
> - Clone the scan state saved at the beginning of the line which is the target of the replace. `(tokensLine.InitialScanState.Clone())`
> - Call `scanState.AdvanceToNextStateAndAdjustTokenProperties()` on the 2 tokens before the token to replace.

**Comment by collarbe** [comment]
It appears that there is a problem in the detection of LastSignificantToken

==> This return a correct result
       REPLACE ==:C-NBR-MAX:== by ==0020== .

       05 TBL-TAUCCAU    Occurs 
	                            :C-NBR-MAX:.

==> This does not.
       REPLACE ==:C-NBR-MAX:== by ==0020== .
       05 TBL-TAUCCAU    Occurs  :C-NBR-MAX:.

**Comment by smedilol** [comment]
@mayanje Can you check proposed solution on this issue for #1753 and #599

**Comment by smedilol** [comment]
@mayanje 
After review of PR #1797 for issue #599 and #1795 for issue #1753, the goal is to find a common way to resolve both issue.
See the proposal in this page.
The final solution can be close to what is already done for PartialCobolWord in #1797. 
If a common solution is found, then PR #1795 can be abandonned.

**Comment by mayanje** [comment]
The issue is reopened, because there's a failure if a replacement is made inside a DATA DIVISION, then an IntegerLiteral can become a Level Number.
The following sample is an example of failure:

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOZCHKP.
       data division.
       working-storage section.
       REPLACE
                ==C-NBRPCB==      BY ==6==.  
       01  W-IDTPCB OCCURS C-NBRPCB    PIC X(8).          
       END PROGRAM TCOZCHKP.
``
