### ISSUE TITLE
EI LEgacy: Generate REMARKS when AutoRemarks is activated

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#446]
When #440 is done.
We need to generate the REMARKS directive.
2 cases :
- There is already an incomplete REMARKS directive written in the original source code.
  - This REMARKS can either be removed OR completed. Whatever is easier to implement
- There is no REMARKS directive, then the full REMARKS directive must be generated

**Comment by smedilol** [comment]
First line of Remarks is generated not generated at the good column:
```cobol
       *REMARKS. COPY=(
      *        COPY1
      *        COPY2
      *        ).
```

Expected result:
```cobol
      *REMARKS. COPY=(
      *        COPY1
      *        COPY2
      *        ).
```

**Comment by smedilol** [comment]
One last thing:
The existing Remarks is lost:
If I have:
```cobol
       PROGRAM-ID. DVZF0OSM.
      *REMARKS. COPY=(
      *        MyCOPY
      *        ).
       DATA DIVISION .
       local-STORAGE SECTION.
       01 CCTEXT. COPY YCCTEXT.
```
The result is:
``` cobol
      *REMARKS. COPY=(
      *        YCCTEXT
      *        ).
      
       DATA DIVISION .
       local-STORAGE SECTION.
       01 CCTEXT. COPY YCCTEXT.
```

**Comment by collarbe** [comment]
MyCopy is lost beacause it's only 6 chars long. If tou have MyCOPY7 it does conserve the copy name when generating Remarks.

**Comment by smedilol** [comment]
Ok to merge.
