### ISSUE TITLE
Codegen: Bool variable cannot be used outside a condition argument

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#455]
With myBool Variable generated like this:
```cobol
      *      10  myBool TYPE BOOL.
             10  myBool-value PIC X VALUE LOW-VALUE.
         88  myBool        VALUE 'T'.
         88  myBool -false VALUE 'F'.
```

When used outside a condition argument like this:
```cobol
move myBool to myBool
```
The generated code is the same which is wrong. It should be:
```cobol
move myBool-value to myBool-value
```

The workaround is to add a group variable above myBool and use it:
With myBool Variable generated like this:
```cobol
            09 myBoolGroup.
      *      10  myBool TYPE BOOL.
             10  myBool-value PIC X VALUE LOW-VALUE.
         88  myBool        VALUE 'T'.
         88  myBool -false VALUE 'F'.

            move myBoolGroup to myBoolGroup
```

**Comment by smedilol** [comment]
We could reuse the same technique as with indexes to mark nodes and reference StorageAreas that use a Bool.

Rule : all variables under a ConditionalExpression or a Set Node must remain untouched duringcodegen.
Otherwise, codegen must replace the variable with  "*variable_name*Group"

**Comment by collarbe** [comment]
Test also with WHEN
