### ISSUE TITLE
Typedef strict

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#459]
After tests, it seems `TYPEDEF STRONG` doesn't suit exactly our need.
We need `TYPEDEF STRICT` that works like `TYPEDEF STRONG` but with following differences:
- contains value clause (like weak typedef)
- have a picture clause on the same line as the typedef strict declaration (like weak typedef)

**Comment by collarbe** [comment]
Problem while trying to change grammar..
