### ISSUE TITLE
Custom EI rule : Force the usage of Typedef strict over weak/strong typedef

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#460]
Add a custom EI Rule:
If a weak or strong typedef is used, then create an error:
"Custom EI rule : Only `Typedef strict` is allowed"

**Comment by collarbe** [comment]
After adding new Compilation Symbol `#if EUROINFO_LEGACY_TYPEDEF`, all tests with TYPEDEF don't pass. 

- Do I have to change all tests to use STRICT instead of WEAK/STRONG ? 
- If TYPEDEF is STRICT, do we have to check external or redifines clauses in TypeDef ?

**Comment by smedilol** [comment]
After adding new Compilation Symbol `#if EUROINFO_LEGACY_TYPEDEF` (so only strict typedef is allowed), all tests with TYPEDEF don't pass. 

> - Do I have to change all tests to use STRICT instead of WEAK/STRONG ? 

Maybe one solution is to add a 2 new Build Configurations:
* EIRules_Debug
* EIRules_Release

This configuration will activate all our EI rules but also deactivate tests related to WEAK and STRONG.
The standard configuration build (Debug, Release) will not activate our EI tests.

Our tests on our local machine will be made using only EIRules_*
Appveyor will use the standard configuration builds (Debug, Release) and EIRules_*

@collarbe @mayanje  what do you think?

>  If TYPEDEF is STRICT, do we have to check external or redifines clauses in TypeDef ? 

==> Yes, same behavior as Strong

**Comment by mayanje** [comment]
Yes I think its a right solution also.

**Comment by collarbe** [comment]
Proposition for Unit test : 
We cannot ignore all unit test using STRONG or WEAK TypeDef. In order to use EIRules_Debug configuration, I think that we could create two kinds of Results File for tests. One for Debug/Release and one for EIRules_*. 
The comparator will just have to select the file corresponding to the configuration.

**Comment by collarbe** [comment]
Created issue #475.

**Comment by smedilol** [comment]
The common pattern for our checker is to create as many diagnostic as possible.
In TypeDefinitionEntryChecker.CheckTypedef, there is no need to `return` after the check _"Only TYPEDEF STRICT is allowed."_

**Comment by collarbe** [comment]
Mistake on issue number, last commit 	"Update SQLCA copy content." is for Issue #236
