### ISSUE TITLE
Performance measure : Antlr profiler

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#468]
**CHILD OF #270**

laurentprudhon has already implemented Anltr profiler on his fork.
We can retrieve the last commit of:
https://github.com/laurentprudhon/TypeCobol/commits/parser-performance-12-2016

**Comment by collarbe** [comment]
May we could implement some unit tests to check Antlr Performance results. Just have to check is the result is stable between multiple parsing before creating new FileComparer etc..

**Comment by collarbe** [comment]
Here is the result of Antlr Performance tracker. 2 parts of this document are using MS unit, so we could not use this document like this to create Unit test.


---------------------
Top rules invocations
---------------------

27	codeElement
18	alphanumericValue4
12	dataDescriptionEntry
12	integerValue2
12	symbolDefinition4
12	dataNameDefinition
8	typeNameReference
8	cobol2002TypeClause
6	alphanumericValue5
6	symbolReference4
6	programNameReference3
4	cobol2002TypedefClause
4	pictureClause
4	alphanumericValue7
3	programIdentification
3	programEnd
3	authoringProperties
3	dataDivisionHeader
3	workingStorageSectionHeader
3	symbolDefinition5
3	symbolReference5
3	programNameDefinition
3	programNameReference2
1	cobolCodeElements
1	globalClause
1	procedureDivisionHeader
1	sentenceEnd
1	gobackStatement
0	dummyPhase1Rule
0	tcCodeElement

---------------------
Costly decisions info
---------------------

0 : 28 invocations, 359 µs per decision, 10 ms in prediction
71 : 3 invocations, 564 µs per decision, 1 ms in prediction
56 : 8 invocations, 72 µs per decision, 0 ms in prediction
63 : 27 invocations, 14 µs per decision, 0 ms in prediction
75 : 3 invocations, 36 µs per decision, 0 ms in prediction
70 : 3 invocations, 23 µs per decision, 0 ms in prediction
62 : 12 invocations, 4 µs per decision, 0 ms in prediction
60 : 13 invocations, 1 µs per decision, 0 ms in prediction

---------------------
Rules invocation info
---------------------

2:codeElement
	12	2:codeElement>dataDescriptionEntry
	3	2:codeElement>programIdentification
	3	2:codeElement>dataDivisionHeader
	3	2:codeElement>workingStorageSectionHeader
	3	2:codeElement>programEnd
	1	2:codeElement>procedureDivisionHeader
	1	2:codeElement>gobackStatement
	1	2:codeElement>sentenceEnd



3:codeElement>dataDescriptionEntry
	12	3:codeElement>dataDescriptionEntry>integerValue2
	12	3:codeElement>dataDescriptionEntry>dataNameDefinition
	8	3:codeElement>dataDescriptionEntry>cobol2002TypeClause
	4	3:codeElement>dataDescriptionEntry>cobol2002TypedefClause
	4	3:codeElement>dataDescriptionEntry>pictureClause
	1	3:codeElement>dataDescriptionEntry>globalClause

3:codeElement>programEnd
	3	3:codeElement>programEnd>programNameReference2

3:codeElement>programIdentification
	3	3:codeElement>programIdentification>programNameDefinition
	3	3:codeElement>programIdentification>authoringProperties



4:codeElement>dataDescriptionEntry>cobol2002TypeClause
	8	4:codeElement>dataDescriptionEntry>cobol2002TypeClause>typeNameReference
	6	4:codeElement>dataDescriptionEntry>cobol2002TypeClause>programNameReference3

4:codeElement>dataDescriptionEntry>dataNameDefinition
	12	4:codeElement>dataDescriptionEntry>dataNameDefinition>symbolDefinition4

4:codeElement>dataDescriptionEntry>pictureClause
	4	4:codeElement>dataDescriptionEntry>pictureClause>alphanumericValue7

4:codeElement>programEnd>programNameReference2
	3	4:codeElement>programEnd>programNameReference2>symbolReference5

4:codeElement>programIdentification>programNameDefinition
	3	4:codeElement>programIdentification>programNameDefinition>symbolDefinition5



5:codeElement>dataDescriptionEntry>cobol2002TypeClause>programNameReference3
	6	5:codeElement>dataDescriptionEntry>cobol2002TypeClause>programNameReference3>symbolReference4

5:codeElement>dataDescriptionEntry>dataNameDefinition>symbolDefinition4
	12	5:codeElement>dataDescriptionEntry>dataNameDefinition>symbolDefinition4>alphanumericValue4

5:codeElement>programEnd>programNameReference2>symbolReference5
	3	5:codeElement>programEnd>programNameReference2>symbolReference5>alphanumericValue5

5:codeElement>programIdentification>programNameDefinition>symbolDefinition5
	3	5:codeElement>programIdentification>programNameDefinition>symbolDefinition5>alphanumericValue5



6:codeElement>dataDescriptionEntry>cobol2002TypeClause>programNameReference3>symbolReference4
	6	6:codeElement>dataDescriptionEntry>cobol2002TypeClause>programNameReference3>symbolReference4>alphanumericValue4





-------------------
Detailed file infos
-------------------

StackedProgram.rdz.tcbl
	29 lines, 139 tokens, 28 code elements
	85 ms parsing, 12 ms decisio
