### ISSUE TITLE
Add new Build Configurations

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#475]
**Add new EIRules_Debug / EIRules_Release**
- Apply EIRules only on EIRules_* configs. 

**Create new ResultFile Type** (file will be mark with `-EI` like : `ResultFile-EI.txt`)
- Duplicate not passing Unitest results files to respect EI Rules

**Comment by smedilol** [comment]
Build configuration EIRules_Debug is not present in all project (like CLI).
Config EIRules_* don't always defines Constant for EI.

**Comment by smedilol** [comment]
`TypeCobol.core.sln` which is used by AppVeyor must be updated as well.

**Comment by smedilol** [comment]
There is a regression with new configs EIRules_*
Check CheckParserCobol85 tests

**Comment by smedilol** [comment]
EIRules_Release doesn't compile
