### ISSUE TITLE
CLI: new option to stop after a specific Step of FileCompiler

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#476]
New option : 
```
--ExecToStep=<step-name>
```
where `<step-name>` can be:
* `Scanner`
* `Preprocessor`
* `SyntaxCheck`
* `SemanticCheck`
* `Generate`

**Comment by smedilol** [comment]
We need unit tests and one case is not implemented

**Comment by smedilol** [comment]
The new Test CheckExecToStepPrase works fine, but the new option doesn't works from CLI command

**Comment by collarbe** [comment]
Can we imagine to supress the option --generate and create a new ProcessingStep which would be "generate", It would be placed after SemanticCheck.

**Comment by smedilol** [comment]
Yes why not,
In this case:
The default for `--ExecToStep` is `Generate` if option `-o` is used.
Otherwise the default is `SemanticCheck`

**Comment by collarbe** [comment]
Can I have some details on this issue? I looked at server Config serialization and it seems to work, the `ProcessingStep`field of the config is correctly restored.
