### ISSUE TITLE
New concept : source dependencies

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#481]
## The need
We currently have the notions of 
* intrinsic Type and functions/procedure.
  * Intrinsic functions/procedures can be call without prefixing them with the program name
* files to parse AND to generate

we lack the notion of a file dependency: It's a file that can contains public function/procedure which are accessible by the main files that we want to parse and generate.

## Target
The target is:
* intrinsic Type and functions/procedure.
  * Intrinsic functions/procedures can be call without prefixing them with the program name
* files to parse AND to generate
* dependencies: files that are only parsed.
  * public function/procedures must be prefixed by the program name

## Proposed solution to implement this:
Add a new option "--dependencies" in CLI which is a PATH (folder with wildcard or specific files).
Dependencies will be loaded after intrinsic files (option `-y`) and before main files to parse and generate (option `-i`)

warning: the PATH to dependencies must not be accessible as an ICobolLibrary during parsing of the main files.

**Comment by smedilol** [comment]
The loading of multiple files with wildcard doesn't works.
See `XmlParser` for an example

**Comment by collarbe** [comment]
We can now load depencies by passing a folder path with wildcar like this `C:\users\typecobol\dependencies\*.tcbl `
