### ISSUE TITLE
Document SymbolTable

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#488]

**Comment by collarbe** [comment]
Added some Documentation Page https://github.com/TypeCobolTeam/TypeCobol/wiki/SymbolTable may need to be updated

**Comment by smedilol** [comment]
Ok, just 2 minor issues:
* GLOBAL scope contains all the variables declared in Data division as GLOBAL
* Program scope contains all variables declared in Data Division **without** GLOBAL

**Comment by collarbe** [comment]
Documentation updated.
