### ISSUE TITLE
Orphan END-STATEMENT

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#49]
**BLOCKS ISSUE #23**

It seems one can find statement scope terminators (`END-IF`, `END-ADD` and so on) anywhere in the code.
I've seen real-life examples of `IF condition THEN statements END-IF END-IF`, and the program compiled. I suppose the "orphaned" statement terminator is treated like a `CONTINUE` statement and has thus no effect.

However, is it possible to find such an orphan statement *in the middle of another statement* ?
For example between two nested statements, like:
`IF condition THEN statement1 END_ADD statement2 END_IF`
Or even in the middle of a statement, like:
`ADD x TO y END-IF GIVING z`

**Comment by osmedile** [comment]
After testing, it seems that ou can't have an END-IF or an END-ADD just in the middle of your code without a matching IF or ADD.

**Comment by osmedile** [comment]
Don't allow an END-STATEMENT without the corresponding BEGIN-STATEMENT
