### ISSUE TITLE
Allow to share TYPEDEF between programs

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#490]
After some tests: it appears that a procedure can use custom type as parameter type.
The problem is that these custom types need to be shared between the caller and the callee.

So we need to define a TYPEDEF as public.
By default a TYPEDEF is private.

## When to use the program qualifier before a type reference?

- When Type is declared has intrinsic
  - program qualifier is optional and the type must be public
- When Type is declared inside the same program
  - program qualifier is optional
- When Type is declared in another program (even in the same source file)
  - program qualifier is mandatory and the type must be public

## Test
See test:
TypeCobol.Test/NewTestsToFix/Parser/Samples/Typedef-public.rdz.tcbl

**Comment by collarbe** [comment]
As for functions I had to do the check of TYPEDEF only when semantic phase is done so I'm now using `Cobol85ASTChecker`. It's generate a side-effect in Unit test. The case describe that a TYPE can oly be accessible if it was already declare, however this is not true anymore. 

See test `Typedef.tcbl` & `TypedefPGM.txt.` 

What do I do ?

**Comment by smedilol** [comment]
It's ok to change this behavior. You can now make a reference to a TYPE declared later in the source file.

**Comment by collarbe** [comment]
Ok thanks :)

**Comment by collarbe** [comment]
Waiting for global project meeting to know if grammar has to change with the use of PRIVATE Keyword.
