### ISSUE TITLE
CLI: return code "3" if there is a Diagnostic issued during parsing

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#491]

**Comment by collarbe** [comment]
In the futur, I think that we should implement a set of error code. 
Like : 
- 1 : FatalError
- 2 : MissingOutputFIle
- 3 : ParsingError
- 4 : .... 
- 5 : ...

What do you think ?

**Comment by smedilol** [comment]
Yes that's a good idea.
Can you create an issue about that?

**Comment by collarbe** [comment]
I have created the branch 491_CLI_ReturnCode. Please feel free to tell me about what I've done in CLI to manage exception and errors. @smedilol @mayanje

**Comment by collarbe** [comment]
Issue #497 created.

**Comment by smedilol** [comment]
I've tested this branch:

When there is an error in a file (intrinsic, dependency or input) , you always get a generic to tell you that you have errors:
Example:
```
Line 7[10,10] <34, Error, Semantics> - Error during parsing of input\MyIntrinsicFunctions.rdz.tcbl: Line 7[10,10] <27, Error, Syntax> - Syntax error : no viable alternative at input '.'
Line 1[0,0] <34, Error, Semantics> - Diagnostics detected while parsing Intrinsic file
```
I don't think the second error is useful.


When using the server mode (option -k), the return code is always Success.

**Comment by collarbe** [comment]
Thank you for your feedback. The first remarks as already been fixed by adding the possibility or not to log in error output file the exception message. For the second one, you right, I forget to use the return code of the namedpipe server. Fix, coming soon.
