### ISSUE TITLE
Call to a procedure must check if picture is compatible

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#515]
Problem:
We don't check if the `picture` of a parameter is compatible between callee and caller:
**Callee**
```cobol
       declare procedure check private
            input    data1  pic 9(10)
       procedure division.
           continue.
       end-declare.
```

**Caller**
```cobol
       01  myData pic 9(08).
           call check input myData  *> myData is "smaller" than parameter description
                                    *> Callee will then access random memory location
```

This issue is related to issues #335 and #350. These issues will allow us to check if a variable is compatible with the parameter of the function.
Eg: we could just create a warning if the specified parameter is "_longer_" than expected.

For this issue, we will only check if the variable passed to a procedure or function is defined **exactly** as the parameter.
By **exactly** we means, same:
- picture
- Type (if Cobol 2002 or higher)
- Usage (comp, comp-3, ...)
- Justified
- Group usage national
- Occurs (Min, Max, Unbounded, depending on)
- Sign is separate
- Sign position
- Synchronized
- Object reference

**Comment by collarbe** [comment]
Waitting for new TypeCobol Unit tests
