### ISSUE TITLE
In case of parsing error/exception : send email with all info

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#518]
In order to get information from the TypeCobol user, we need the ability to get stacktrace and CobolSource file by email.  

- The email sending mechanism has to be generic with the use of an app.config file. 

- A new option in CLI will be created : `Telemetry`

- Create basic HTML template email with replace mechanism to add inforamtion about the exception

For now, this email sender will only work for exception catched by the CLI. In the future we may create an option to send all the thrown exceptions by email... 

Also add documentation on mail sender

**Comment by collarbe** [comment]
Created page about telemetry and email sender : https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobol-Telemetry
