### ISSUE TITLE
A qualified reference that ends with keyword will throw a NullReferenceException

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#527]
**CHILD OF #524**

A qualified reference that ends with keyword will throw a NullReferenceException

```cobol
01 var1 pic X.

move 'toto' to var1::Type   *> var::Type will throw the Exception because Type is a keyword
```

**Comment by collarbe** [comment]
I've tested different cases :

var1::type -> KO
var1::var2 -> OK
var1::var2::type -> KO
var1::type::bla -> KO (but, grammar completly ignore type for the tail, and after all var1.bla becomes a tested symbol. However a message for type is generated by antlr)

**Comment by smedilol** [comment]
It works for the original problem, but after viewing your fix, I try with:
`move var1::9 to var2`
`9` is not part of TokenFamily.SyntaxKeyword but it produces the same exception.
