### ISSUE TITLE
Arguments of standard call are not controlled

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#532]
```cobol
call 'MyProgram' using undefinedVariable
```

there is no error if `undefinedVariable` is not declared.

Note:  the Cobol compiler will detect it.

**Comment by collarbe** [comment]
I've tested different cases : 
- var1::type -> KO
- var1::var2 -> OK
- var1::var2::type -> KO
- var1::type::bla -> KO (but, grammar completly ignore type for the tail, and after all var1.bla becomes a tested symbol. However a message for type is generated by antlr)

**Comment by fm-117** [comment]
Using this test sample:

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZMFT1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       PROCEDURE DIVISION.
           CALL 'DVZZMFT2' USING undefinedVariable
           GOBACK
           .
       END PROGRAM DVZZMFT1.
```

We get the diagnostic `Semantic error: Symbol undefinedVariable is not referenced` as expected.

@rooksdo should we close this issue ?

**Comment by rooksdo** [comment]
@fm-117 Thanks for the update.

This issue seems to be resolved.
