### ISSUE TITLE
Document default access modifier rule for Type

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#549]
**CHILD OF #520**

Document  TCTYPE_DEFAULT_ACCESS_MODIFIER here : 
https://github.com/TypeCobolTeam/TypeCobol/wiki/Cobol02TYPEDEF
and in source code by adding TCTYPE_DEFAULT_ACCESS_MODIFIER  in comment.

like for functions [TCRFUN_DEFAULT_ACCESS_MODIFIER](https://github.com/TypeCobolTeam/TypeCobol/wiki/TypeCobolFunctionsSyntax)

**Comment by collarbe** [comment]
Documentation also updated 👍
