### ISSUE TITLE
Custom EI rule: COPY name of 8 chars that ends with `L` are real COPY (no suffixing)

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#562]
example
```cobol
COPY YAAAXXXL
````
`YAAAXXXL`  is a real copy. No suffixing apply here.

This COPY must be added to Remarks.
The file YAAAXXXL.cpy (or another extension) must be available to the parser.

**Comment by collarbe** [comment]
Does the copy name is limited to 7 characters befor the L letter or does it could be more than 7 ? 
Like : 
- YAAAAAAXXXXXXXL.cpy Do we have to suffix it or not ?
