### ISSUE TITLE
ON ERROR

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#57]
Is the following syntax valid COBOL ?
```cobol
READ fileName
   NOT AT END
      * imperative statements *
   AT END
      * imperative statements *
   AT END
      * imperative statements *
   NOT AT END
      * imperative statements *
```
The spec says `AT? END` must come first (if present), that there must be only one, and that it can be followed by only none or one `NOT AT? END`.

**Comment by delmasgu** [comment]
Following rules apply to READ statement  
- AT END condition is optional, no more than one AT END condition for one READ statement
- NOT AT END condition is optional, no more than one NOT AT END condition
- If both AT END and NOT AT END conditions are used, the order should be AT END and then NOT AT END
