### ISSUE TITLE
TypeCobol doesn't contains all keywords

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#578]
Check Cobol V6 Language Reference p581 to check all keywords:
https://github.com/TypeCobolTeam/TypeCobol/blob/master/TypeCobol/Documentation/Reference/IBM%20Enterprise%20Cobol%206.1%20for%20zOS%20-%20Language%20Reference.pdf

Some keywords are missing.  We also define EBCDIC, PROCESS and ELEMENT as keyword in TypeCobol but they are not keywords.

**Comment by collarbe** [comment]
59 COBOL Keywords to add : 

ALLOCATE
CD
CF
CH
CLOCK_UNITS
COLUMN
COMMUNICATION
CONTROL
CONTROLS
DE
DEFAULT
DESTINATION
DETAIL
DISABLE
EGI
EMI
ENABLE
END_JSON
END_RECEIVE
ESI
FINAL
FREE
GROUP
HEADING
INDICATE
INITIATE
JSON
LAST
LIMIT
LIMITS
LINE_COUNTER
MESSAGE
NUMBER
PAGE_COUNTER
PF
PH
PLUS
PRINTING
PURGE
QUEUE
RD
RECEIVE
REPORT
REPORTING
REPORTS
RF
RH
SEGMENT
SEND
SOURCE
SUB_QUEUE_1
SUB_QUEUE_2
SUB_QUEUE_3
SUM
TABLE
TERMINAL
TERMINATE
TEXT
VOLATILE

**Comment by smedilol** [comment]
Can you identify keywords of Cobol V6 in comment and with a TokenFamily?
Perhaps in the future we'll need to have a parameter "sourceLevel" of the source code.

**Comment by collarbe** [comment]
Here are the following keywords to delete : 

ATTRIBUTE
ATTRIBUTES
EBCDIC
ELEMENT
ENCODING
NAME
NAMESPACE
NAMESPACE_PREFIX
NONNUMERIC
PARSE
VALIDATING
XML_DECLARATION
YYYYDDD
YYYYMMDD
