### ISSUE TITLE
Fix Diagnostics + Missing Copies repetition

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#605]
While parsing and sendig diagnostics or missing copies, the data seems to be duplicated. So all the diagnostics will be duplicated as the missing copies list. 

We need to clear these properties before each refreshing.

**Comment by smedilol** [comment]
For tests: 
Can you check that 

- when the text `COPY ABCDEFGH.` is deleted then the copy is removed from the list of missing copys
- a missing copy is registered only when the dot is added at the end of `COPY ABCDEFGH.`
   - if a user is typing `COPY A` you don't want to register `A` as a missing copy.


Thanks
