### ISSUE TITLE
Measure Razor performance and look for an alternative

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#615]
It seems that razor is not fast enough. It generates temp files to generate skeleton.
We need to see how "fast/slow" razor really is and look for an alternative.

One possibility is to generate the code directly in C#.
Our skeletons are not complicated.

Edit: Study http://www.stringtemplate.org/

**Comment by mayanje** [comment]
Ok according to #1028, this issue is now obsolete
