### ISSUE TITLE
Implement custom notification when Loading Intrinsic/Dependencies fail

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#624]
We need to notify the client that something went wrong when loading the Intrinsics or Dependencies. 

This notification will use the following identifier : **_typecobol/loadingIssue_**
And will be composed of a property `Message `as a string.

**Comment by mayanje** [comment]
With the introduction of the FileWatcher to track dependencies files changes, the client must be notified when there are no more load dependencies issues.

**Comment by mayanje** [comment]
Leave a comment
