### ISSUE TITLE
Analytics should be loaded dynamically

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#632]
2 teams of our company will use the parser but they don't need analytics.
Analytics should be active only if needed.

Thus, we could avoid to provide Analytics DLL to these teams.

Note: Use MEF to configure which analytics implementation we want.

**Comment by fm-117** [comment]
Porting Analytics to our new extensible logging system could help solve this issue as loggers can be loaded dynamically now.
See #2091.

**Comment by fm-117** [comment]
out-of-date: Analytics project has been removed. New logging system still allows dynamic loading of external loggers (but needs to be improved)
