### ISSUE TITLE
Update solution dependencies

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#638]
As the work progress on our solution, some dependencies coming from NuGet are updated. 
It would be great if we can take a moment to check those updates and apply them if possible.

**Comment by collarbe** [comment]
# Dependencies update results

### Analytics
 - [ ] ApplicationInsight (stuck at 2.3.0, 2.4.0 need .NET 4.5)
 - [x] NLog ( 4.4.9 -> 4.4.12) OK
 - [x] NLog.Config (4.4.9 -> 4.4.11) OK
 - [x] NLog.Schema (4.4.9 -> 4.4.11) OK

### CLI
 - [ ] SimpleMsgPack (no update)
 - [x] Castle.Core (3.3.3 -> 4.1.1) OK

### CodeGen
- [x] Microsoft.AspNet.Razor (3.0.0 -> 3.2.3) OK
- [x] RazorEngine (3.8.2 -> 3.10.0) OK

### TypeCobol
 - [x] Castle.Core (3.3.3 -> 4.1.1) ForEach extension for collection disapears OK
 - [x] JetBrains.Annotations (10.1.5 -> 11.0.0) OK
 - [x] System.Xml.ReaderWriter (4.0.0 -> 4.3.0) OK

### TypeCobol.Test
 - [x] Moq (4.2.1510 ->4.7.99) OK

### LanguageServer
 - [x] Newtonsoft.json (8.0.2 -> 10.0.3) OK


**NOTE :** ANTLR Update will need some work. It's a major version to pass and some unit test results are different. First need to analyse the impact before upgrading Antlr.

**Comment by smedilol** [comment]
Ok, for Antlr dependencies we will wait to see if it's replaced by CUPS
