### ISSUE TITLE
Build after clone

### ISSUE THREAD

**Issue by Slesa** [TypeCobolTeam/TypeCobol#642]
It would be very nice to have the possibility to build this project after cloning it from scratch.

Building the solution tells me something like "Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.", which last time ment some secret environment var has not been set - what is it good for? Where does it come from? Will I like it?

The build batch tells me "bin not found", "El_Release not found"... so I am not able to build something I could use.

In TypeCobol.Grammar is a file "IMPORTANT_BEFORE_BUILD" - do I have to care about it? Do I have to read it?

All in all - would be nice to get some kind of help when I try to build this project. Maybe an additional INSTALL.md or something like that. Thanks.

**Comment by collarbe** [comment]
Hi Slesa, 

Sorry for the late answer, the team was on vacation. That's great to see someone interested in our work ! 👍

For the environment variable, if the diag message was like the following : "Analytics - Post Build event : Environment variable not defined". There is nothing to worry about, this env. var is only here to replace a file that contains our own Application Insight Key. (See App.config file in Analytics project https://github.com/TypeCobolTeam/TypeCobol/blob/master/Analytics/App.config). 

The build script that you use is not really a tool to build the project. It's only used by AppVeyor to create a release folder to publish TypeCobol on GitHub releases. (See https://github.com/TypeCobolTeam/TypeCobol/releases )

Regarding to TypeCobol.Grammar, indeed the file "IMPORTANT_README_BEFORE_FIRST_BUILD.txt" is really important, without following the indications, you'll not be able to build. It is related to ANTLR package config. You will first need to restore Nuget packages if not present in your solution folder/packages folder. 

Lastly, you are right, we may need to produce some documentation on how to build the solution. Something like a guide would be nice.

Hope this would help !

Please feel free to let us know if you have any other issue on TypeCobol, we would be glad to help you. 

Have fun, 
Ben

**Comment by smedilol** [comment]
We will be able to build the projet just after a clone, after issues #850 is done.
