### ISSUE TITLE
Identifiers that look like numbers

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#65]
**CONTINUATION OF ISSUE #50**

Our incremental compiler has currently some limitations regarding identifier that look like numbers (these limitations are commented in `TypeCobol/Compiler/Scanner/Scanner.cs` from 622ce027520615e6e0c389a6308c6a38b91a445b).

We don't recognize things like `123-456` or `23E-2` because we deem it more probable that these are subtractions with no space (and thus we want to give an error) than mischievousely named identifiers. Moreover, detecting this kind of identifiers would more impact performance that it seems worth.

However, that's not how the IBM compiler works.

So: let's discuss.

**Comment by smedilol** [comment]
It's a limitation of our parser:
https://github.com/TypeCobolTeam/TypeCobol/wiki/Limitations
