### ISSUE TITLE
Codegen of a program WITHOUT data division and public procedure doesn't works

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#659]
This program without a `data division`, an `Environment division` and a public procedure causes an Assert error in LinearNodeSourceCodeMapper line 431 with `Debug.Assert(Nodes[beforeNode.NodeIndex].Buffer != null);`

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TestMe.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
      *SOURCE-COMPUTER.    IBM-3033 WITH DEBUGGING MODE.
       PROCEDURE DIVISION.
      
       declare procedure StartCheckpoint public
           input  PgmName          pic X(08).
       end-declare.
      
      
       END PROGRAM TestMe.
```

And in the generated code, the `data division` is before the `Environment division`.

**Comment by mayanje** [comment]
I fixed this special issue using a work around that preserve the current behavior. But using auto generated nodes without positions starts to become a little bit tricky. According to what have been done for handling public to public function calls, it is time to start thinking how to get rid of the skeleton templates.
