### ISSUE TITLE
When LanguageServer starts, it should returns TypeCobol version

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#662]
To ease debugging, it should be nice if TypeCobol version was returned by TypeCobolServer when it starts.
IDZ could then display it.

**Comment by collarbe** [comment]
I see two options for this issue. 

- First, is to add TypeCobol version in InitializeResult object returned by LSP after the initialization. 
- Second, create a custom method in TypeCobol LSP that returns TypeCobol's version.
