### ISSUE TITLE
Codegen: generate better name for procedure

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#666]
We use a hash for the name of stacked programs generated from a procedure declaration.

This hash is limited to 8 characters because of a limitation of IBM compiler.
But IBM Compiler accepts more than 8 characters. It's just that characters after 8th are ignored.

So we could use the hash + the procedure name to name our stacked programs.
Example:
```cobol
      *declare procedure StartCheckpoint public
      *    input  PgmName          pic X(08)
      *    output RC               type ReturnCode.
      *_________________________________________________________________
       IDENTIFICATION DIVISION.
       PROGRAM-ID. e01f2d5e.
```
would be
```cobol
      *declare procedure StartCheckpoint public
      *    input  PgmName          pic X(08)
      *    output RC               type ReturnCode.
      *_________________________________________________________________
       IDENTIFICATION DIVISION.
       PROGRAM-ID. e01f2d5e-StartCheckpoint.
```

**Comment by collarbe** [comment]
After some test from @reydelpa it seems that the generated code is not correct. We could sometimes have pointer or variable with name longer than 30 chars. There is also a generated value of 8 lenght that is not correct anymore. 

To fix those problems, we will need to create a new property that is only going to be used for the subprogram name.

**Comment by collarbe** [comment]
The fix seems to do the trick except when the procedureName is longer than 21char. The generated code for the PROGRAM-ID will be over 30 chars and will not compile... 

Option 1 : Limit the name lenght of a procedure/function.
Option 2 : Rollback to only use hash for generated code.

**Comment by smedilol** [comment]
After discussion with @reydelpa, we will only use name of 30 chars (Hash + 22 first letters of procedure name) for PROGRAM-ID and for static call (call to a private procedure)
