### ISSUE TITLE
Symbol " not recognize when loading dependencies/intrinsics files

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#667]
It seems that the symbol " in command line given to CLI or LSP cause a faillure in depencies/intrinsics loading.

**Comment by smedilol** [comment]
The solution works, but did you find the cause of the problem?
As I didn't encounter this problem on my machine, maybe there is something that is changing arguments given to CLI or LSP. In this case, maybe the problem will arise for another argument.

**Comment by collarbe** [comment]
After studying exactly what's happening on both side, CLI and LSP, it seems that CLI correctly manage path with `" `symbol. On the other hand, LSP has some issues while receiving parameters. The current used client is sending a string that contains an espace char for `"`. 

A file path like this : `"C:\Path\To\TCOB\dependencies\"`
Is transform into this  `"\"C:\Path\To\TCOB\dependencies\\"" ` by the LSP Client
And look like this `"C:\Path\To\TCOB\dependencies\"` in CLI

TypeCobol LSP Server is now able to manage this issue, but the client needs some update to send a string that has no espace char. 

This issue will affect all the options that are given as a file path.
