### ISSUE TITLE
When opening a file : Send all initialization diagnostics to the Client

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#670]
Diagnostics created during initialization of LanguageServer are not transmitted to the client.
These diagnostics can be:
- Error during loading of intrinsic/dependencies
- Error during parsing of configuration
- ...

One idea is to associate all these diagnostics to each opened file.
As soon as a file is opened these diagnostics are inserted so the user can now that there is a problem.

**Comment by mayanje** [comment]
This has been implemented with issue #624
