### ISSUE TITLE
Create a free size object

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#673]
@reydelpa encountered the following case : 

Has a procedure that expect an input parameter of size 50. 
Has a caller that could give this input parameter a value with an unknow size (less or more than 50)

We may need to create a nex type or Syntaxic word that is not going to check the length.

**Comment by smedilol** [comment]
2 work around:
- Use a pointer
- Pass a group, because we don't check size of data group yet

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
