### ISSUE TITLE
Completion for SET

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#678]
Implement completion for SET statement.

Need to define specifications

**Comment by collarbe** [comment]
Some spec...

### Switch-setting : 
SET _identifier_ TO (_ON_ / _OFF_)

### Condition-setting:
SET _identifier_ TO (_TRUE_ / _FALSE_)

### Object Reference setting : 
SET _identifier_ TO _identifier_

**Comment by smedilol** [comment]
There are 7 forms of SET in Cobol V5:

Here is the list of all possible kind of variable that can you use after *SET* (when you don't know which form of SET to use). They are sorted by order of preference (based on our company habits):

`
SET condition-name | index-name | identifier | ADDRESS OF identifier-2 | mnemonic-name | procedure-pointer-data-item | function-pointer-data-item | object-reference-id
`


`condition-name` : level 88 variable

`identifier` : 
- either an index data item or an elementary numeric integer item.
- or described as USAGE IS POINTER.

`identifier-2` :
must be level-01 or level-77 items defined in the LINKAGE SECTION.

After that you can try to determine which form of SET it is.


See page 415 of https://github.com/TypeCobolTeam/TypeCobol/blob/master/TypeCobol/Documentation/Reference/IBM%20Enterprise%20Cobol%205.1%20for%20zOS%20-%20Language%20Reference.pdf

**Comment by smedilol** [comment]
I forgot to mention that variable Typed with intrinsic `type bool` can be used in a `SET`

**Comment by smedilol** [comment]
level01 or 77 of linkage section are not listed too.
```cobol
       linkage section.
       77 date3 pic X(08).
      
       procedure division.
           set d
           goback
           .
```
`set d` should propose `date3`
