### ISSUE TITLE
Setting a bool to false generate an 80 columns exceed

### ISSUE THREAD

**Issue by epixilog** [TypeCobolTeam/TypeCobol#692]
Hello I got the following code:

 
       01 PERSON TYPEDEF STRICT.
            05 FirstName              PIC X(30).
            05 LastName               PIC X(30).
            05 Birthday               TYPE Date.
            05 Registered             TYPE Bool.
       01 W-PERSON1      TYPE PERSON.
       01 W-PERSON2      TYPE PERSON.

The following line causes an 80 columns exceed error:
`SET W-PERSON2::Registered            TO FALSE`

Thanks

**Comment by mayanje** [comment]
So, right now we can only detect that during code generation, the generated line exceed 72 columns. The situation here is a little bit different, there is no line overflow, but there are some existing characters in colums 73 to 80 that make the Code Generator thinks that the line exceed column 72.
