### ISSUE TITLE
Codegen: generate and use unique name for Index that have been qualified

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#701]
**CHILD OF #663 and #699**

During codegen create an unique name for the index that have been qualified and are in the editable source file : add Hash of 8 chars (starting with a letter) based on the fully qualified name of the index

Replace all qualified references of indexes that have been qualified and which name are not unique OR inside TYPEDEF with the unique name of the index (Hash + the rest of its name).

**Comment by mayanje** [comment]
Hum.... this leads me to a question, do we have a contextual hash name generation, because I can remember a discussion about avoid hash name conflicts with a variable name. So maybe for version v1.xxx we have to ignore this kind of situation.

**Comment by smedilol** [comment]
Right, see #702

**Comment by smedilol** [comment]
New test, I commented what is not working currently.
```
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       DATA DIVISION.
       working-storage section.
      
       01 Var1.
      *Bug codegen : MyIdx should be prefixed with a hash
           05 Tab1 occurs 99 indexed by MyIdx.
      
       procedure division.
      *MyIdx should be prefixed with a hash
           set MyIdx             to 1
      *MyIdx should be prefixed with a hash
           set MyIdx             up by 1
           set Var1::MyIdx       to 1
           set Var1::MyIdx       up by 1
           set Var1::Tab1::MyIdx to 1
           set Var1::Tab1::MyIdx up by 1
      
           goback
           .
       END PROGRAM DVZF0OSM.
```

Generated code should be:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       DATA DIVISION.
       working-storage section.
      
       01 Var1.
      *Bug codegen : MyIdx should be prefixed with a hash
      *    05 Tab1 occurs 99 indexed by MyIdx.
           05 Tab1 occurs 99 indexed by ea84b906MYIDX.     
      
       procedure division.
      *   set MyIdx             to 1
           set ea84b906MYIDX  to 1
      *   set MyIdx             up by 1
           set ea84b906MYIDX up by 1
      *    set Var1::MyIdx       to 1
           set ea84b906MYIDX       to 1
      *    set Var1::MyIdx       up by 1
           set ea84b906MYIDX       up by 1
      *    set Var1::Tab1::MyIdx to 1
           set ea84b906MYIDX to 1
      *    set Var1::Tab1::MyIdx up by 1
           set ea84b906MYIDX up by 1
      
           goback
           .
       END PROGRAM DVZF0OSM.
```

**Comment by mayanje** [comment]
New test using pure cobol toplevel variable

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       DATA DIVISION.
       working-storage section.
      
      
       01 MyType TYPEDEF STRICT.
           05 MyTab occurs 99 indexed by MyIdx.
      
       01 Var1.
          05 Var2 type MyType.
      
       procedure division.
           set Var1::MyIdx       to 1
           set Var1::myidx       up by 1
      
           goback
           .
       END PROGRAM DVZF0OSM.
```

Generated code should be



       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       DATA DIVISION.
       working-storage section.
      
      
      *01 MyType TYPEDEF STRICT.
      *    05 MyTab occurs 99 indexed by MyIdx.
      
       01 Var1.
      *   05 Var2 type MyType.
          05 Var2.
      * Generated code is
      *     06 MyTab occurs 99 indexed by ac5aacb0MyIdx.
      * It should be                              
      *     06 MyTab occurs 99 indexed by a39c8812MyIdx.
      
       procedure division.
      *    set Var1::MyIdx       to 1
           set a39c8812MyIdx       to 1
      *    set Var1::myidx       up by 1
           set a39c8812MyIdx       up by 1
      
           goback
           .
       END PROGRAM DVZF0OSM.

**Comment by smedilol** [comment]
Sorry but there is still one bug:

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       DATA DIVISION.
       working-storage section.
       01 Var1.
           05 Tab1 occurs 99 indexed by MyIdx.
      
       01 MyType TYPEDEF STRICT.
           05 Tab10 occurs 99 indexed by MyIdx.
      
       procedure division.
           set Var1::MyIdx to 1
           .
       END PROGRAM DVZF0OSM.
```

The instruction  `set Var1::MyIdx to 1` doesn't use a valid index.
Here's what I get:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       DATA DIVISION.
       working-storage section.
       01 Var1.
           05 Tab1 occurs 99 indexed by ea84b906MyIdx.
      
      
      *01 MyType TYPEDEF STRICT.
      *    05 Tab10 occurs 99 indexed by MyIdx.
      
       procedure division.
      *    set Var1::MyIdx to 1
           set bfd94713MyIdx to 1
           .
       END PROGRAM DVZF0OSM.
```
`bfd94713MyIdx ` is not valid
