### ISSUE TITLE
Make sure generated name with a Hash doesn't conflict with other variable 

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#702]
This apply to:
- Generated program name for procedure
- Generated Index name

**Comment by mayanje** [comment]
For this issue the current implementation checks that for a source file and a name there is no duplicated hash value generated. If there is a duplication an error is generated.
But as everybody knows : the SHA hash functions family has no known weaknesses that can lead to forgery. SHA-256, for example, yields a 256 bits signature. **This greatly reduces the probability of a collision**.

**Comment by mayanje** [comment]
Our main problem is that in some situtaions (if the hash value begins with a number) we take a substring of the generated hash value, maybe we increase the probability of a collision.

**Comment by mayanje** [comment]
So any way, the only solution we have against a collision is to ask the user to rename its name to be hashed.

**Comment by smedilol** [comment]
Following #464, hash is already unique for function/procedure

**Comment by smedilol** [comment]
No longer needed as TypeCobol is abandonned.
