### ISSUE TITLE
Forbid Type and level 77 if the code is translated to Cobol 85

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#704]
```cobol
77 MyDate Type Date.
```
will be generated in Cobol 85 like this:
```cobol
*77 MyDate Type Date.
77 MyDate.
   78 YYYY pic 9(4).
   78 MM pic 9(4).
   78 DDpic 9(4).
```

And of course it won't compile because level 78 doesn't exist in Cobol 85.

So according to Cobol 2002 specs we can use a `TYPE` with a level 77. This is only forbidden if the code is translated to Cobol 85.

But the following is allowed and works fine:
```cobol
01 MyType TYPEDEF STRICT pic X.

77 var1 type MyType.
```
Generated code will be
```cobol
*77 var1 type MyType.
77 var1 pic X.
```

This is ok, because MyType doesn't have children.

**Comment by collarbe** [comment]
To clarify : 

- A variable could be types from level 1 to 49 (including type children) 
- A level 77 variable could be typed, only if type has no children
- A level 88 variable cannot be types
- A level 66 variable ...
