### ISSUE TITLE
Method SymbolTable.GetVariable should be able to retrieve the complete QualifiedName of a variable reference

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#708]
```cobol
01 MyType TYPEDEF STRICT.
  05 tab occurs 5 indexed by MyIdx.

01 Group.
   05 var1 type MyType.
   05 var2 type MyType.


set var1::MyIdx to 1.
set group::var1::MyIdx to 1.  
```

For `var1::MyIdx`, the complete QualifiedName is `group::var1::tab::MyIdx`
For `group::var1::MyIdx`, the complete QualifiedName is `group::var1::tab::MyIdx`

**Comment by collarbe** [comment]
Need to change GetParentDefinition to also return the path that it takes to get the ParentType.
