### ISSUE TITLE
Enhance diagnostics details for ambiguous symbol reference

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#716]
Since #708, we are now able to geta complete variable path thanks to `GetVariableExplicitWithQualifiedName()` So if a varialbe is found multiple times we can indicate the sources where the variable has been found.

**Comment by Brochato** [comment]
If a group is declared, in case of ambigous reference an unexpected candidante will be part of the result tacking the place of a real candidate.
The unexpected candidate is formed just like a real candidate (a QualifiedName path) exept it have no program name and no variable name in it.
