### ISSUE TITLE
Allow a variant of the SET Instruction to accept qualified index names.

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#720]
The current grammar does not support for our language extensions, qualified index names.

"SET" { index-name }+ ( "UP" "BY" | "DOWN" "BY" ) ( identifier | integer )

**Comment by collarbe** [comment]
Need to had a new rule like qualifiedIndex. The last modification is to permissive. DataDefinition that are not index are also allowed to be use in the case SET ... UP BY... and that is not correct..
