### ISSUE TITLE
New codegen format : Cobol85 with expansed copy

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#724]
The need for this new codegen is to expanse a Cobol 85 file with COPY directive into a Cobol 85 where the content of the COPY are directly in the source.

We can use the CLI to do that. No need to integrate it into RDZ.

**Comment by mayanje** [comment]
For this functionnality I have added the following option: 
•	"ec|expandingcopy=", "Generate a file with all COPY directives expanded in the source code. This option will be executed if the Preprocessor step is enabled.", v => typeCobolConfig.ExpandingCopyFilePath = v

This option takes as argument the expanded file to be generated, and it takes place if the generation sequence includes at leat the preprocessing phase (See option exectostep=Preprocessor).

Example : -1 -i "C:\Users\MAYANJE\Source\ Y110Data\UTIBLOTS.cbl" -e rdz -c "C:\Users\MAYANJE\Source\Y110Data" -ec "C:\Users\MAYANJE\Source\ Y110Data\RESUTIBLOTS.cbl" --exectostep=Preprocessor

Right now (without full testing and full validation), it appears that COPYs are expanded and subtitutions by the REPLACE directive take place. But further tests are needed.
