### ISSUE TITLE
Self Referencing Type

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#730]
We need to check if a type is self referencing. 
Checker will have to throw an error if case is encounter.

**Comment by smedilol** [comment]
I think that you warned me about possible StackOverflow, but just to be sure, here's a test that can crash our parser:

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. LevelChecker.

       DATA DIVISION.
       WORKING-STORAGE SECTION.

       01 myType TYPEDEF STRICT.
            05 myVar PIC X(10).
            05 secondGroup pic X.


       48 MyVar1 TYPE myType.
       45 MyVar2 TYPE myType.

       PROCEDURE DIVISION.
            move MyVar1::myVar to MyVar2::secondGroup
       END PROGRAM LevelChecker.
```
Because Myvar1 is of level 48, method `SymbolTable.AddAllReference` will go in an infinite loop.

**Comment by collarbe** [comment]
Yes that the issue, it is because, MyVar1 is recognize as a child of myType. So it's self referencing. Thx for the unit test :)
