### ISSUE TITLE
Allow to define a value for Bool

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#741]
We should be able to set value for Bool variables:
```cobol
01 A type bool value true.
01 B type bool value false.
```

The generated code should be
```cobol
      *01 A type bool.
       01  A-value PIC X VALUE 'T'.
           88  A       VALUE 'T'.
           88  A-false VALUE 'F'.
                      
      *01 B type bool.
       01  B-value PIC X VALUE 'F'.
           88  B       VALUE 'T'.
           88  B-false VALUE 'F'.
```

Only allow `true` and `false` as value if the type is Bool.

**Comment by collarbe** [comment]
```cobol
01 A type bool value true.`
```

this code is also creating an InvalidOperationException in CobolWordsBuilder.CreateValue() Line 234.

**Comment by smedilol** [comment]
Ok but valueClauseWithBoolean grammar rule is specific to TypeCobol and should be moved to TypeCobol grammar.

**Comment by smedilol** [comment]
One small issue : if I define a value for a Bool procedure parameter I get an exception.
See issue #791 to block value clause for procedure
