### ISSUE TITLE
Token not found in this stream

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#744]
Application version: v1.0.7.5
Event time: 19/12/2017 à 16:58:38
Exception type: System.InvalidOperationException
Failed method: TypeCobol.Compiler.AntlrUtils.TokensLinesTokenStream.SeekToToken
Problem Id: System.InvalidOperationException at TypeCobol.Compiler.AntlrUtils.TokensLinesTokenStream.SeekToToken Line 69

<a href="https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortal?subscriptionId=68c62f99-2b4f-4f98-8264-39f12a2bdf90&resourceGroup=EID&componentName=TypeCobol&bladeDetails=SearchResultExceptionDetailBlade%2Fid%2F%257B%2522id%2522%253A%2522813ff9d9-e4d5-11e7-8f84-0bf34eb116e6%2522%252C%2522name%2522%253A%2522Token%2520not%2520found%2520in%2520this%2520stream%2522%252C%2522eventTime%2522%253A%25222017-12-19T15%253A58%253A38.679Z%2522%252C%2522eventType%2522%253A2%252C%2522componentId%2522%253A%257B%2522SubscriptionId%2522%253A%252268c62f99-2b4f-4f98-8264-39f12a2bdf90%2522%252C%2522ResourceGroup%2522%253A%2522EID%2522%252C%2522Name%2522%253A%2522TypeCobol%2522%257D%252C%2522timeContext%2522%253A%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222017-12-19T16%253A30%253A00.000Z%2522%252C%2522createdTime%2522%253A%2522Tue%2520Dec%252019%25202017%252017%253A15%253A59%2520GMT%252B0100%2520(Paris%252C%2520Madrid)%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D%252C%2522filters%2522%253A%257B%2522context.application.version%2522%253A%255B%2522v1.0.7.5%2522%255D%257D%257D" target="_blank">View this instance in the Azure portal<\a>
<a href="https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortalFeature?subscriptionId=68c62f99-2b4f-4f98-8264-39f12a2bdf90&resourceGroup=EID&resourceName=TypeCobol&featureName=Search&bladeDetails=SearchBlade&InitialFilter=%257B%2522eventTypes%2522%253A%255B2%255D%252C%2522typeFacets%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522System.InvalidOperationException%2520at%2520TypeCobol.Compiler.AntlrUtils.TokensLinesTokenStream.SeekToToken%2522%255D%257D%252C%2522isPermissive%2522%253Afalse%257D&InitialTime=%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222017-12-20T03%253A58%253A38.679Z%2522%252C%2522createdTime%2522%253A%25222017-12-19T16%253A16%253A04.394Z%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D" target="_blank">View similar exceptions in this time range<\a>

**Comment by nortorious-flame89** [comment]
Hello, could I be assigned this bug? Also, I have azure but I was unable to look at the code. It said I wasn't allowed. Could you allow me access?
thanks,
Noor

**Comment by smedilol** [comment]
Hi,

Thanks for your interest in the project.
Do you use TypeCobol ?


The azure instance is private to our company so I cannot give you access.
But here's the stackTrace logged in azure:
```
System.InvalidOperationException
--
TypeCobol.Compiler.AntlrUtils.TokensLinesTokenStream.SeekToToken
TypeCobol.Compiler.Parser.CodeElementsParserStep.ParseProcessedTokensLinesChanges
TypeCobol.Compiler.CompilationUnit.RefreshCodeElementsDocumentSnapshot
TypeCobol.LanguageServices.Editor.Workspace+<>c__DisplayClass27_0.<UpdateSourceFile>b__0
TypeCobol.Compiler.CompilationDocument.UpdateTokensLines
TypeCobol.LanguageServices.Editor.Workspace.UpdateSourceFile
TypeCobol.LanguageServer.TypeCobolServer.OnDidChangeTextDocument
TypeCobol.LanguageServer.VsCodeProtocol.LanguageServer.CallDidChangeTextDocument
```

I you want to help, feel free to create a Pull Request with the fix.

Thanks,

**Comment by nortorious-flame89** [comment]
I'm new to this but I figured I would just plunge in. Thanks for the stackTrace.

**Comment by smedilol** [comment]
Don't hesitate to ask questions.
Our documentation is currently very poor.
We'll improve this.

**Comment by nortorious-flame89** [comment]
Hey sorry for the late reply but I just finished finals today. :) I read your Readme file and I'm not quite sure how to set the program up to appear in my Azure instance? Could you give me some tips?

**Comment by collarbe** [comment]
Hello nortorious, 

The Azure part of this project is only a way for us to get information about our TypeCobol Parser. We are currently using Azure Application Insight to register any exception/crash happening when someone is using the parser. 

If your question is "How to set up my Azure instance to receive telemetry from Typeobol parser ?" I could explain it to you.  But if you want to participate in this issue, **Azure is absolutely not required.** 

## How to start
To give you some advice, you can start by opening the TypeCobol.sln in Visual Studio, then restoring NuGet packages. After that, there is a file named `"IMPORTANT_README_BEFORE_FIRST_BUILD"`  that will guide you on how to modify a certain file to let the project build properly. 

Finally, you will have to **set CLI as StartUp Project**, then right click CLI project, go to properties, then Debug, then inside "Command line arguments:" you will have to put something like this : 

```
-1 -i "{Path_To_INPUT_File}" -o "{Path_To_OUTPUT_File}" -d "{Path_To_ERROR_OUTPUT_File}" -s  "{Path_To_Skeletons_XML_File}" -e rdz 
```
_This is the minimal arguments that need to be given to the parser._ 

`{Path_To_INPUT_File}` -> Path to your TypeCobol program (See TypeCobol.Test/Parser/Program/TypeCobol to get some examples)
`{Path_To_OUTPUT_File}` -> Path where the parser + generator is going to output result
`{Path_To_ERROR_OUTPUT_File}` -> Path to get information on encountered errors
`{Path_To_Skeletons_XML_File} `-> Path to Skeletons.xml file that will make CodeGeneration possible. This file is located in CLI/config folder. 

Also, if want to debug step by step you can just put a breakpoint the Main method of `Deamon.cs` file. After that you will be able to navigate over all the TypeCobol process. 

Hope this would help :) Feel free to ask if you have any other question

**Comment by smedilol** [comment]
One of our user encountered this bug a lot of times this week.
We need to fix it.
I'll try to reproduce the bug.
Otherwise we can use LanguageServerRobot with our user.

**Comment by smedilol** [comment]
Here 's the source to reproduce the bug:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MYPGM000.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-370.
       SPECIAL-NAMES. DECIMAL-POINT IS COMMA.
       DATA DIVISION.
       working-storage SECTION.
           COPY YTEMP  REPLACING ==:TMP:== BY ==TMP==.
           COPY YTEMP  REPLACING ==:TMP:== BY ==TMP2==.

       END PROGRAM MYPGM000.
```
with the copy:
YEMP.cpy:
```cobol
       01 :TMP:.
            15  :TMP:-var1 pic X.
```

The problem seems to occurs when you have 2 copys declared. It could 2 different copys.
when you add a space after the 2nd copy replacing, then you get the bug.
