### ISSUE TITLE
Move : completion after a special keyword doesn't work

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#783]
Completion after this kind of code doesn't work:
```cobol
move space to 
move quote to 
```

**Comment by smedilol** [comment]
We need to discuss about which type are compatible with things like `space`, `quote`, ...

**Comment by smedilol** [comment]
This issue can be started for quote and space

**Comment by fm-117** [comment]
Related to #1541. See if the updated code also covers those cases.
