### ISSUE TITLE
Allow declarative in public library

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#790]
**FOLLOWING #569**

A program which contains at least one public procedure cannot contains code directly under procedure division.
Only in paragraphs.

But it should be possible to have a declarative.

**Comment by smedilol** [comment]
It works when debugging mode is active.
But when debugging mode is not active, the declaratives part is generated after the generated paragraph `FctList-Process-Mode`

**Comment by smedilol** [comment]
We can still deliver this for v1.0.9

**Comment by collarbe** [comment]
Maybe is not usefull to generate Debuging line if debug mode is not enable.

**Comment by smedilol** [comment]
Following our last meeting (23/01/18), we need to keep debug lines into generated code even if debug mode is not enable.

**Comment by smedilol** [comment]
After tests made with 396395e, the result is not perfect, but we can wait for #801 to see if we can improve this.
