### ISSUE TITLE
Value clause is allowed in the description of procedure parameters and typed variable but is not used in codegen

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#791]
Currently value clause only works with type Date:
```cobol
01 C-DatePivot              TYPE Date VALUE '20190101'.
01 C-DefaultRate            TYPE Rate VALUE 3,55.
```

generated code is:
```cobol
      *01 C-DatePivot              TYPE Date VALUE '20190101'.
       01 C-DatePivot VALUE '20190101'.
           02 YYYY PIC 9(4).
           02 MM PIC 9(2).
           02 DD PIC 9(2).

      *01 C-DefaultRate            TYPE Rate VALUE 3,55.
       01 C-DefaultRate PIC S9(06)V9(08).
```

Clause value must be kept in generated code.

Another example for procedure:
```cobol
declare procedure Foor private
     input Param1 type Date value '20190101'.
data division.
working-storage section.
01 Var1 pic X value 'A'.
end-declare.
```

**Comment by fm-117** [comment]
Method TypedDataNode.ExtractAnyCobolScalarTypeDef uses only the typedef to generate the picture. Should the method be modified to take the datadefinitionentry and accounts for the value claue ?

**Comment by fm-117** [comment]
Order of declaration is not correcty supported. If VALUE clause is declared befor TYPE info, the result is wrong.

**Comment by fm-117** [comment]
Here is my plan to handle the VALUE clauses that may be declared after or before type info :
- [ ] Change `FlushConsumedTokens` method to stop outputting tokens on next keyword found
- [ ] Add a new `ExtractValueTokens`which will be responsible for extracting VALUE clauses tokens only
- [ ] Update all remaining `TypedDataNode.Extract*`methods to outpu only the part they are targetting (PIC, TYPE, etc)
- [ ] Add calls to `ExtractValueTokens` where necessary
I'd like to discuss this approach as there maybe lighter solutions.
