### ISSUE TITLE
Global-storage section

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#805]
Implement a `global-storage section` under `data division` to:
 - share data between procedure
 - share data between a program and its nested programs (same behavior as `GLOBAL` keyword in Cobol 85)
Data in `global-storage section` will have wider scope of `global` keyword.

## Rules
 - [x] **GLOBALSS** rules for codeElement grammar declaration of Global-Storage Section
 - [x] **GLOBALSS_POSITION** `Global-storage section` is declared after `file section` and before `working-storage section`
 - [x] **GLOBALSS_LIMIT48** You can declare data from level 01 to level 48 and level 77 (No 66). Level 88 is allowed under variable from 01 to 48.
 - [x] **GLOBALSS_NO_GLOBAL_KEYWORD** Keyword `GLOBAL` is forbidden under `Global-storage section`
 - [x] **GLOBALSS_NO_EXTERNAL** Keyword `EXTERNAL` is forbidden under `Global-storage section`
 - [x] **GLOBALSS_ONLY_IN_MAIN** `global-storage section` can only be declared in the first program of a source file (the main program)
- [x] **GLOBALSS_RANGE** Data declared in `global-storage section`  are accessible by the main program, all its procedures and all its nested programs.
   - Programs and procedures contained in nested programs can also access data declared in `global-storage section` 
   - Elements in data division of program or procedure cannot reference elements in `global-storage section`. Eg : From the `working-storage section`, you cannot write a `depending on ElementInGlobalStorage`.
- [x] **GLOBALSS_NOT_FOR_STACKED** Data declared in `global-storage section`  are not accessible by Stacked program
- [x] **GLOBALSS_ALWAYS_RESOLVE** Data declared in `global-storage section`  are always checked when we resolve variables. This is in contradiction of symbol resolution with global variable.
- [x] **GLOBALSS_NOTYPEDEF** The `global-storage section` cannot contains typedef declaration.

## Sample
TODO

## Codegen
 - [x] **GLOBALSS_CG_ENCAPSULATE_WITH_01_GLOBAL** Code generation will encapsulate all items in `Global-storage section` into a level 01 variable. This level 01 is named `TC-GlobalData` and is not marked `GLOBAL`.
 - [x] **GLOBALSS_CG_CREATE_STACKED_PROGRAM** A stacked program named with a hash based on the main program name must be created. 
Its definition is:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. a9a9a5ea.
       ENVIRONMENT DIVISION. *> use ENVIRONMENT DIVISION from the main program
       CONFIGURATION SECTION.
       SOURCE-COMPUTER.    IBM-3033. *> use
       SPECIAL-NAMES.      DECIMAL-POINT IS COMMA.
       data division.
       working-storage section.
      *Eye-Catcher
       01 PIC X(8) value ':TC:GBLS'.
       01 TC-GlobalData. *> var from rule GLOBALSS_CG_ENCAPSULATE_WITH_01_GLOBAL
       *> ## insert global storage vars here ##

       LINKAGE SECTION.
       01 GlobalPointer pointer.
       PROCEDURE DIVISION USING BY REFERENCE GlobalPointer.
           set GlobalPointer to address of TC-GlobalData
       .
       END PROGRAM a9a9a5ea.
```
Its `ENVIRONMENT DIVISION` must reused the one of the main program.

- [x] **GLOBALSS_CG_GLOBALDATA_LINKAGE** All programs (main, nested, stacked) and procedures that use at least one variable of the global-storage section must have the definition of `TC-GlobalData` in their linkage section.
```cobol
       data division.
       linkage section.
       01 TC-GlobalData. *> var from rule GLOBALSS_CG_ENCAPSULATE_WITH_01_GLOBAL
       *> ## insert global storage vars here ##
```

- [x] **GLOBALSS_CG_CALL_GETGLOBAL** The first instruction of procedure, main program, nested and stacked program that use the `global-storage section` must be 
```cobol
           CALL 'a9a9a5ea' USING
                    by reference address of TC-GlobalData
           end-call
```

This call can be placed after the call to TC-INITIALIZATIONS..

- [x] **GLOBALSS_CG_CALL_GETGLOBAL_MAINPRIVATE** A main program which use the `global-storage section` must have below instructions inside its paragraph `TC-INITIALIZATIONS` in the first `IF TC-FirstCall`
```cobol
       TC-INITIALIZATIONS.
            IF TC-FirstCall
                 SET TC-NthCall TO TRUE
                 CALL 'a9a9a5eaTC-GetGlobal' USING
                     by reference address of TC-GlobalData
                 end-call
                 *>Following of current code
```
- [x] **GLOBALSS_CG_COMMENT** The global-storage section must be commented.

TODO : create a wiki page with all theses rules.

EDIT : 2018/04/10 : Add rules **GLOBALSS_RANGE** and **GLOBALSS_NOT_FOR_STACKED**
EDIT : 2018/04/24 : Add codegen rules
EDIT : 2019/07/05 : The generated program name for global-storage must have a named based on the hash of the main program instead of  `a9a9a5eaTC-GetGlobal`.

**Comment by smedilol** [comment]
@reydelpa and @sarterbe what do you think of these rules?

@collarbe you can already think about the impact on SymbolTable

**Comment by collarbe** [comment]
@smedilol Can you check out if this unit test result is correct regarding to Global Storage Section rules : https://github.com/TypeCobolTeam/TypeCobol/blob/8a6837f43cab16313c43a02069416a536b2e7a4c/TypeCobol.Test/Parser/Programs/TypeCobol/GlobalStorageSection.rdzMix.txt

**Comment by smedilol** [comment]
Yes it's ok, except for some sentence that must start in column 8:
 * IDENTIFICATION DIVISION
 * PROGRAM-ID
 * \* division
 * \* section
 * paragraph
 * Level 01 data declaration
 * Level 77 data declaration

We need #378 to check these alignment.

Also, can you declare the same variable name in Global-storage section and in working-storage section and see if a move with this variable is ambiguous ?

**Comment by smedilol** [comment]
@sarterbe and @reydelpa are you ok with specs of codegen?

**Comment by smedilol** [comment]
@collarbe I didn't have the time to create unit test, can you see with Cobol devs?

We need at least:
- A main program with no environment division, 2 procedures. All use global
- A main program with no env division, 2 procedures. The main and one proc use global
- A main program with no env division, 2 procedures. Only procs use global
- A main program with no env division, 2 procedures. No code use global

- A main program with env division, 1 procedure. All use global
- A main program with env division and debugging, 1 procedure. All use global
- A main program and a nested. All use global

These tests should also test:
- A proc or pgm with no data division that use global
- A proc or pgm with data division but no linkage that use global
- A proc or pgm with data division and a linkage that use global

- A main program with no environment division, 2 procedures. All use only a typedef of global
