### ISSUE TITLE
LSP: Add ClientCapabilities support in TypeCobol.LanguageServer.

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#829]
For TypeCobol custom rules, we must use the" initialize" request and its ClientCapabilities parameters, with the experimental client capabilities field to allow them. But our current server implementations does not support ClientCapabilities, we must implement this feature in our TypeCobol.LanguageServer.

**Comment by smedilol** [comment]
This has been done with #1342
