### ISSUE TITLE
Allow procedure call even if types are not directly equals but primitive type are

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#834]
FOLLOWING #753 

TypeCobol Checker does not allow user to declare a procedure parameter with the following description pic S9(9) COMP-5 and a call that uses the variable of type Integer which description is identical to the procedure's parameter. 

In this example : 
```cobol
DECLARE PROCEDURE MyProc 
  INPUT Param1 pic S9(9) COMP-5.
END DECLARE.

01 Integer TYPEDEF STRICT pic S9(9) COMP-5.
01 MyInput1 TYPE Interger.

CALL MyProc INPUT MyInput1. 
```
The last line is in error.. it is not supposed to be. Because Integer's type description is identical to Param1 description.

**Comment by smedilol** [comment]
Won't  implement as TypeCobol language is no longer supported.
