### ISSUE TITLE
Make procedure parameter completion, signature context sensitive

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#835]

**Comment by collarbe** [comment]
Two problematic for this issue : 
- In case there is multiple signature available, the client will show a selection list of all the potential signature. The server will not select any signature because he doesn't what to do at this stage. Then, the client will allow the user to select a signature and it will display the pop-up to show the awaited parameters. The server will never know which signature has been chosen, it will not be able to use the user context.. 

- In case the user has already typed an argument, the signature help will be able to determine the most valuable signature to use. It will select it and set it as the procedure completion context. In case the client interface, show a list of potential signatures and the user select a different one from the server, the server will not be notified and it will not be able to perform a relevant completion. 

To resolve these situations, regarding to our technical context, I think the client should send the procedure completion context to the server. So that it will know what to do. 
Otherwise, the client has to change and let the server handle the whole workflow for signature helper. So it will be able to manage properly the user context. 

@smedilol & @mayanje we need to discuss this point

**Comment by mayanje** [comment]
Sure we shall discuss this point, because it is not clear to me what shall be case sensitive, and according to what?

**Comment by collarbe** [comment]
The notification will be as follow : 

```C#
public static readonly NotificationType Type = new NotificationType("typecobol/signatureHelpContext", typeof(SignatureHelp));
```
