### ISSUE TITLE
Completion is not working perferctly with ZERO or SPACE keyword

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#845]
The following does not work properly. 

```COBOL
01 MyType TYPEDEF STRICT PRIVATE.
   05 NumberOfParams PIC 9(08) COMP. 
   05 NumberOfExecution PIC 9(08). 

01 MyTypedVar TYPE MyType. 

MOVE ZERO TO NumberOf
```

Completion will sometimes propose both variable, sometimes only one... 

Edit Olivier : the priority is completion after:
- space (space is alphabetic variable)
- spaces (spaces is alphabetic variable)
- zero (zero is alphanumeric variable)

**Comment by collarbe** [comment]
ZERO seems also compatible with Numeric variable.

**Comment by smedilol** [comment]
A LSR unit test will be great for this issue
