### ISSUE TITLE
Create intrinsic type Currency

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#862]
Create type currency like this:
```cobol
01 Currency typedef strict pic X(03).

01 var1 type Currency.
```
The problem is `currency` is a keyword.
This type must be created directly in the grammar like type `Date`

**Comment by collarbe** [comment]
Not sure it's a good idea to create type like this inside the TypeCobol Parser code. 

I rather think that if `Currency` is a keyword, the developper should  use an other name for his type. Something like `CurrencyType`

**Comment by smedilol** [comment]
@mayanje reminds me that we could use verbatim syntax like C# to declare Currency type:
```cobol
01 @Currency typedef strict pic X(3).
```

**Comment by smedilol** [comment]
As discussed:
- We only need the currency type, not the amount. The amount type can be added with our intrinsic mechanism.
- No need for exchange rate
