### ISSUE TITLE
Remove fake Node Sentence

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#866]
Sentence Node is used for code generation only.
We should remove it and use a better technique to generate our code.
This will impact Razor template.

**Comment by mayanje** [comment]
Based on the work made with #1028, we can now start reviewing all skeleton templates

**Comment by mayanje** [comment]
Can we move this issue in v1.4 ?

**Comment by smedilol** [comment]
Yes, that's not urgent

**Comment by mayanje** [comment]
ok to move it to v1.4.

**Comment by smedilol** [comment]
Following an internal discussion, Sentence node is mandatory for Control flow / data flow.
We must keep it.
