### ISSUE TITLE
Cobol CALL does not check if variable exists

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#930]
This code will not generate any error : 

```COBOL
CALL undefiniedVariable USING myVariable.
```

This call is a simple Cobol call. The parser is not checking if the given variable after call is defined or not.

**Comment by cobarzanc** [comment]
An error should be raised when "myVariable" is not defined but is used as a parameter for the "undefinedVariable" function.

**Comment by cobarzanc** [comment]
@collarbe I cannot reproduce the issue. If I have in a program


       Procedure division
         CALL undefiniedVariable USING var1OK.
       END-DECLARE.


I get the following error:

`<27, Error, Syntax> - Syntax error : Symbol undefiniedVariable is not referenced. `

Can you provide a complete example if you encountered a different use case where there is no error generated?

**Comment by collarbe** [comment]
@cobarzanc 
The issue seems to be fixed ! May it comes from some changes I made in CrossChecker in the last issues. 
Thanks for checking.

To close this issue, you can add/update a unit test.
