### ISSUE TITLE
Map StorageArea/Variable to their DataDefinition

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#967]
On CodeElement we have:
StorageAreaReads
StorageAreaWrites

On Node we could have:
 IDictionary<StorageArea, DataDefinition> StorageAreaReadsDataDefinition
 IDictionary<ReceivingStorageArea, DataDefinition> StorageAreaWritesDataDefinition

These properties will retain the DataDefinition of a StorageArea.

This will avoid several call to SymbolTable.getVariables().

**Comment by smedilol** [comment]
As explained in #979:
The Dictionary at the Node level, will contains StorageArea read/write of storageAreaGroupsCorrespondingImpact.

This is not exactly right, but it'll be treated in another issue.

**Comment by cobarzanc** [comment]
For now, the SymbolTable is still used in the following methods or classes

- RenameChecker class - Check method - the node does not have any StorageArea in the CodeElement, so the Dictinary cannot be constructed

- FunctionCallChecker class - OnNode method -  the node does not have any StorageArea in the CodeElement, so the Dictinary cannot be constructed

- ProcedureDivision class - CreateName method - the node does not have a CodeElement attached when the method is called in the call stack

- CrossCompleteChecker class - Visit(IndexDefinition) method - the node does not have a CodeElement attached when the method is called in the call stack
