### ISSUE TITLE
Incremental parsing bug with IDENTIFICATION DIVISION

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#969]
Incremental parsing has a bug when deleting IDENTIFICATION DIVISION. then doing Ctrl+Z. 

The textChange event property range is null. Because range is null, LSP, is determine that it's better to reload the document based on the text sent. So it reopen the file but only has "IDENTIFICATION DIVISION." as source text.

**Comment by collarbe** [comment]
I've tried to optimize incremental parsing when IDENTIFICATION Division is deleted, but i'm facing a lot of troubles... 
As a result I can't find a way to make it works without breaking something else. The Antlr TokensItterator and CodeElementParser are really hard to handle... 
I think that we should wait until CUP comes on CodeElement parsing in order to rebuild the incremental part...

**Comment by smedilol** [comment]
Seems to be fixed.
It must have been done by #2157.
