### ISSUE TITLE
Remove unuseful code in CrossChecker ?

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#996]
Issue only apply if #977 is merged into develop.

Method 
`public static DataDefinition CheckVariable(Node node, StorageArea storageArea, bool isReadStorageArea)` in CrossChecker, search for existing data definitinon before constructing one.

But as CheckVariable is only called once per StorageArea, this code shouldn't be useful.

Try to see if we can remove this code:
```C#
//search for existing data definitinon before constructing one
            Tuple<string,DataDefinition> searchExistingDataDefinition;
            if (isReadStorageArea)
            {
                node.StorageAreaReadsDataDefinition
                    .TryGetValue(storageArea, out searchExistingDataDefinition);
            }
            else
            {
                node.StorageAreaWritesDataDefinition
                    .TryGetValue(storageArea, out searchExistingDataDefinition);
            }
            if (searchExistingDataDefinition!=null)
            {
                IndexAndFlagDataDefiniton(searchExistingDataDefinition.Item1, searchExistingDataDefinition.Item2,node,area,storageArea);
                return searchExistingDataDefinition.Item2;
            }
```

**Comment by cobarzanc** [comment]
After analysis, the highlighted code is not useful anymore. CheckVariable method is used only to build the dictionaries, so we should not make any search in the dictionaries.
