### ISSUE TITLE
Formalized comment syntax for documentation generation.

### ISSUE THREAD

**Issue by Brochato** [TypeCobolTeam/TypeCobol#998]
**Report of Meeting of 2018/06/19**
This meeting follow the [meeting of 2018/04/05](https://github.com/TypeCobolTeam/TypeCobol/issues/891).

# Comment Usage

The formalized comment purpose is to set some meta-informations in order to clarify the TypeCobol source and auto-generate a documentation based on that comment and the commented structure itself.
The applicable structures are:
- a function/procedure declaration (with the formalized comment above the Identification Division)
- a type declaration  (with the formalized comment above the TypeDefinition)
- a program declaration  (with the formalized comment above the Procedure Division)

# Formalisation of the comment

## structure recognition

A formalized comment is delimited by the opening marckup `*<<<` and the closing marckup `*>>>`. those markups must start at column 7.

The comment fields are recognised by the at sign (`@`) and the hyphen (`-`).
Thereby a statement can overflow on the next line if it do not begin with an at sign or a hyphen.

There is no restriction in parameter naming as the hyphen is used.

A colon (`:`) can be placed between the keyword and its value for clarity purpose but it is optional.

Correct
```cobol
*<<< 
    @parameters:
        -bDate  BirthDate – the date the person
is born
        - subject: The person that we have to calculate the age - see 
                Person type
        -    outAge:  The age returned by the function
        - deprecated Indicate if the age is calculated with the deprecated way
    @deprecated:
*>>>
declare procedure age public
    input  bDate type Date
           subject type Person
           deprecated type BOOL
    output outAge PIC S9(3)
```

Not Correct
```cobol
*<<< 
    @ parameters
        - bDate:   BirthDate – the date the person is born
        - subject: The person that we have to calculate the age 
                - see Person type
    @ outAge  The age returned by the function
    - deprecated: Indicate if the age is calculated with the deprecated way
    @ deprecated   *>>>
declare procedure age public
    input  bDate type Date
           subject type Person
           deprecated type BOOL
    output outAge PIC S9(3)
```

## Keywords

Keywords are used to clarify and to structure the documentration.
Keywords are not case sensitive.

### @description OR @desc

Discribe the function/type/Program.
Is implicit if no keyword is given.
Accept only one value.

```cobol
*<<<
    @description : Take 2 Integer and return the sum. 
*>>>
```
OR (if no keyword is given before)
```cobol
*<<< Take 2 Integer and return the sum.
*>>>
```

### @parameters OR @params

List function or program parameters in order to describe them.
Accept a list of key value pair.
The key is the first word after the hyphen (`-`) and is a parameter name

```cobol
*<<<
    @parameters:
        - bDate   BirthDate – the date the person is born
        - subject: The person that we have to calculate the age
        - outAge :  The age returned by the function
*>>>
```

### @deprecated OR @deprec

Flag the function/type as deprecated.
Can be use as standalone or can accept a value.

```cobol
*<<<
    @deprecated:
*>>>
```
OR
```cobol
*<<<
     @ deprec Can not handle BOOL variables. 
*>>>
```

### @replacedBy / @replBy

If the Function/Type/Program have a better replacer, indicate it here.
Accept only one value.

```cobol
*<<<
     @replacedBy : please use MyFunction2 wich handle BOOL variables.
*>>>
```

###  @restriction OR @rstric

Indicate a restriction.
Accept only one value.

```cobol
*<<<
     @restriction : Do not use a pointer as first parameter.
*>>>
```

### @need

Indicates the needs of the fonction.
Accept a list of value or a single value.

```cobol
*<<<
     @need : Be on debug mode
*>>>
```
OR
```cobol
*<<<
     @need
         -  Be on debug mode
          - Have a hot full coffee mug
*>>>
```

### @see

Can contain a reference or a linked element.
Accept only one value.

```cobol
*<<<
     @see : For better undersanding please see issue #891.
*>>>
```

### @ToDo

Indicate Todos.
Accept a list of value or a single value.

```cobol
*<<<
     @todo add BOOL support
*>>>
```
OR
```cobol
*<<<
    @todo:
        - Add BOOL support 
        - implement a call counter
*>>>
```

### restriction by commented structure

Both Program and Function handle the full formalized comment Keywords but Type Definition does not support parameters keyword. If a parameters keyword is set on a TypeDefinition formalised comment it would be ignored and a warning will be set. 

# Documentation generation

The Documentation will be generated with the folowing informations:

### For Programs:
- Formalized Comment content
- name
- namespace

### For Functions:
- Formalized Comment content
- name
- namespace
- visibility

### For Types:
- Formalized Comment content (exept parameters)
- name
- namespace
- visibility
- Type DataType
- each childrens and for each of them (if any) their DataType

**Comment by smedilol** [comment]
Hello,

Thanks for this report.
My remarks :
A documentation is generated if the comment is placed before:
- a function/procedure declaration
- a type declaration
**- a program**


Description or desc keyword can be removed according to me. It's always implicit.

**Comment by smedilol** [comment]
Also:
For program documentation, we don't know if a parameter is input, output.
So instead of keywords `parameters` we should force ot use `input`, `in-out` and `output`.

**Comment by collarbe** [comment]
@smedilol  During the meeting, we said that it's not usefull to precise the type of parameter (input/output/in-out) because we should use the procedure signature in the documentation

**Comment by smedilol** [comment]
yes for procedure, but for program we don't have this information.
