### ISSUE TITLE
Pointer declararion in Type always generate a redifine

### ISSUE THREAD

**Issue by Brochato** [TypeCobolTeam/TypeCobol#999]
Following #780.

If a pointer is declared in a Type, a redefine statement will always be added and an OCCURS instruction will be overrided.
In the check step, for a no-type pointer, a flag is set on the pointer Node when the set statement is checked. But with a type the pointer Node belongs to the Type and is common for every implementation of this Type.
As a result we can no longer flag a pointer Node for generating the redefine for a precise implementation of the type.

```cobol
01 MyType.
    05 myPointer POINTER.

01 pointer0 Type MyType.
01 pointer1 Type MyType.

Set pointer0::myPointer  UP BY 1.
```

The probleme is on the Set statement check, we have no way to get the dataDefinition of the pointer specific to the type implementation.
In this case, no way to link ```myPointer``` to ```pointer0```.

**Comment by smedilol** [comment]
TypeCobol is abandonned, this issue is not needed anymore.
